### ISSUE TITLE
🐛 BUG: Uncaught ReferenceError: global is not defined 

### ISSUE THREAD

**Issue by dangvanthanh** [cloudflare/workers-sdk#6084] opened 2024-06-19 08:07 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

Wrangler

### What version of Node are you using?

22.3.0

### What operating system and version are you using?

Mac Sonoma 14.5

### Observed behavior

When run `npx wrangler pages deploy dist`. It's deployment failed.

### Expected behavior
Deployment success.

### Steps to reproduce

I running build and deploy using Nuxt 3.12.2. It's build sucessfully but can not deployment to cloudflare.

```shell
pnpm run build && wrangler pages deploy
```

![Screenshot 2024-06-19 at 3 06 36 PM](https://github.com/cloudflare/workers-sdk/assets/2674850/5d2fb200-6cd7-49e6-b126-f78cfb8399b1)

![Screenshot 2024-06-19 at 2 57 52 PM](https://github.com/cloudflare/workers-sdk/assets/2674850/2ec7e17e-7eb2-4414-828c-69c1e0f86567)

**Comment by Saganic** [comment] 2024-07-01 14:52
+1 seeing this upstream in a nuxthub project

**Comment by CarmenPopoviciu** [comment] 2024-07-19 11:35
hi @dangvanthanh 

The issue at hand here is that `global` is not exposed in the Workers Runtime by default, only `globalThis` is. I'm not sure how `global` is referenced in your case, whether you reference it directly in your Functions code, or if it comes from a third-party dependency. Regardless, there are things that can help out here:

1. use `globalThis` instead of `global` if you are referencing `global` yourself, or use `globalThis.global = globalThis` in your Functions code if you don't have direct access to the code that references `global`
2. use the experimental `experimental:nodejs_compat_v2` compatibility flag which exposes `global` directly

-  either in your `wrangler.toml` file if you use one

```
# wrangler.toml
compatibility_f;ags = ["experimental:nodejs_compat_v2"]
```

- or passed as `wrangler pages deploy [directory] --compatibility-flags="experimental:nodejs_compat_v2"`

A big word of warning around using `experimental:nodejs_compat_v2` though, since this is very experimental and not recommended for production applications. It also seems to have a bug when used for Pages at the moment (see https://github.com/cloudflare/workers-sdk/issues/6288), which we'll need to look into and fix.

My recommendation is to try and use the first option if possible, and let us know if that helped!

**Comment by dangvanthanh** [comment] 2024-07-19 16:22
Thanks so much @CarmenPopoviciu 

I try 2 solutions but I can't deployment on Cloudflare now.

I see when I use with some package such as [argon2](https://www.npmjs.com/package/argon2)...I can't deployment, too.

Now I try check these packages I use, it take a long time. It's maybe error when I use some packages. Because I was deployed successfully before.

**Comment by CarmenPopoviciu** [comment] 2024-07-22 17:44
@dangvanthanh any chance you have a reproduction at hand we could look at?

**Comment by dangvanthanh** [comment] 2024-07-23 02:42
@CarmenPopoviciu 

I created repository for this issue: https://github.com/dangvanthanh/nuxt-to-pages

```sh
$ cd apps/web
$ bun run deploy
```

The issue when deploy:

![Screenshot 2024-07-23 at 9 36 45 AM](https://github.com/user-attachments/assets/32372772-2079-4d1b-a013-00fdabd3dd4e)

**Comment by huynamboz** [comment] 2024-08-12 17:40
same issue with nuxt3, deploy to vercel work but cloudflare not
![image](https://github.com/user-attachments/assets/87b53047-ff94-4c95-8081-ef00730ff510)

**Comment by thijsw** [comment] 2024-08-20 18:26
For me, this issue is resolved when I add `vue-router` as an explicit dependency, see: https://github.com/nuxt/nuxt/issues/28248#issuecomment-2241749620

**Comment by huynamboz** [comment] 2024-08-21 04:31
> For me, this issue is resolved when I add `vue-router` as an explicit dependency, see: [nuxt/nuxt#28248 (comment)](https://github.com/nuxt/nuxt/issues/28248#issuecomment-2241749620)

Not working for me
![image](https://github.com/user-attachments/assets/8790153c-6e07-46ea-a5b8-7ee16b974901)
![image](https://github.com/user-attachments/assets/19e19f2f-19e9-44e5-a321-5cd6aad0f948)

**Comment by dangvanthanh** [comment] 2024-08-21 05:42
@thijsw 

Thanks. But not working for me, too.

**Comment by CarmenPopoviciu** [comment] 2024-09-09 13:59
hi @dangvanthanh 

thank you so much for putting that repro repository together 🙏 . I tested it locally by running

1. `cd apps/web`
2. `npm run build`
3. `npx wrangler pages dev` / `npx wrangler pages deploy`

and everything worked fine for me 👇 

<img width="723" alt="Screenshot 2024-09-09 at 15 45 39" src="https://github.com/user-attachments/assets/572ec4ac-ec94-489a-ba1d-9449f50ce796">

In fact, this works for me with or without adding `compatibility_flags = ["nodejs_compat_v2"]` in the toml file. I'm wondering if the issue you're experiencing is because you're running `deploy` via `bun`?

Can you please confirm whther deploying via `wrangler pages deploy` works for you 🙏 ?

**Comment by dangvanthanh** [comment] 2024-09-10 02:49
@CarmenPopoviciu 

Now, it's working for me. Even without adding `compatibility_flags = ["nodejs_compat_v2"]` in `wrangler.toml`

**Comment by CarmenPopoviciu** [comment] 2024-09-10 07:14
fantastic! 

In case you run into similar Nodejs compat issues, have a look at https://blog.cloudflare.com/more-npm-packages-on-cloudflare-workers-combining-polyfills-and-native-code/ which was just published. There are more details in there about the `nodejs_compat_v2` compat flag and our plans regarding Nodejs API support. Hope that helps <3

Closing this issue as it looks like all works as expected now

**Closed by CarmenPopoviciu** 2024-09-10 07:14 UTC
Labels: awaiting reporter response, bug
