### ISSUE TITLE
🐛 BUG: Publishing a worker failed with `script_not_found` even though the script published fine

### ISSUE THREAD

**Issue by vlovich** [cloudflare/workers-sdk#3347] opened 2023-05-25 20:47 UTC
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

Linux

### Describe the Bug

A script I generally have no problem publishing in Cloudflare CI flaked and failed to deploy:
```
    Your worker has access to the following bindings:
    - Services:
      - TC_SERVICE: ***** - production
    - Vars:
      - ENVIRONMENT: "staging"
    }
13:30:50     Total Upload: 168.04 KiB / gzip: 39.76 KiB
13:30:52     Uploaded ops-staging (1.76 sec)
13:30:52     Published ops-staging (0.14 sec)
      https://ops-staging.*****.workers.dev
13:30:52     
13:30:52     ��� [ERROR] A request to the Cloudflare API (/accounts/2ef55e4ecc83f62321****/workers/deployments/by-script/680e0e21f9ba4****) failed.
    
      workers.api.error.script_not_found [code: 10007]
      
      If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```
I spelunked through the wrangler logs and didn't see any evidence this had been fixed.

Joe Lee suggested that maybe there's some kind of race condition within wrangler around listing after publishing?

**Comment by s-karki** [comment] 2023-05-26 00:51
I'm getting a similar issue on Wranger 3.0.1. A worker deployment that was working yesterday is now failing. 

```
Total Upload: 6.35 KiB / gzip: 2.08 KiB
--
  |  
  | ✘ [ERROR] A request to the Cloudflare API (/accounts/6ee1860165d88a273b3d5c8994262b8d/workers/scripts/cloudflare-worker-staging-jora-dot-com) failed.
  |  
  | workers.api.error.malformed_param: must specify either 'script' or 'service' [code: 10004]
  |  
  | If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose

```

**Comment by vlovich** [comment] 2023-05-26 01:20
@s-karki that looks like a different unrelated issue, especially if it's failing consistently. This was a one-off flake. I'd recommend opening a separate issue.

**Comment by penalosa** [comment] 2024-05-01 16:21
Closing for now, since this was a one-off flake. We can re-examine if this becomes a more consistent problem.

**Closed by penalosa** 2024-05-01 16:21 UTC
Labels: bug

**Comment by imWildCat** [comment] 2024-06-14 20:08
same here:

```
npx wrangler tail [name]

 ⛅️ wrangler 3.60.3
-------------------


✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/xxx/bindings) failed.

  workers.api.error.script_not_found [code: 10007]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```
not sure why

**Comment by petebacondarwin** [comment] 2024-06-25 05:18
It looks like it fails to look up the binding for a worker, even though the worker has clearly been deployed (since the lines directly before that bindings lookup pull down the script content of that worker.) I wonder if that issue is something related to changes added due to gradual rollout versions?

Here is the code where the error is being triggered:

https://github.com/cloudflare/workers-sdk/blob/489b9c51550d583d50e262f5905393501c2d6419/packages/wrangler/src/tail/index.ts#L138-L142

Apparently this particular bit of code is no longer needed, as DOs are no longer reset. So it could be removed. But that doesn't help identify the cause of the problem.

**Comment by irvinebroque** [comment] 2024-07-18 22:22
refs https://github.com/cloudflare/workers-sdk/issues/6289
