### ISSUE TITLE
🐛 BUG:  [ERROR] statement too long

### ISSUE THREAD

**Issue by jonathangreensted** [cloudflare/workers-sdk#6146] opened 2024-06-25 15:03 UTC
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

wrangler 3.62.0

### What version of Node are you using?

v21.6.2

### What operating system and version are you using?

Mac Sonoma 14.5 (23F79)

### Observed behavior
Errors with "statement too long" when running an export file created using:

wrangler d1 export dev-rentiful --remote --output webhooks.sql --table  Webhooks

Then executed against --local using:

npx wrangler d1 execute dev-rentiful --local --file=webhooks.sql --env dev

### Expected behavior
Complete succcessfully and have a copy of the --remote table --local for development.

### Steps to reproduce
The above steps are sufficient to recreate.

There is a large amount of JSON data in a single column in the Webhook table but it really shouldn't error with something that was exported successfully.

webhooks.sql attached.

[webhooks.sql.zip](https://github.com/user-attachments/files/15973425/webhooks.sql.zip)

**Comment by petebacondarwin** [comment] 2024-07-01 13:32
Duplicate of https://github.com/cloudflare/workers-sdk/issues/4510

**Closed by petebacondarwin** 2024-07-01 13:32 UTC
Labels: bug, d1
