### ISSUE TITLE
🐛 BUG:CREATE TRIGGER containing unparenthesized CASE..END fails with "incomplete input"

### ISSUE THREAD

**Issue by deliciousreya** [cloudflare/workers-sdk#4727] opened 2024-01-09 02:33 UTC
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

v21.5.0

### What operating system are you using?

Linux (Pop! OS 22.04 LTS)

### Describe the Bug

CREATE TRIGGER misunderstands the END of a CASE outside of parentheses as belonging to itself. It does not have this problem for a parenthesized CASE, so **parenthesizing the CASE..END is the simplest workaround**. (for anyone coming to this bug looking for a workaround)

The parentheses can be directly around the CASE or be surrounding a sub-SELECT. 

The most basic pair of statements which trigger this behavior are:
```sql
CREATE TABLE IF NOT EXISTS demo (id INTEGER PRIMARY KEY);
CREATE TRIGGER IF NOT EXISTS broken_select AFTER INSERT ON demo BEGIN
    SELECT CASE WHEN TRUE THEN TRUE END;
END;
```

But a more comprehensive repro showing the investigation I've done into which statements work and which don't is linked.

### Please provide a link to a minimal reproduction

https://gist.github.com/deliciousreya/2fe66f335dfb084d93bb478782a0d210

**Comment by RamIdeas** [comment] 2024-06-24 13:33
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/4326

**Closed by RamIdeas** 2024-06-24 13:33 UTC
Labels: bug, d1
