### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by iritikyadav123** [cloudflare/workers-sdk#5502] opened 2024-04-04 08:55 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.32.0

### What version of Node are you using?

20.12.0

### What operating system and version are you using?

windows 10

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

when ever I am trying to run cloudflare locally I get write EOF error.

C:\Users\SHREE RAMA\OneDrive\Desktop\New folder (6)\my-app\node_modules\wrangler\wrangler-dist\cli.js:29573
            throw a;
            ^

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}

**Comment by ygweric** [comment] 2024-04-09 09:33
same bug, hope to be fixed ASAP

**Comment by ygweric** [comment] 2024-04-10 05:43
> same bug, hope to be fixed ASAP
Reinstall node.js with **Automatically install the necessary tools** works for me 👍
ref:  https://github.com/cloudflare/workers-sdk/issues/4412#issuecomment-2046535473

**Comment by iritikyadav123** [comment] 2024-04-21 20:50
> > same bug, hope to be fixed ASAP
> 
> Reinstall node.js with **Automatically install the necessary tools** works for me 👍 ref: [#4412 (comment)](https://github.com/cloudflare/workers-sdk/issues/4412#issuecomment-2046535473)

i am still getting same error

**Comment by penalosa** [comment] 2024-05-02 10:17
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by petebacondarwin** [comment] 2024-06-17 18:39
Closing as there is no reproduction for us to debug.

**Closed by petebacondarwin** 2024-06-17 18:39 UTC
Labels: awaiting reporter response, bug
