### ISSUE TITLE
🐛 BUG: fsevents.code, escode Not Opened causing failure to start npx wrangler dev

### ISSUE THREAD

**Issue by nitbu** [cloudflare/workers-sdk#6919] opened 2024-10-08 01:54 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.1

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

Mac Sequoia 15.0

### Describe the Bug

Fresh upgrade to MacOS Sequoia 15
Fresh install brew install node
Fresh install npm install -g @cloudflare/wrangler
Fresh upgrade npm update -g @cloudflare/wrangler

Run:
npx wrangler dev --persist-to ./localData --config ./main.toml

System errors:
1. (x2)
“fsevents.node” Not Opened
Apple could not verify “fsevents.node” is free of malware that may harm your Mac or compromise your privacy.
[Done] [Move to Trash]
2. (x2)
“esbuild” Not Opened
Apple could not verify “esbuild” is free of malware that may harm your Mac or compromise your privacy.
[Done] [Move to Trash]

Wrangler partially loads by clicking `Done` through two `fsevents.node` errors, and then fails without error when clicking [Done] to `esbulid`

Doesn't look like a wrangler specific problem but is there a workaround or anything that can be done to get this running again?

**Comment by andyjessop** [comment] 2024-10-08 11:06
Thanks very much for reporting this. I don't believe there's anything to do on our end, but one thing I might suggest is to install node with nvm, which may help avoid permissions issues.

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
nvm install node
npm install -g @cloudflare/wrangler
```

I'll close this for now, as it's not clear that it's something that we can fix.

**Comment by threepointone** [comment] 2024-10-08 13:21
To clarify the package name, it should be `wrangler`, not `@cloudflare/wrangler` (which is deprecated)

**Comment by threepointone** [comment] 2024-10-08 13:46
I think this might be related to sequoia. I'll be installing sequoia this week and I'll test it myself.

**Comment by nitbu** [comment] 2024-10-14 03:46
brew uninstall node
brew install nvm

[--unrelated system configuration--]
mkdir ~/.nvm
export NVM_DIR="$HOME/.nvm"
export NVM_SYMLINK_CURRENT=true
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
source ~/.zshrc
[-- --]

nvm install -g wrangler
npx wrangler dev --persist-to ./localData --config ./main.toml

This, uninstalling node and then using nvm to reinstall install it, has resolved my issue. Thanks.

**Closed** 2024-10-14 03:46 UTC
Labels: bug, awaiting Cloudflare response

**Comment by FlyingAvatar** [comment] 2024-12-18 23:48
I am leaving this comment here since this is the only page the comes up in search for these errors:

Apple could not verify “esbuild” is free of malware that may harm your Mac or compromise your privacy.
Apple could not verify "fsevents.code" is free of malware that may harm your Mac or compromise your privacy.

I ran into this error and it took me quite some time to figure it out.  It turns out the issue was caused by:

(a) My code is executed from a mounted Sparse Bundle disk image which I do to have a case-sensitive file system
(b) I copied this Sparse Bundle from a backup drive after reformatting my Mac to do a fresh install of Sequoia

It seems that Apple's security system treats bundles from a 'foreign' origin differently, which triggered the error.  I created a new sparse bundle and copied all the code from the old one to the new, locally generated one and all the errors were solved.

**Comment by evisong** [comment] 2025-01-13 04:27
> I am leaving this comment here since this is the only page the comes up in search for these errors:
> 
> Apple could not verify “esbuild” is free of malware that may harm your Mac or compromise your privacy. Apple could not verify "fsevents.code" is free of malware that may harm your Mac or compromise your privacy.
> 
> I ran into this error and it took me quite some time to figure it out. It turns out the issue was caused by:
> 
> (a) My code is executed from a mounted Sparse Bundle disk image which I do to have a case-sensitive file system (b) I copied this Sparse Bundle from a backup drive after reformatting my Mac to do a fresh install of Sequoia
> 
> It seems that Apple's security system treats bundles from a 'foreign' origin differently, which triggered the error. I created a new sparse bundle and copied all the code from the old one to the new, locally generated one and all the errors were solved.

Thanks for sharing. My case is similar, FYI.

The issue was revealed when I opened my project in VSCode, but macOS prompt:

```
“fsevents.node” Not Opened
Apple could not verify “fsevents.node” is free of malware that may harm your Mac or compromise your privacy.
```

Here is how I produced the issue:

I'm recently switching my laptop from an M1 Pro (2021) to M4 Pro (2024), the former's OS is macOS Sonoma 14.4 while the latter's is Sequoia 15.2. To migrate my ongoing projects, I compressed the workspace dir as zip, copied the zip to new laptop, and unzipped it. Then when I opened the project in VSCode on my new laptop, the error prompt above appeared.

I believe the root cause is the same as @FlyingAvatar. 

To fix this, I simply deleted all `node_modules` and reinstalled the npm packages:

```sh
rm -rf ./**/node_modules
yarn install
```

**Comment by Oberoi-consulting** [comment] 2025-02-20 10:44
Update how i fixed it in 2025.

I'm on MacOS Sequoia 15.3.1.

After having the pop up about the 'fs_event', 
go to Settings->Privacy & Security
scroll down to Security section
'fs_event' -> click open anyway
then if needed reinstall npm in your local directory, that helped me.

**Comment by Peter-Cumming** [comment] 2025-02-27 11:55
@Oberoi-consulting this worked for me too 🙌🏼
