### ISSUE TITLE
🐛 BUG: create cloudflare with Astro is broken with Error parsing file: src/env.d.ts

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#7492] opened 2024-12-09 20:07 UTC
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

2.33.3

### What version of Node are you using?

22.11.0

### What operating system and version are you using?

Mac

### Observed behavior
```
👋 Welcome to create-cloudflare v2.33.3!
🧡 Let's get started.
📊 Cloudflare collects telemetry about your usage of Create-Cloudflare.

Learn more at: https://github.com/cloudflare/workers-sdk/blob/main/packages/create-cloudflare/telemetry.md
────────────────────────────────────────────────────────────────────────────────

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./wandering-brook-8ac6
│
├ What would you like to start with?
│ category Framework Starter
│
├ Which development framework do you want to use?
│ framework Astro
│
├ Continue with Astro via `pnpm dlx create-astro@4.10.0 wandering-brook-8ac6 --no-install`
│

Packages: +30
++++++++++++++++++++++++++++++
Progress: resolved 30, reused 21, downloaded 9, added 30, done

 astro   Launch sequence initiated.

      ◼  dir Using wandering-brook-8ac6 as project directory

  tmpl   How would you like to start your new project?
         Empty

    ts   Do you plan to write TypeScript?
         Yes

   use   How strict should TypeScript be?
         Strict
      ◼  No problem! Remember to install dependencies after setup.

   git   Initialize a new git repository?
         Yes

      ✔  Project initialized!
         ■ Template copied
         ■ TypeScript customized
         ■ Git initialized

  next   Liftoff confirmed. Explore your project!

         Enter your project directory using cd ./wandering-brook-8ac6 
         Run pnpm dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat

╭──🌲─╮  Houston:
│ ◠ ◡ ◠  Good luck out there, astronaut! 🚀
╰─────╯

├ Copying template files
│ files copied to project directory
│
├ Installing dependencies
│ installed via `pnpm install`
│
╰ Application created 

╭ Configuring your application for Cloudflare Step 2 of 3
│
├ Installing wrangler A command line tool for building Cloudflare Workers
│ installed via `pnpm install wrangler --save-dev`
│
├ Installing @cloudflare/workers-types
│ installed via pnpm
│
├ Adding latest types to `tsconfig.json`
│ added @cloudflare/workers-types/2023-07-01
│
├ Retrieving current workerd compatibility date
│ compatibility date 2024-12-05
│
├ Installing adapter
│ installed via `pnpm astro add cloudflare`
│
├ Updating configuration in astro.config.mjs
│
├ Adding type declarations in src/env.d.ts
│
╰  ERROR  Error: Error parsing file: src/env.d.ts
```

### Expected behavior

Should scaffold the project

### Steps to reproduce
Please provide the following:

- `npm create cloudflare`
- select framework + astro
- accept defaults

**Comment by dario-piotrowicz** [comment] 2024-12-10 14:08
This issue is actually a duplicate of https://github.com/cloudflare/workers-sdk/issues/7416, since the other one was created first I'm closing this one 🙂 (either way this should be fixed in #7497)

**Closed by dario-piotrowicz** 2024-12-10 14:08 UTC
Labels: bug
