### ISSUE TITLE
🚀 Feature Request: Allow local Service Bindings to proxy to a `wrangler dev --remote` session

### ISSUE THREAD

**Issue by thipperz** [cloudflare/workers-sdk#5578] opened 2024-04-10 18:19 UTC
### Describe the solution

When I try to acess a rpc Service Binding in my next-on-pages application:

`Error: Cannot access 'ImageSearch' as we couldn't find a 'wrangler dev' session for service 'vectorize-worker' to proxy to.`

As the error says, I should run `wrangler dev` to test locally and it works when running `wrangler pages dev` (it do not work with `next dev` but that is [another story](https://github.com/cloudflare/workers-sdk/issues/5577).

However, my "vectorize-worker" do need to access both Vectorize, and production R2 buckets. 

For Vectorize, this means it needs `wrangler dev --remote` to work, as it says:

`Vectorize bindings are not currently supported in local mode. Please use --remote if you are working with them.`

And so does R2 non-preview buckets.

Then we can go back to my initial error:
`Error: Cannot access 'ImageSearch' as we couldn't find a 'wrangler dev' session for service 'vectorize-worker' to proxy to.`

The only way out of my situtation would be if it could proxy to a "wrangler dev --remote" session too.

I hope this makes sense!

**Comment by smallbraingames** [comment] 2024-07-02 01:43
Is this fixed yet? or does vectorize only work in prod still

**Comment by penalosa** [comment] 2024-07-22 16:58
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/1182 (tracked in the Mixed Mode section)

**Closed by penalosa** 2024-07-22 16:58 UTC
Labels: enhancement
