### ISSUE TITLE
🐛 BUG:  `wrangler generate` doesn't work on Windows

### ISSUE THREAD

**Issue by ShivamGuptaKennect** [cloudflare/workers-sdk#2547] opened 2023-01-15 07:33 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Windows

### Describe the Bug

wrangler generate geergit-backend worker-openapi

 ⛅️ wrangler 2.6.2 (update available 2.7.1)
-----------------------------------------------------
Creating a worker in geergit-backend from worker-openapi

✘ [ERROR] Failed to find "worker-openapi" in https://github.com/cloudflare/templates.git

unable to create a worker in geergit-backend using worker-openapi tempalte

**Comment by ShivamGuptaKennect** [comment] 2023-01-15 07:51
even on wrangler 2.7.1 this bug exists

**Comment by rozenmd** [comment] 2023-01-16 17:27
Hey @ShivamGuptaKennect - does `wrangler generate worker-openapi https://github.com/cloudflare/templates/worker-openapi` work for you?

**Comment by ShivamGuptaKennect** [comment] 2023-01-16 17:30
![image](https://user-images.githubusercontent.com/89238398/212736703-2bd47d4b-e7eb-47ab-81b9-75d76179cc09.png)

**Comment by rozenmd** [comment] 2023-01-16 17:39
Looks like a bug in how `wrangler generate` works on Windows @ShivamGuptaKennect - would recommend the "Deploy with Workers" button on https://github.com/cloudflare/templates/tree/main/worker-openapi

**Comment by JacobMGEvans** [comment] 2023-01-17 21:49
> Looks like a bug in how `wrangler generate` works on Windows @ShivamGuptaKennect - would recommend the "Deploy with Workers" button on https://github.com/cloudflare/templates/tree/main/worker-openapi

@rozenmd This PR #2498 going in could potentially give us the ability to test this as well.

**Comment by penalosa** [comment] 2023-01-18 11:25
@ShivamGuptaKennect Would you be able to try `WRANGLER_LOG=debug wrangler generate geergit-backend worker-openapi` and post the output?

**Comment by ShivamGuptaKennect** [comment] 2023-01-18 11:31
> WRANGLER_LOG=debug wrangler generate geergit-backend worker-openapi

![image](https://user-images.githubusercontent.com/89238398/213160451-ad12fc35-567e-4a11-81ca-9817a304e8be.png)

![image](https://user-images.githubusercontent.com/89238398/213160603-3f25cb1b-ac35-4703-af07-af05eb31fe23.png)

**Comment by penalosa** [comment] 2023-01-18 12:26
Ah, of course, that won't work on Windows. Could you try (with `cmd`, not powershell):

```sh
D:\projects> set WRANGLER_LOG=debug
D:\projects> npx wrangler generate geergit-backend worker-openapi
```

**Comment by ShivamGuptaKennect** [comment] 2023-01-18 13:19
> Ah, of course, that won't work on Windows. Could you try (with `cmd`, not powershell):
> 
> ```shell
> D:\projects> set WRANGLER_LOG=debug
> D:\projects> npx wrangler generate geergit-backend worker-openapi
> ```

![image](https://user-images.githubusercontent.com/89238398/213181915-5bb737b3-9ba7-4940-8f0e-06b3f2465daa.png)

**Comment by penalosa** [comment] 2023-01-18 13:46
Thanks! Nothing looks immediately off to me. Sorry for the back and forth, and all the requests, but as one final thing, would you be able to try:
```sh
D:\projects> git -v
D:\projects> git clone https://github.com/cloudflare/templates
D:\projects> dir templates
```

**Comment by penalosa** [comment] 2023-01-18 16:32
Passing this off to @petebacondarwin or @JacobMGEvans, who can test it on Windows hardware

**Comment by ShivamGuptaKennect** [comment] 2023-01-19 06:58
![image](https://user-images.githubusercontent.com/89238398/213376062-224d8dc1-1744-4527-91d6-ee99f979bb5a.png)


> Thanks! Nothing looks immediately off to me. Sorry for the back and forth, and all the requests, but as one final thing, would you be able to try:
> 
> ```shell
> D:\projects> git -v
> D:\projects> git clone https://github.com/cloudflare/templates
> D:\projects> dir templates
> ```

**Comment by petebacondarwin** [comment] 2023-01-19 10:02
Agh! I'm in the office today and my Windows box is at home. I will try tomorrow.
But in the meantime, I see that this error is only triggered by attempting to move the folder from the git clone:

```ts
	try {
		fs.renameSync(templatePath, targetDirectory);
	} catch {
		throw new Error(`Failed to find "${subdirectory}" in ${remote}`);
	}
```

I wonder if the directory is somehow readonly or not movable for the given user?

**Comment by penalosa** [comment] 2023-03-03 18:05
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2850, which captures the root cause (renaming across drives in Windows)

**Closed by penalosa** 2023-03-03 18:05 UTC
Labels: bug
