### ISSUE TITLE
🐛 BUG: Dashboard showing "This namespace no longer exists and  can not be read from or written to. Please try using a different namespace." for bound Durable Objects on wrangler.toml managed Pages projects

### ISSUE THREAD

**Issue by zwily** [cloudflare/workers-sdk#6099] opened 2024-06-20 01:52 UTC
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.60.2 [Wrangler]

### What version of Node are you using?

18.17.1

### What operating system and version are you using?

Mac OS Sonoma 14.5

### Observed behavior
I have a wrangler.toml managed Pages project with a bound Durable Object. In the dashboard, the binding is showing as "This namespace no longer exists and can not be read from or written to. Please try using a different namespace." The binding appears to be working fine. For my non-wrangler.toml-managed Pages projects, the bindings show up as expected.

This feels like a dashboard UI issue to me, but Walshy told me in Discord to file a wrangler bug on it since it's only happening on wrangler.toml managed Pages projects.

### Expected behavior
The dashboard should show the bound Durable Object without an error.

### Steps to reproduce
Create a Pages application, with a wrangler.toml
Bound a Durable Object to the app
Publish the app with `wrangler pages deploy`
Go to the dashboard and see that your Durable Object is showing as "no longer exists".

**Comment by davidhollenbeckx** [comment] 2024-07-07 20:04
Have also run into this issue - strangely, was able to deploy without issues for a few days. Randomly today when I deployed with wrangler pages, all of a sudden my DO namespace is invalid

**Comment by zwily** [comment] 2024-07-07 20:13
I submitted a support request as well. 16 days with no response yet.

**Comment by cbtexan04** [comment] 2024-07-08 13:00
@zwily thanks for letting us know! The dev team has already identified the root cause, and we're hoping to get this out soon. The "namespace no longer exists" message is just a cosmetic issue in the dashboard, the DO namespace is still properly connected in your functions/workers.

**Comment by CarmenPopoviciu** [comment] 2024-07-16 21:18
@cbtexan04 is this something we need to action on the wrangler side of things? or is it completely unrelated? If the latter, I'd like to go ahead and close this?

**Comment by davidhollenbeckx** [comment] 2024-07-16 21:22
hey, at least in my case, it was more than a UI dashboard bug. when I pushed the site with wrangler, the pages deployment's binding to the durable object started returning undefined and we had a bunch of run time errors as a result

this didnt happen on a live project btw - was trying out pages/toml for a new project, but based on this experience we are going to stick with dashboard managed until toml support for pages is out of beta haha

**Comment by CarmenPopoviciu** [comment] 2024-07-16 21:47
@davidhollenbeckx  kk. thank you for confirming that. I'll follow up with William's team to check what the root cause is...doesn't seem to be wrangler itself...and circle back here

**Comment by cbtexan04** [comment] 2024-07-24 19:07
> hey, at least in my case, it was more than a UI dashboard bug. when I pushed the site with wrangler, the pages deployment's binding to the durable object started returning undefined and we had a bunch of run time errors as a result
> 
> this didnt happen on a live project btw - was trying out pages/toml for a new project, but based on this experience we are going to stick with dashboard managed until toml support for pages is out of beta haha

@davidhollenbeckx, we tried to replicate your issue, but the DO bindings are working as expected on our end. Can you provide us some additional information (such as your wrangler configuration, and maybe the zone you're working with)?

In terms of this issue (dashboard showing the namespace no longer exists), I think we're all set. Not sure if we want to close this issue (as it's logged against wrangler and it doesn't seem like a wrangler issue), or continue this thread for communication.

**Comment by zwily** [comment] 2024-07-24 21:54
@cbtexan04 I'm fine closing the issue since this doesn't appear to be a wrangler issue. 

But FYI, it still appears broken on the dashboard. (I wasn't sure if "we're all set" meant "it's fixed on the dashboard" or "the fix is coming" or what, so I'm mentioning that.)

**Comment by cbtexan04** [comment] 2024-07-24 22:47
> @cbtexan04 I'm fine closing the issue since this doesn't appear to be a wrangler issue.
> 
> But FYI, it still appears broken on the dashboard. (I wasn't sure if "we're all set" meant "it's fixed on the dashboard" or "the fix is coming" or what, so I'm mentioning that.)

Ah sorry, I moreso meant let's consider closing if the initial issue (the namespace no longer exists message) is resolved! I did fail to mention-- for any _already deployed_ pages apps, you'll need to re-deploy in order to be fixed going forward. Old deployments will still show the error message. Have you happened to re-deploy in the last few weeks?

**Comment by andyjessop** [comment] 2024-08-07 13:53
For all intents and purposes, this looks closable. Thanks everyone for your comments.

**Closed by andyjessop** 2024-08-07 13:53 UTC
Labels: bug
