### ISSUE TITLE
🚀 Feature Request: Esbuild External

### ISSUE THREAD

**Issue by emersonlaurentino** [cloudflare/workers-sdk#6231] opened 2024-07-09 04:33 UTC
### Describe the solution

Add support to configure external libs to esbuild config.

Explanation:

Currently, I'm using the `@node-rs/argon2` dependency, and I'm receiving this error when run the command `wrangler dev`:

```cmd
Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error.
```

The solution is adding this lib to external on esbuild config, but we can't because we don't have access to esbuild config.

**Comment by threepointone** [comment] 2024-07-09 11:52
I'm not sure marking it as external would solve your problem, since during runtime it would still try to import it and fail. I'd be curious why the module doesn't exist for you, do you need to manually install it?

As a workaround we support module aliasing now (via https://github.com/cloudflare/workers-sdk/pull/6167, pending documentation), so you can add this to `wrangler.toml`
```toml
[alias]
"@node-rs/argon2-wasm32-wasi" = "./some-file.js"
```

so that it resolves to something you export in `some-file.js`. I'm not sure it fixes your problem, but may give you a path forward.

**Comment by petebacondarwin** [comment] 2024-07-16 05:39
I guess the problem is that since it is a WASI library it will be pulling in a WASM binary file, which cannot be bundled directly.
I wonder if adding a "rule" in wrangler.toml to tell that this file is a WASM would help:

**wrangler.toml**
```toml
[[rules]]
globs = ["@node-rs/argon2-wasm32-wasi"]
type = "CompiledWasm"
```

**Closed** 2024-08-05 13:48 UTC
Labels: enhancement, awaiting reporter response
