### ISSUE TITLE
🐛 BUG: wrangler login is not working

### ISSUE THREAD

**Issue by swleungX** [cloudflare/workers-sdk#6196] opened 2024-07-04 02:46 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

wrangler 3.63.0

### What version of Node are you using?

Node.js v22.0.0

### What operating system and version are you using?

Windows 10

### Observed behavior
- I am using wrangler behind proxy
- I have created a ".env" file with HTTPS_PROXY setting

Run npx wrangler login
- it prompts browser page and let me click "Allow"
- Redirect to localhost:8976 and failed to connect

D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:29765
            throw a;
            ^

TypeError: fetch failed
    at fetch (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:17227:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAuthToken (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:155281:10)
    at async exchangeAuthCodeForAccessToken (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:154934:20)
    at async Server.<anonymous> (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:155097:30) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6049:29)
      at D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6005:51
      at Immediate._onImmediate (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6035:37)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Node.js v22.0.0

Tried npx wrangler dev, localhost:8787 can be accessed with "Hello World!"

 ⛅️ wrangler 3.63.0
-------------------

⎔ Starting local server...
[wrangler:wrn] Unable to fetch the `Request.cf` object! Falling back to a default placeholder...
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6049:29)
    at D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6005:51
    at Immediate._onImmediate (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6035:37)
    at process.processImmediate (node:internal/timers:478:21)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[wrangler-UserWorker:wrn] Unable to fetch the `Request.cf` object! Falling back to a default placeholder...
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6049:29)
    at D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6005:51
    at Immediate._onImmediate (D:\Testfield\cloudflareTest\my-first-app\node_modules\wrangler\wrangler-dist\cli.js:6035:37)
    at process.processImmediate (node:internal/timers:478:21)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[wrangler:inf] Ready on http://127.0.0.1:8787
[wrangler:inf] GET / 200 OK (8ms)
[wrangler:inf] GET /favicon.ico 200 OK (3ms)

### Expected behavior
Don't know, never success before.

**Comment by penalosa** [comment] 2024-07-05 12:05
I think this might be a duplicate of https://github.com/cloudflare/workers-sdk/issues/5162? Wrangler is generally unable to function if you're unable to access the Cloudflare API.

Could you provide a minimal reproduction, including the proxy variables you're using?

**Comment by swleungX** [comment] 2024-07-22 04:35
Sorry to reply late, and thank you for your handling. I have update the version of wrangler to 3.65.1 and the problem still exist.

I have created a .env inside my project folder, like this
![image](https://github.com/user-attachments/assets/3e1ab4ad-f6d2-4876-8d26-c9ff38d9ba9f)

And the content of the .env file is like this
![image](https://github.com/user-attachments/assets/a5c4b909-bf9f-46fe-b723-9cf71c9dd238)

When i run nxp wrangler login, it shows:
![image](https://github.com/user-attachments/assets/54ca9ed6-7c26-45c5-8771-a3756e54a8cb)

then browser:
![image](https://github.com/user-attachments/assets/62949eb4-6946-4098-b558-fb3c6285cd8d)

And then i click "Allow"
![image](https://github.com/user-attachments/assets/a6a2eea1-03fa-45ab-a31b-9f9cb6c1fb91)
![image](https://github.com/user-attachments/assets/c4da1595-7d68-405d-8d1c-3b8009608f88)


For your question, I am not quite sure whether I am unable to access the Cloudflare API or not. Could you please let me know how to check?

Thank you very much!

**Comment by penalosa** [comment] 2024-07-22 17:23
This might be a red herring, but it looks like you have an `http://` URL in your `HTTPS_PROXY` setting? Does your company run an `https://` proxy?

**Comment by swleungX** [comment] 2024-07-23 01:13
No, my company only runs one proxy, I have asked the same question to the network team, they answer me the proxy support https.

**Comment by swleungX** [comment] 2024-07-24 08:19
> In that case could you try setting the `HTTPS_PROXY` variable to `https://proxy2.mycompany.proxy:8080`?

Tried. The same result.

**Comment by RamIdeas** [comment] 2024-08-05 12:53
> For your question, I am not quite sure whether I am unable to access the Cloudflare API or not. Could you please let me know how to check?

Could you try running another wrangler command which hits the Cloudflare API, like `wrangler deployments list`, with the `HTTPS_PROXY` env var set? This would narrow down whether your proxy is working for Cloudflare API calls. You may need to login without using your proxy first

**Comment by lrapoport-cf** [comment] 2024-08-19 13:12
hi @swleungX , are you able to try @RamIdeas 's suggestion above?

**Comment by swleungX** [comment] 2024-08-20 09:10
Sorry for late reply.
Finally, I found our IT administrator to setup the environment variables in Windows, and the npx wrangler login can be run. It seems that the .env setting is not working. Anyway, thanks for you all for handling it.

**Closed** 2024-08-21 12:09 UTC
Labels: awaiting reporter response, needs reproduction, bug
