### ISSUE TITLE
🐛 BUG: Local KV silently limits values to 4KB

### ISSUE THREAD

**Issue by mhamann** [cloudflare/workers-sdk#4037] opened 2023-09-26 20:46 UTC
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler core

### What version(s) of the tool(s) are you using?

3.10.0 [Wrangler]

### What version of Node are you using?

18.17.0

### What operating system are you using?

Mac

### Describe the Bug

When inserting values into the KV store (running `wrangler dev` locally), values are silently truncated at 4096 characters (roughly 4KB). Examining the blob on disk reveals the truncated value.

Steps:
1. Start the worker: `wrangler dev --env dev` with a KV binding
2. Attempt to write a text blob > 4K to the KV binding
3. Insert succeeds
4. Read inserted value and find it's truncated to 4096 characters

Given that the production limit for KV values is 25MB, I would expect the local version to work similarly.

### Please provide any relevant error logs

No errors are thrown.

**Comment by penalosa** [comment] 2023-09-29 14:40
I'm unable to reproduce this locally. Local KV has a size limit of `26214400` bytes, which should match the behaviour of KV for a deployed Worker. Could you include a reproduction to demonstrate the behaviour you're seeing?

**Comment by lrapoport-cf** [comment] 2023-10-23 15:27
hi @mhamann   :) we haven’t heard back so we will close the issue for now. however, if this is still an issue and you are able to provide a repro, please feel free to re-open it. thanks!

**Closed by lrapoport-cf** 2023-10-23 15:27 UTC
Labels: needs reproduction, bug

**Comment by awthwathje** [comment] 2024-05-23 14:07
To whomever stumbles upon this bug: this happens when you do `kv.put(eventId, JSON.stringify(data))` and not `await kv.put(eventId, JSON.stringify(data))`.

In the past it was not necessary to `await` when saving data, but they changed it at some point and now if you don't `await` it is only saving the first 4 or 8 KB.

**Comment by subhendupsingh** [comment] 2024-08-30 15:36
Banging my head over this for hours now
