### ISSUE TITLE
🐛 BUG: wrangler D1 export doesn't work

### ISSUE THREAD

**Issue by GeorgeTailor** [cloudflare/workers-sdk#6135] opened 2024-06-24 11:14 UTC
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler core

### What version(s) of the tool(s) are you using?

3.61.0

### What version of Node are you using?

20.10

### What operating system and version are you using?

Windows 11

### Observed behavior
go to https://developers.cloudflare.com/d1/build-with-d1/import-export-data/#export-an-existing-d1-database

copy paste `npx wrangler d1 export <database_name> --remote --output=./database.sql`
change <database_name> to actual database name
run

I am forced to allow access via browser, but it ends up in error:
```
Unable to connect

Firefox can’t establish a connection to the server at localhost:8976.
```

and in command line:
```
node_modules\wrangler\wrangler-dist\cli.js:29747
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

### Expected behavior
It should just work

### Steps to reproduce
all steps are described in `Observed behaviour`

**Comment by GeorgeTailor** [comment] 2024-06-24 13:37
generating export via API also doesn't work properly, the response file is riddled with:
```
INSERT INTO comment VALUES('edae5276-cff9-4d9d-ae1f-b9432a296ea8','5e76df81-3955-45e5-955e-4b70b0eb1e6a','Ð¢Ð°Ðº Ñ†Ðµ ÑÐ»Ð¾Ð²Ð¾ Ñ– Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð¾Ð²ÑƒÑ”Ñ‚ÑŒÑÑ ÑÐº ÑÐ»ÑŽÑ€ Ð² Ð¡Ð¨Ð (Ð·Ð° Ð„Ð²Ñ€Ð¾Ð¿Ñƒ Ð½Ðµ Ð·Ð½Ð°ÑŽ). Ð¢Ð°Ð¼ ÑÐ¸Ñ‚ÑƒÐ°Ñ†Ñ–Ñ Ð· Ð½Ð¸Ð¼ Ñ‚Ð°ÐºÐ° Ð¶, ÑÐº Ñ‚ÑƒÑ‚. Ð’Ð¾Ð½Ð¾ Ð½Ð°Ð±ÑƒÐ»Ð¾ ÑÐ»ÑŽÑ€Ð½Ð¾Ð³Ð¾ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð½Ñ, Ñ‚Ð° Ð´ÐµÑÐºÑ– Ñ‚Ñ€Ð°Ð½ÑÐ²Ð¸ÐºÐ»ÑŽÑ‡Ð½Ñ– Ñ„ÐµÐ¼Ñ–Ð½Ñ–ÑÑ‚ÐºÐ¸ (ÑÐºÑ‰Ð¾ Ð½Ðµ Ð±Ñ–Ð»ÑŒÑˆÑ–ÑÑ‚ÑŒ) Ð½Ðµ Ñ…Ð¾Ñ‡ÑƒÑ‚ÑŒ, Ð°Ð±Ð¸ Ñ—Ñ… Ñ‚Ð°Ðº Ð½Ð°Ð·Ð¸Ð²Ð°Ð»Ð¸, Ð½Ð°Ñ‚Ð¾Ð¼Ñ–ÑÑ‚ÑŒ Ð²Ð¸Ð³Ð°Ð´ÑƒÑŽÑ‡Ð¸ Ñ–Ð½Ð°ÐºÑˆÑ– Ñ‚ÐµÑ€Ð¼Ñ–Ð½Ð¸. Ð¢Ð¾Ð¼Ñƒ Ð²Ð¾Ð½Ð¾ Ð½Ðµ Ð±ÐµÐ·Ð¿Ñ–Ð´ÑÑ‚Ð°Ð²Ð½Ð¾ ÑÐ»ÑŽÑ€Ð½Ðµ','115',1693771129);
```

**Comment by GeorgeTailor** [comment] 2024-06-26 12:23
seems that this problem is related to broken wrangler integration, wrangler cannot aquire authorization for any functions. I have also tried `wrangler pages deployment tail` and encoutered the same problem.

any help?

**Comment by GeorgeTailor** [comment] 2024-06-26 12:29
to make things even more funny, this is the response that wrangler gets:
```
<div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> dash.cloudflare.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->
```

**Comment by alexcroox** [comment] 2024-06-26 17:17
I think wrangler CLI is broken in general. I'm getting the same error with `wrangler pages deployment tail`. During the oauth dance the callback is hitting the same error in terminal:

```
/Users/alex/Projects/saas/node_modules/wrangler/wrangler-dist/cli.js:29747
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/Users/alex/Projects/saas/node_modules/wrangler/wrangler-dist/cli.js:5287:19)
    ```

**Comment by michael1979er** [comment] 2024-06-27 10:59
i had the same problem, when i first run "wrangler login" in the console, everything seems to be fine.

**Comment by langyo** [comment] 2024-07-02 15:58
same issue

**Comment by penalosa** [comment] 2024-08-19 13:44
Hi all! We've recently added some more logging to `wrangler login` (which is where we usually see this issue come up) to help us diagnose. It usually comes down to using a proxy or VPN, which triggers some sort of API limit.

I'm going to close this issue because there's not a whole lot we can do without more reproducible steps. If anyone runs into it in future, to help us reproduce and fix could you run `npx wrangler@latest login`, and open a new issue with the error message, including the Ray ID?

**Closed by penalosa** 2024-08-19 13:44 UTC
Labels: bug
