### ISSUE TITLE
🐛 BUG: "open Devtools" doesn't fallback to other browsers

### ISSUE THREAD

**Issue by x-yuri** [cloudflare/workers-sdk#2889] opened 2023-03-10 05:43 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.2

### What operating system are you using?

Linux

### Describe the Bug

```
$ npx wrangler init my-project
$ cd my-project
$ npx wrangler dev
```

Then press <kbd>d</kbd>.

I don't have `google-chrome` but I have `chromium`.

Since you [don't pass][a] `wait: true`, `open` [doesn't try][b] other browsers.

Also, what's the point? I made it work w/ `chromium` w/o `wait: true`, it opened a console, probably to the preview server. I make an http request, but it ignores my breakpoints.

An [issue][c] in the `open`'s repository.

[a]: https://github.com/cloudflare/workers-sdk/blob/wrangler%402.12.2/packages/wrangler/src/inspect.ts#L763-L778
[b]: https://github.com/sindresorhus/open/blob/v8.4.2/index.js#L224-L243
[c]: https://github.com/sindresorhus/open/issues/301

**Comment by penalosa** [comment] 2023-07-11 20:10
Closing as a duplicate of #1445

**Closed by penalosa** 2023-07-11 20:10 UTC
Labels: bug
