### ISSUE TITLE
🐛 BUG: Getting`SyntaxError: The requested module 'pretty-format' does not provide an export named 'format'`

### ISSUE THREAD

**Issue by harryzcy** [cloudflare/workers-sdk#5303] opened 2024-03-19 21:12 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

wrangler 3.34.2, `@cloudflare/vitest-pool-workers` 0.1.3

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Ubuntu

### Describe the Bug

I'm getting `Error initialising worker: SyntaxError: The requested module 'pretty-format' does not provide an export named 'format'` when I try to migrate tests to `@cloudflare/vitest-pool-workers`. There's no other error traces given.

I only see `pretty-format` as a dependency for vitest. Is there anyway to know where the error is coming from?

**Comment by harryzcy** [comment] 2024-04-07 00:54
I haven't find out why, but installing `pretty-format` separately seems clear the errors.

**Comment by penalosa** [comment] 2024-04-07 12:37
@harryzcy would you be able to link a reproduction? I suspect this is a bug that's fairly specific to your project setup, and so a reproduction would be really helpful in narrowing in down!

**Comment by petebacondarwin** [comment] 2024-04-15 14:47
Closing as we can't reproduce this locally.

**Closed by petebacondarwin** 2024-04-15 14:47 UTC
Labels: needs reproduction, bug

**Comment by ecchochan** [comment] 2024-05-15 14:34
Just encountered this bug and successfully reproduced the same error by also having `jest` installed, which in `28.1.3` for example has `pretty-format "^28.1.3"` dependency (because they are in the same monorepo, thus the same version)

I will put the repo [here](https://github.com/ecchochan/test-cf-worker-vitest/commit/c1ce608ad3905366ffc73891dbd4b917fa6222bc) for reproducing the issue

Note that if I install a newer version of `jest`, e.g. `29.7.0`, the import error does not happen

**Comment by colelawrence** [comment] 2024-07-18 19:21
I'm experiencing this same issue, but maybe it is related to the way `bun` installs packages for workspaces, because I think the error I encounter is from `@auth/core` -> `preact-render-to-string@5.2.5` -> `pretty-format@^3.8.0` being included in my workspace root's node_modules, folder.
