### ISSUE TITLE
🐛 BUG: Failed to find "undefined" in https://github.com/cloudflare/worker-template-router.git

### ISSUE THREAD

**Issue by jpedrocr** [cloudflare/workers-sdk#2585] opened 2023-01-23 08:46 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

node.js VSCode Dev Env

### Describe the Bug

When I run `wrangler generate my-app https://github.com/cloudflare/worker-template-router`, I get the following message:
``` 
⛅️ wrangler 2.8.0 
-------------------
Creating a worker in my-app from https://github.com/cloudflare/worker-template-router

✘ [ERROR] Failed to find "undefined" in https://github.com/cloudflare/worker-template-router.git.
```

Can you help?

**Comment by eslachance** [comment] 2023-02-12 03:35
> Hey! 👋 I'm unable to reproduce this. Which operating system are you using? What is the output of `--version`?

Hi! I came here specifically for this issue, since I have exactly the same one. I had wrangler 2.7.1 and now I tried to update to 2.9.1 and get the same error. Windows 10, tried in Powershell, Command Prompt, and the new Terminal (which is still powershell I guess). No dice, I got exactly the same error as above: 

```
F:\cloudflare\workers>wrangler generate my-ts-project https://github.com/cloudflare/worker-typescript-template
 ⛅️ wrangler 2.9.1
-------------------
Creating a worker in my-ts-project from https://github.com/cloudflare/worker-typescript-template

X [ERROR] Failed to find "undefined" in https://github.com/cloudflare/worker-typescript-template.git

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by eslachance** [comment] 2023-02-12 03:39
Interesting point however, I tried to visit https://github.com/cloudflare/worker-typescript-template , curious as to what might be undefined here, and it now says: 

> ⚠️ Warning: This template is no longer maintained

For something that's directly linked and used from the workers dev, that's worrying - perhaps someone might update https://developers.cloudflare.com/workers/get-started/quickstarts/ to reflect whatever current methodology should be used? Apparently using "wrangler init" but the page linked from that github doesn't talk about init, just about installing. 

From the perspective of a user trying to get into workers, this is a pretty difficult experience to navigate!

**Comment by penalosa** [comment] 2023-03-03 18:07
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2850, which captures the likely root cause here (renaming across drives). 

In the meantime, the best way to get started with Workers is to run `npx wrangler init my-app`, and Wrangler will walk you through some interactive prompts.

**Closed by penalosa** 2023-03-03 18:07 UTC
Labels: needs reproduction, bug
