### ISSUE TITLE
🐛 BUG: Tailing - workers.api.error.script_not_found [code: 8000068]

### ISSUE THREAD

**Issue by magick93** [cloudflare/workers-sdk#6289] opened 2024-07-18 22:12 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

Wrangler 3.65.0

### What operating system and version are you using?

Ubuntu 24:04

### Observed behavior
When trying to tail a Cloudflare pages Next.js application I'm getting:

```
A request to the Cloudflare API (/accounts/61871ed1209ff345d53e18f6b0ce8552/pages/projects/typebot-io-viewer/deployments/d30ef19b-c048-4b61-93a5-3c0476d06d12/tails) failed.

  workers.api.error.script_not_found [code: 8000068]

```

### Expected behavior

Should be able to tail logs

### Steps to reproduce
Please provide the following:

To reproduce
- use https://github.com/yestechgroup/typebot.io
- Build command: ` npx turbo build --filter=viewer...`
- Output dir:  `    //apps/viewer/.next/standalone/apps/viewer/.next/`
- Root dir:  `/`
- Environment variables - using these exact values should produce errors when running, but if you get errors from the incorrect values, then that is probably a good thing.

```
ENCRYPTION_SECRET=fx+RanDom/abcbDEX/rskFmtgGSSZ8Ta

# DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot

DATABASE_URL=postgres://postgres:postgres@nevermind:5432/postgres?schema=typebot

NEXTAUTH_URL=http://typebot.domain.com:8080
NEXT_PUBLIC_VIEWER_URL=http://typebot.domain.com:8081

GITHUB_CLIENT_ID=xxxxxxxxxxxxxxxxxx
GITHUB_CLIENT_SECRET=xxxxx

ADMIN_EMAIL=your@email.com
```

### Please provide a link to a minimal reproduction

https://github.com/yestechgroup/typebot.io

### Please provide any relevant error logs

  workers.api.error.script_not_found [code: 8000068]

**Comment by irvinebroque** [comment] 2024-07-18 22:23
seems similar to https://github.com/cloudflare/workers-sdk/issues/3347

**Comment by ikobe** [comment] 2024-07-26 15:58
same here

**Comment by petebacondarwin** [comment] 2024-07-27 06:35
I believe this may be caused by trying to tail a project that has no fetch handler?
There is an internal ticket to improve the messaging in this case.

**Comment by lrapoport-cf** [comment] 2024-10-25 02:28
hi @magick93 :) we're closing this as it seems the issue is messaging and there is an internal ticket to address this. if you are still experiencing issues, please feel free to open a new issue referencing this one and we will review. thanks!

**Closed by lrapoport-cf** 2024-10-25 02:28 UTC
Labels: bug, internal
