### ISSUE TITLE
🐛 BUG: Deleting a nonexistent KV namespace ID returns an oauth error

### ISSUE THREAD

**Issue by K3das** [cloudflare/workers-sdk#2288] opened 2022-11-24 20:14 UTC
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Fedora 37

### Describe the Bug

I haven't tested this with a existing namespace ID, but for invalid namespace IDs it should likely return a more helpful error.
```
$ wrangler kv:namespace delete --namespace-id [namespace_id]
 ⛅️ wrangler 2.4.4 
-------------------
Deleting KV namespace [namespace_id].

✘ [ERROR] A request to the Cloudflare API (/accounts/[account_id]/storage/kv/namespaces/[namespace_id]) failed.

  DELETE method not allowed for the oauth_token authentication scheme [code: 10000]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by rozenmd** [comment] 2022-11-28 13:43
Thanks for reporting this @K3das - we'll improve the error message here

**Comment by 1000hz** [comment] 2023-11-21 15:57
The root cause of this issue is a route mismatch at our API Gateway layer due to pattern constraints on the endpoint's route definition. I think this would be better fixed at that layer rather than us working around it in wrangler. I'll close this issue and open an internal one to address the root cause.

**Closed by 1000hz** 2023-11-21 15:57 UTC
Labels: enhancement, quick win

**Comment by 1000hz** [comment] 2023-11-21 16:14
For future reference, this is being tracked internally as **KV-694**
