### ISSUE TITLE
🐛 BUG: Uncaught exception when binding `pages dev` to port 80 or 443

### ISSUE THREAD

**Issue by xtian** [cloudflare/workers-sdk#3676] opened 2023-07-25 21:26 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.3.0

### What version of Node are you using?

20.5.0

### What operating system are you using?

Mac

### Describe the Bug

Reproduction steps:

0. Setup: `git clone https://github.com/xtian/wrangler-repo; cd wrangler-repo; npm install`
1. Build project: `./node_modules/.bin/vite build`
2. Start wrangler: `./node_modules/.bin/wrangler pages dev .svelte-kit/cloudflare --port=80`
    - Site will be reachable at `http://127.0.0.1`
3. In a separate terminal session run `./node_modules/.bin/vite build` again
    - Wrangler will log uncaught exception and site will no longer be reachable

### Please provide a link to a minimal reproduction

https://github.com/xtian/wrangler-repo

### Please provide any relevant error logs

```
⎔ Reloading local server...
▲ [WARNING] Parsed 2 valid header rules.


workerd/util/symbolizer.c++:99: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:1298: failed: DNS lookup failed.; params.host = 127.0.0.1; params.service = NaN; gai_strerror(status) = nodename nor servname provided, or not known
stack: 10403d37c 1027c0f38 1027c1b58 10278c91f 10279032b 10279015f 102790147 104076013 10407626f 1040749c7 104074797 1027841ab 18098bf27
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above
```

**Comment by longrunningprocess** [comment] 2023-12-08 21:51
It would be nice to hear whether this is going to be fixed or not, it affects my cors setup by requiring me to check for an optional port before setting the `Access-Control-Allow-Origin` header...

**Comment by longrunningprocess** [comment] 2023-12-08 22:21
after some discussion on the discord channel, it was a permissions issue... low ports (< 1024) require root access... so for me, I re-ran my command with a `sudo` and it was fine.

**Comment by lrapoport-cf** [comment] 2024-01-23 02:47
@longrunningprocess apologies for the delay on this! however, sounds like the issue is resolved, so will close this out 👍

**Closed by lrapoport-cf** 2024-01-23 02:47 UTC
Labels: pages, bug
