### ISSUE TITLE
🚀 Feature Request: add `wrangler deploy` support for explicit resource management

### ISSUE THREAD

**Issue by Hebilicious** [cloudflare/workers-sdk#5299] opened 2024-03-19 17:43 UTC
### Describe the solution

EDIT : This could be considered a duplicate of https://github.com/cloudflare/workers-sdk/issues/5222

When using the new `using` keyword, `wrangler deploy` chokes as support for this got introduced in a more recent version of esbuild (https://github.com/evanw/esbuild/releases/tag/v0.18.7)

Upgrading to a more recent version of esbuild would fix the issue (this is what we're doing with a pnpm patch).

The esbuild version needed for supporting this feature would be at least [0.18.9](https://github.com/evanw/esbuild/releases/tag/v0.18.9) (currently wrangler uses 0.17.19), although it would be nice to move to the latest version (0.20 +).

Additional question : Is there workerd runtime support planned for this yet ? It's a [stage 3 proposal](https://github.com/evanw/esbuild/releases/tag/v0.18.9), so probably not yet.

**Comment by penalosa** [comment] 2024-11-08 22:05
Thanks for raising this! I'm closing it as a duplicate of https://github.com/cloudflare/workers-sdk/issues/5222, but it's definitely something we'll be investigating soon

**Closed by penalosa** 2024-11-08 22:05 UTC
Labels: enhancement
