### ISSUE TITLE
polish: On 10000/ auth errors, we should log details about the token

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1197] opened 2022-06-07 07:21 UTC
A significant number of bug reports/issues are about auth and tokens and stuff. While there are bugs that we should fix, some of it is just configuration. So when wrangler fails with a 10000 error, we should log details related to the token so it's easier to debug/report. (api for getting permission groups: https://api.cloudflare.com/#permission-groups-list-permission-groups)

**Comment by petebacondarwin** [comment] 2022-06-07 09:02
This is very similar to (perhaps even a duplicate of) https://github.com/cloudflare/wrangler2/issues/761.

**Comment by JacobMGEvans** [comment] 2022-06-09 18:13
> A significant number of bug reports/issues are about auth and tokens and stuff. While there are bugs that we should fix, some of it is just configuration. So when wrangler fails with a 10000 error, we should log details related to the token so it's easier to debug/report. (api for getting permission groups: https://api.cloudflare.com/#permission-groups-list-permission-groups)

Is this referring to the instance of people having a token that doesn't have correct permissions somewhere not getting information necessary, I remember someone had mentioned showing the token and some additional information from the permissions error. I don't remember that scenario completely, but it may help to know it to differentiate the work in issue 761

**Closed** 2023-10-02 16:15 UTC
Labels: polish
