### ISSUE TITLE
🐛 BUG: 🛑🛑 KV and D1 Not Functioning Locally with  Pages🐞🛑🛑

### ISSUE THREAD

**Issue by joelket23** [cloudflare/workers-sdk#6583] opened 2024-08-27 14:32 UTC
### Which Cloudflare product(s) does this pertain to?

D1, KV

### What version(s) of the tool(s) are you using?

 wrangler@3.72.2

### What version of Node are you using?

v22.5.1 

### What operating system and version are you using?

Mac Sonoma 14.6.1 , Mac M1

### Observed behavior
Both KV and D1 databases are not working locally; they function fine with Workers but fail to work in Pages. 
As you can see from my log, KV and D1 are successfully bound, yet I'm still receiving null data. However, when I access D1 directly from the terminal using the command `npx wrangler d1 execute prod-yeniseysk --remote --command="SELECT * FROM users"`, it works correctly
```
⛅️ wrangler 3.72.2
-------------------

Attaching additional modules:
┌────────────────────────────────────────────────────────────────────────────┬──────┬────────────┐
│ Name                                                                       │ Type │ Size       │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1058.js                                      │ esm  │ 2.29 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/106.js                                       │ esm  │ 0.19 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1130.js                                      │ esm  │ 2.30 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1161.js                                      │ esm  │ 0.31 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1217.js                                      │ esm  │ 5.99 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1403.js                                      │ esm  │ 0.25 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1465.js                                      │ esm  │ 10.35 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1483.js                                      │ esm  │ 3.35 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1512.js                                      │ esm  │ 0.31 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1522.js                                      │ esm  │ 2.08 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1556.js                                      │ esm  │ 0.57 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/162.js                                       │ esm  │ 2.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1694.js                                      │ esm  │ 0.27 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1729.js                                      │ esm  │ 2.24 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1732.js                                      │ esm  │ 0.31 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/178.js                                       │ esm  │ 0.95 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1922.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1931.js                                      │ esm  │ 0.42 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/1979.js                                      │ esm  │ 15.13 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2062.js                                      │ esm  │ 0.46 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2091.js                                      │ esm  │ 1.22 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2096.js                                      │ esm  │ 0.48 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2135.js                                      │ esm  │ 0.12 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2158.js                                      │ esm  │ 0.25 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2181.js                                      │ esm  │ 0.16 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2221.js                                      │ esm  │ 0.58 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2240.js                                      │ esm  │ 2.33 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2261.js                                      │ esm  │ 0.31 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/258.js                                       │ esm  │ 1.39 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2586.js                                      │ esm  │ 0.06 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2652.js                                      │ esm  │ 0.16 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2659.js                                      │ esm  │ 0.19 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2717.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/281.js                                       │ esm  │ 0.73 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/2852.js                                      │ esm  │ 0.23 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3010.js                                      │ esm  │ 0.24 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/306.js                                       │ esm  │ 1.50 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3067.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3199.js                                      │ esm  │ 0.37 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3275.js                                      │ esm  │ 0.16 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3276.js                                      │ esm  │ 0.19 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3405.js                                      │ esm  │ 0.18 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3481.js                                      │ esm  │ 1.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3484.js                                      │ esm  │ 1.22 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3572.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3606.js                                      │ esm  │ 13.36 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3756.js                                      │ esm  │ 1.24 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3794.js                                      │ esm  │ 0.23 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3943.js                                      │ esm  │ 5.19 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3987.js                                      │ esm  │ 0.82 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/3998.js                                      │ esm  │ 0.72 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4016.js                                      │ esm  │ 0.99 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4206.js                                      │ esm  │ 1.62 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4239.js                                      │ esm  │ 0.55 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4349.js                                      │ esm  │ 0.21 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4395.js                                      │ esm  │ 0.08 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4423.js                                      │ esm  │ 0.66 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4444.js                                      │ esm  │ 0.93 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4508.js                                      │ esm  │ 0.72 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4522.js                                      │ esm  │ 0.37 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4567.js                                      │ esm  │ 0.21 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4735.js                                      │ esm  │ 3.74 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/4918.js                                      │ esm  │ 1.82 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5043.js                                      │ esm  │ 0.20 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5198.js                                      │ esm  │ 4.26 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5324.js                                      │ esm  │ 0.38 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5355.js                                      │ esm  │ 0.32 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5404.js                                      │ esm  │ 1.13 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5417.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5516.js                                      │ esm  │ 0.88 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5710.js                                      │ esm  │ 0.56 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5731.js                                      │ esm  │ 1.03 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5765.js                                      │ esm  │ 2.15 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5823.js                                      │ esm  │ 0.97 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/5995.js                                      │ esm  │ 0.63 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6043.js                                      │ esm  │ 1.01 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6179.js                                      │ esm  │ 0.45 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6204.js                                      │ esm  │ 1.13 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6282.js                                      │ esm  │ 2.04 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6305.js                                      │ esm  │ 1.20 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6460.js                                      │ esm  │ 0.37 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6555.js                                      │ esm  │ 0.39 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6592.js                                      │ esm  │ 0.80 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6678.js                                      │ esm  │ 0.52 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6699.js                                      │ esm  │ 2.65 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6801.js                                      │ esm  │ 2.92 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6881.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/6926.js                                      │ esm  │ 1.46 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7090.js                                      │ esm  │ 0.68 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7242.js                                      │ esm  │ 0.19 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7277.js                                      │ esm  │ 2.02 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7522.js                                      │ esm  │ 2.36 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7578.js                                      │ esm  │ 1.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7586.js                                      │ esm  │ 0.58 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/760.js                                       │ esm  │ 0.07 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7641.js                                      │ esm  │ 61.84 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7668.js                                      │ esm  │ 4.78 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7671.js                                      │ esm  │ 0.35 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7695.js                                      │ esm  │ 8.23 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7714.js                                      │ esm  │ 3.59 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7748.js                                      │ esm  │ 0.42 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/781.js                                       │ esm  │ 0.29 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7881.js                                      │ esm  │ 0.98 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/7996.js                                      │ esm  │ 0.54 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8020.js                                      │ esm  │ 1.45 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8097.js                                      │ esm  │ 4.83 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/81.js                                        │ esm  │ 0.28 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8117.js                                      │ esm  │ 0.38 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8207.js                                      │ esm  │ 0.48 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8269.js                                      │ esm  │ 0.44 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8326.js                                      │ esm  │ 0.75 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8543.js                                      │ esm  │ 0.48 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8565.js                                      │ esm  │ 1.76 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8568.js                                      │ esm  │ 1.63 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/866.js                                       │ esm  │ 0.38 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8674.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/870.js                                       │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8744.js                                      │ esm  │ 5.06 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8745.js                                      │ esm  │ 0.10 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/890.js                                       │ esm  │ 2.42 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/8914.js                                      │ esm  │ 0.40 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9003.js                                      │ esm  │ 3.12 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9083.js                                      │ esm  │ 0.23 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9153.js                                      │ esm  │ 1.46 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9239.js                                      │ esm  │ 0.76 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/925.js                                       │ esm  │ 0.73 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9437.js                                      │ esm  │ 2.21 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9505.js                                      │ esm  │ 0.96 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9521.js                                      │ esm  │ 1.11 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9525.js                                      │ esm  │ 0.35 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/957.js                                       │ esm  │ 1.34 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9586.js                                      │ esm  │ 0.23 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9591.js                                      │ esm  │ 7.04 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9594.js                                      │ esm  │ 3.31 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9647.js                                      │ esm  │ 0.25 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9688.js                                      │ esm  │ 0.17 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9774.js                                      │ esm  │ 1.77 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9824.js                                      │ esm  │ 0.62 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9851.js                                      │ esm  │ 0.36 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9881.js                                      │ esm  │ 0.21 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9901.js                                      │ esm  │ 0.12 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9908.js                                      │ esm  │ 6.57 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/chunks/9977.js                                      │ esm  │ 3.18 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/auth.func.js                          │ esm  │ 13.34 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/charge.func.js                        │ esm  │ 13.20 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/checkPlan.func.js                     │ esm  │ 13.21 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/direct.func.js                        │ esm  │ 13.20 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/get.func.js                           │ esm  │ 13.33 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/getThemeId.func.js                    │ esm  │ 13.35 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/reauth.func.js                        │ esm  │ 13.20 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/test.func.js                          │ esm  │ 5.35 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/token.func.js                         │ esm  │ 13.55 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/update_version.func.js                │ esm  │ 13.36 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/webhook/app_uninstalled.func.js       │ esm  │ 13.60 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/webhook/customer_data_request.func.js │ esm  │ 6.78 KiB   │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/webhook/shop_updated.func.js          │ esm  │ 13.59 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ __next-on-pages-dist__/functions/api/webhook.func.js                       │ esm  │ 13.27 KiB  │
├────────────────────────────────────────────────────────────────────────────┼──────┼────────────┤
│ Total (157 modules)                                                        │      │ 442.01 KiB │
└────────────────────────────────────────────────────────────────────────────┴──────┴────────────┘
✨ Compiled Worker successfully
Your worker has access to the following bindings:
- KV Namespaces:
  - WORDS: 5efab49ed93e42d496830733edd8da60
- D1 Databases:
  - DB: prod-yeniseysk (0fa3e8a0-2e0f-4138-9c29-d3cdd11a3cbd), Preview: (0fa3e8a0-2e0f-4138-9c29-d3cdd11a3cbd)

⎔ Starting local server...
✨ Parsed 1 valid header rule.
[wrangler:inf] Ready on http://127.0.0.1:8181
```

### Expected behavior
Both KV and D1 databases must work fine locally, as they do with Workers

### Steps to reproduce
Please provide the following:
- Create simple next js project
- Create a `wrangler.toml` file and add the following code:
```
name = "dev-imgz-next"
pages_build_output_dir = "./.vercel/output/static"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "WORDS"
id = "<YOUR_ID>"
preview_id = "<YOUR_ID>"

[[d1_databases]]
binding = "DB" 
database_name = "prod-yeniseysk"
database_id = "<YOUR_ID>"
preview_database_id = "<YOUR_ID>" 

[dev]
ip = "127.0.0.1"
port = 8181
inspector_port = 8989
local_protocol = "http"
upstream_protocol = "http"

```
- Create a API file`test.js`in  NextJS project and add the following code:
```
export const config = { runtime: 'edge' };
export default async function Authenticate(req, res) {
  const test = { shop: 'staffa' };

try {
    const { results } = await process.env.DB.prepare('SELECT * FROM users');
    console.log("resut",results)    
  } catch (error) {
    console.log("catch error",error.message)
  }
  if (test.shop !== 'staff') {
    console.log('is not staff');
  }
  let kvData = await process.env.WORDS.get("joyboy")
  console.log("kvdata",kvData)
  return new Response('test', { status: 200 });
}
```
- To run the code, use the command `npx wrangler pages dev`

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide a link to a minimal reproduction

https://github.com/joelket23/cloudflare-dev.git

### Please provide any relevant error logs

No errors

**Comment by joelket23** [comment] 2024-08-27 16:05
@irvinebroque I followed the instructions, but I'm still not receiving data from the database.

**Comment by irvinebroque** [comment] 2024-08-27 16:22
What's the error?

**Comment by joelket23** [comment] 2024-08-27 16:52
@irvinebroque  
```
resut undefined
is not staff
error in kv:  Cannot read properties of undefined (reading 'get')

```

**Comment by penalosa** [comment] 2024-08-27 21:37
@joelket23 could you update your reproduction to incorporate the steps from https://developers.cloudflare.com/pages/framework-guides/nextjs/ssr/get-started/#3-update-nextconfigmjs?

As a secondary note, I see you're running D1 commands with the `--remote` flag, which will execute against your production database. Pages uses a local simulator for D1—to query the local database make sure you're passing `--local` to your D1 commands.

**Comment by joelket23** [comment] 2024-08-28 04:43
@penalosa  I’ve updated my reproduction repo; you can check it now. I also want to clarify your secondary point about the D1 commands with the --remote flag. I only used that to confirm if my query is correct for fetching data from the database.

**Comment by RamIdeas** [comment] 2024-09-09 13:31
> local KV is not connected to Cloudflare KV like it is in Workers

It sounds like you want to use your remote data while running your project. This is requires `wrangler dev –remote` when running your a Workers project. Unfortunately, Pages projects do not support remote-mode. 

Ideally your local development would have no impact on your remote data. You can write a script to seed your local data stores with dummy data or data from remote.

I'm going to close this issue since it isn't a bug.

**Closed** 2024-09-09 13:46 UTC
Labels: bug
