### ISSUE TITLE
🚀 Feature Request: [Wrangler 2 Regression] Being able to inspect the worker code

### ISSUE THREAD

**Issue by brillout** [cloudflare/workers-sdk#1580] opened 2022-07-29 13:33 UTC
### Describe the solution

Wrangler 1 was generating the worker code locally on my machine, and added the worker code to my source tree, so I could easily inspect it.

Wrangler 2 most likely also generates the worker code locally on my machine, but I can't find where it then lives? Is it written to the filesystem somewhere? Being able to inspect the worker code is *paramount* for debugging.

I know I can inspect the worker code on `couldflare.com`'s UI but that's quite inconvenient.

(Btw. wrangler 2 is *much* better than wrangler 1, nice job 👌.)

**Comment by threepointone** [comment] 2022-07-29 16:49
You can generate a local copy of the worker we upload with `wrangler publish --dry-run --outdir <path>` 

(We should document this)

**Comment by brillout** [comment] 2022-07-29 16:51
Perfect, thanks!

**Comment by brillout** [comment] 2022-07-30 21:47
Unfortunately, the line numbers of the error stack thrown while running `$ wrangler dev` don't match the line numbers of the worker code generated by `$ wrangler publish --dry-run`.

Also, is there a way to modify the local worker and then try it? That's quite a convenient debugging DX.

**Comment by threepointone** [comment] 2022-07-30 22:02
Could you try with the @beta version? We landed a fix for error stacks that we'll release next week. 
Alternately, if you're using a custom build, you can skip wrangler's bundling altogether with `--no-bundle` (in both dev and publish)

**Comment by brillout** [comment] 2022-07-31 06:11
With beta it's still off:

Error thrown while running `$ wrangler dev`:
```
Error: [telefunc@0.1.22][Wrong Usage] Using `telefunc()` (`import { telefunc } from 'telefunc'`) is forbidden on the client-side, see https://telefunc.com/isomorphic-import
    at worker.js:491:7
    at handleTelefunc (worker.js:497:32)
    at handleFetchEvent (worker.js:560:31)
7:47:02 AM POST /_telefunc 500
```

The worker code generated by `$ wrangler publish --dry-run`:

```
  494   async function handleFetchEvent(event) {                                                                                                                    
  495     const { url } = event.request;                                                                                                                            
  496     const { pathname } = new URL(url);                                                                                                                        
  497     if (pathname.startsWith("/_telefunc")) {                                                                                                                  
  498       const body = await event.request.text();                                                                                                                
  499       const { method } = event.request;                                                                                                                       
  500       const response2 = await handleTelefunc({ url, method, body });                                                                                          
  501       return response2;                                                                                                                                       
  502     }                                                                                                                                                         
  503     const response = await handleStaticAssets(event);                                                                                                         
  504     return response;                                                                                                                                          
  505   }    
```

Note how `handleTelefunc()` lives at line `500` which doesn't match the stack trace.

> using a custom build, you can skip wrangler's bundling altogether with `--no-bundle`

Neat & I can confirm that works:

```
wrangler publish --dry-run --outdir worker-build 
```
```
wrangler dev --no-bundle worker-build/index.js 
```

I can start debugging now. And, yes, I think it'd be great to document this. This makes debugging 10x more fun.

(FYI I'm debugging [Telefunc](https://telefunc.com/)'s Cloudflare support.)

Thanks! I guess we can close this then.

**Comment by brillout** [comment] 2023-02-13 11:29
The line numbers are mismatching again. Using `wrangler@2.9.1`.

**Comment by brillout** [comment] 2023-02-13 11:43
A workaround is to run `$ wrangler publish --dry-run --outdir worker-build` then modify `wranger.toml#main` to point to `worker-build/index.js` and run `$ wrangler dev --no-bundle`.

**Comment by penalosa** [comment] 2023-03-13 11:24
@brillout Would you be able to setup a reproduction repository? In the meantime the custom builds/no bundle workaround will work, but if there's an issue with stack traces that's definitely something we should fix!

**Comment by brillout** [comment] 2023-03-13 11:29
👍 https://github.com/brillout/vite-plugin-ssr/tree/main/examples/cloudflare-workers-react

**Comment by penalosa** [comment] 2023-06-16 13:31
@brillout it looks like you're catching the error and logging `err.stack` in your code? That won't always match the files output by `wrangler publish --dry-run --outdir worker-build` since we apply more code transformations in dev mode than we do for publish mode. The best solution for now is to not catch the error and let it bubble up to the top level of your worker, where Wrangler will apply proper source mapping in dev mode. For instance, if your worker is:

```js
addEventListener("fetch", (e) => e.respondWith(handleRequest(e.request)));

async function handleRequest(request) {
	throw new Error("this is an error");
}
```

then accessing that in dev mode will log the following (source-mapped) stack trace to the console:

```
[mf:err] Error: this is an error
    at handleRequest (/path/to/worker/index.ts:4:8)
    at null.<anonymous> (/path/to/worker/index.ts:1:48)
```

and render the following page in your browser:
<img width="1728" alt="Screenshot 2023-06-16 at 14 30 16" src="https://github.com/cloudflare/workers-sdk/assets/28503158/32b0e2bd-de12-44d1-b030-dde18d35b2b2">

Once the Workers runtime has native support for stacktraces we should be able to provide a better experience when you access `err.stack` directly, but for now this is the best workaround. cc @admah @lrapoport-cf for reference re sourcemaps

**Closed by penalosa** 2023-06-16 13:31 UTC
Labels: enhancement
