### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by carlosdarkoficial** [cloudflare/workers-sdk#5185] opened 2024-03-06 19:52 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

npm

### What operating system and version are you using?

Linux

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide a link to a minimal reproduction

http://localhost:7700/index.html

**Comment by penalosa** [comment] 2024-03-11 15:09
I'm going to close this for now, since there isn't enough information to reproduce your issue. If you're still running into problems, feel free to open a new issue and make sure to include:
- A description of the behaviour you're running into which you think is incorrect
- A minimal reproduction of the bug

**Closed by penalosa** 2024-03-11 15:09 UTC
Labels: bug
