### ISSUE TITLE
🐛 BUG: workerd process doesn't die after wrangler exits with error

### ISSUE THREAD

**Issue by russelldavis** [cloudflare/workers-sdk#4866] opened 2024-01-29 21:58 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.25.0

### What version of Node are you using?

18.18.2

### What operating system are you using?

macOS Sonoma

### Describe the Bug

This is basically the same bug as #4612. It was fixed for the case where you exit wrangler cleanly. But if wrangler exits with an error, the bug still occurs. For example, while `wrangler pages dev` is running, edit a file and add a bad import to the top, e.g.:

```
import "askdlfjlajsdfljasdfjlk"
```

Wrangler will output an error message starting with lines that look like this:
```
/Users/russell/dev/test/node_modules/.pnpm/wrangler@3.25.0/node_modules/wrangler/wrangler-dist/cli.js:29572
            throw a;
            ^

Error: Build failed with 1 error:
api/test.ts:4:7: ERROR: Could not resolve "askdlfjlajsdfljasdfjlk"
```

It will then exit with error code 1. But the `workerd` processes will hang around, eating up 100% CPU as described at #4612.

**Comment by admah** [comment] 2024-02-09 19:56
@russelldavis could you try the latest version (3.28.1) and see if this is still an issue? I've tried replicating this and I can't seem to on that branch. 

If you add the import and save while running dev, the dev server didn't stop for me. I can still see the workerd process running. I then exited, and the process went away.

**Comment by russelldavis** [comment] 2024-02-11 02:13
@admah Thanks for taking a look. It still reproduces for me on 3.28.1. I just realized I wrote `wrangler dev` in the description when it's actually `wrangler pages dev`, maybe that's why you couldn't repro? (I haven't tried it yet on a workers project w/ `wrangler dev`, and I've updated the description.)

**Comment by petebacondarwin** [comment] 2024-02-19 13:00
@admah - can you have another go at reproducing this?

**Comment by admah** [comment] 2024-03-04 16:59
I've tried reproducing this with Wrangler 3.30.1 and am not able to. When exiting, the 2 processes remained, but once I fixed the bad import no more were added and I was able to continue to develop as expected. When I closed the dev session, all processes exited.

This is where I started the session, added the bad import, and then fixed the file:

![Screenshot 2024-03-04 at 10 55 19 AM](https://github.com/cloudflare/workers-sdk/assets/2184114/2e65a1ac-c637-418c-9126-326d20185550)

These two processes were the only ones open. They exited when I closed the session:

![Screenshot 2024-03-04 at 10 55 46 AM](https://github.com/cloudflare/workers-sdk/assets/2184114/84834a04-eb33-4465-a990-0dd5e48cc3e7)

**Comment by russelldavis** [comment] 2024-03-04 22:29
@admah I am still able to reproduce in Wrangler 3.30.1. It looks like you tested with `import asdfasdf` instead of `import "asdfasdf"` (notice the quotes). For some reason, the former error does not cause this bug, but the latter does.

**Comment by penalosa** [comment] 2024-03-18 15:15
@admah could you try reproducing this again?

**Comment by dominicdoty** [comment] 2024-04-07 06:00
I've experienced what seems to be the same issue on wrangler 3.48.0

Single process stuck running after exiting, using 100% CPU that I have to manually kill.

I'm working on finding a reproducible trigger. Happened twice today while working on a project, though seems to only come up after running the development server for some time.

**Comment by CarmenPopoviciu** [comment] 2024-04-24 14:39
Hi folks,

trying to reproduce this on latest wrangler `v 3.52.0` and getting the following:

- without bad import
<img width="773" alt="Screenshot 2024-04-24 at 15 36 04" src="https://github.com/cloudflare/workers-sdk/assets/4638332/264764cc-247f-4808-8fba-8c5db245e524">

- with bad import `import "gsdhfawhefva"`
<img width="837" alt="Screenshot 2024-04-24 at 15 36 37" src="https://github.com/cloudflare/workers-sdk/assets/4638332/42bfd817-b74b-4ab2-aec0-1851f5032be4">

@russelldavis very sorry for the back and forth, but can you pls confirm if you're seeing the same 🙏 🙇

**Comment by petebacondarwin** [comment] 2024-05-15 13:24
I'm going to close this one as without a reproduction there is nothing that we can action. If you can create a reproduction that we can debug, please open a new issue and provide the steps.

**Closed as completed by petebacondarwin** 2024-05-15 13:24 UTC
Labels: pages, awaiting reporter response

**Comment by chrwiencke** [comment] 2024-07-14 22:51
I want to pitch in and say that I also have this issue with 100% CPU usage, however I cant replicate it.
