### ISSUE TITLE
🐛 BUG: WebSocket typing doesn't work in apps that also pull in DOM types

### ISSUE THREAD

**Issue by zwily** [cloudflare/workers-sdk#5665] opened 2024-04-19 15:59 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.51.0 [Wrangler]

### What operating system and version are you using?

Mac Sonoma

### Observed behavior
I am in a Remix app on Cloudflare Pages, and adding a websocket endpoint. Things work fine, except for typescript typing. When I create a socket pair (in a loader, which runs in the worker), I get 2 WebSocket objects that are typed according to DOM WebSockets, not the Cloudflare flavor:

```
  const webSocketPair = new WebSocketPair();
  const [client, server] = Object.values(webSocketPair);

  // can't figure out how to get this typed as a cloudflare-style websocket?
  // @ts-ignore
  server.accept();
```

I believe this is happening because since this is a Remix app, the tsconfig.json specifies "DOM" in the `lib` list, and that `WebSocket` definition is overriding the one specified by workers-types.

### Expected behavior

I'm not sure what the right thing to do here is. Maybe since Cloudflare WebSockets aren't 100% compatible with a DOM WebSocket, they should use a different name, like CloudflareWebSocket?

### Steps to reproduce

- Create a Remix app for Cloudflare Pages
- Create a file `app/routes/websocket.ts`:

```
export async function loader({ request, context }: LoaderFunctionArgs) {
  const upgradeHeader = request.headers.get("Upgrade");
  if (!upgradeHeader || upgradeHeader.toLowerCase() !== "websocket") {
    return new Response("Expected WebSocket request", { status: 400 });
  }

  const webSocketPair = new WebSocketPair();
  const [client, server] = Object.values(webSocketPair);

  // can't figure out how to get this typed as a cloudflare-style websocket?
  server.accept();
  server.addEventListener("message", (event) => {
    console.log("**", event.data);
  });

  return new Response(null, {
    status: 101,
    webSocket: client,
  });
}
```

See that the `server.accept()` line has an error saying accept isn't found on WebSocket, because it thinks `server` is a DOM `WebSocket`, not the `WebSocket` defined in @cloudflare/workers-types.

Relevant issue, before workers-types had WebSocket typing at all: https://github.com/cloudflare/workers-types/issues/84

**Comment by threepointone** [comment] 2024-06-15 08:36
This is a hard one to fix in "isomorphic apps". I don't think there's a clean solution here, we can't rename our WebSocket to something else. You'd face this problem even with other runtimes as well. We'll have to think this one through...

**Comment by penalosa** [comment] 2024-07-22 17:16
This is tricky to solve, but in general we recommend _not_ typing your app against DOM types, and _only_ using `workers-types`, because they are subtly incompatible. That can definitely be tricky with frameworks like Remix which mix the two environments in the same file though (see previous discussions with the Remix team: https://github.com/cloudflare/workers-types/issues/164) . If ditching DOM types isn't an option for you, the next best thing is to do something like this using [importable types](https://github.com/cloudflare/workerd/tree/main/npm/workers-types#importable-types):

```js
import type { WebSocket as CFWebSocket } from "@cloudflare/workers-types"

const webSocketPair = new WebSocketPair();
const [client, server] = Object.values(webSocketPair);

(server as unknown as CFWebSocket).accept();
```
We should definitely figure out a way to get this working better with `WebSocketPair()` though—maybe we should have the internal definition reference a `CloudflareWebSocket` type?

**Comment by RamIdeas** [comment] 2024-08-05 13:29
I agree with @penalosa – I think we can fix this specific case by ensuring return types of `WebSocketPair` references the WebSocket type from `@cloudflare/workers-types`

**Comment by andyjessop** [comment] 2024-10-08 10:13
I'm unable to reproduce this locally. I haven't confirmed, but this is likely a result of the recent updates to the generated Worker runtime types

1. I created a new Remix app with `npm create cloudflare@latest`.
2. I added the `websocket.ts` route as specified in the original issue post.
3. I ran `tsc`.

There are no errors in `tsc` or in the editor.

The `compilerOptions` are as follows, so you can see it pulls in both `DOM` and `@cloudflare/workers-types`:

```json
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "types": [
        "@remix-run/cloudflare",
        "vite/client",
        "@cloudflare/workers-types/2023-07-01"
    ],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "target": "ES2022",
    "strict": true,
    "allowJs": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },
    "noEmit": true
  }
```

You can see here that TypeScript is referencing the `@cloudflare/workers-types` `WebSocket` interface:

<img width="899" alt="Screenshot 2024-10-08 at 12 09 44" src="https://github.com/user-attachments/assets/2a6605ed-9f67-449f-a21b-ac8c4d360dc9">

I'll close the issue, but please feel free to re-open if I've misunderstood something here.

**Closed by andyjessop** 2024-10-08 10:13 UTC
Labels: bug

**Comment by zwily** [comment] 2024-10-09 16:21
I updated @cloudflare/workers-types to `4.20241004.0` in my app where I was having this problem, and I can confirm that the typing issues are gone.
