### ISSUE TITLE
🐛 BUG: dev server crashed 

### ISSUE THREAD

**Issue by ImSingee** [cloudflare/workers-sdk#7125] opened 2024-10-30 10:07 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.83.0 [Wrangler]

### What version of Node are you using?

22.10.0

### What operating system and version are you using?

macOS 15.0

### Observed behavior

Some requests will cause the dev server to crash without any logs and can't be auto-recovered.

### Expected behavior

Serve request successfully

### Steps to reproduce

1. `pnpm create cloudflare demo`, choose "Hello World example" and "Hello World Worker"
2. `pnpm dev` to start it (on port 8787)
3. Open `bun repl` in another shell, run `await fetch('http://localhost:8787')`
4. The wrangler dev server crashed (though no logs printed), and `curl http://localhost:8787` will also stop working

**Comment by ImSingee** [comment] 2024-10-30 10:08
Nearly the same as https://github.com/cloudflare/workers-sdk/issues/6176 https://github.com/oven-sh/bun/issues/12730

But this is definitely wrangler's bug, not bun's

**Comment by penalosa** [comment] 2024-11-04 14:21
To confirm, does this issue present with no usage of bun?

**Comment by ImSingee** [comment] 2024-11-04 14:23
@penalosa Honestly, to my knowledge, the only thing can cause this happen is to use bun to send a request.

**Comment by advancedtw** [comment] 2024-11-14 16:35
I had that happen to me I thought it was my setup or I was sending too many request. The thing is in the past I have sent many request to local worker using bun without issue. I don't remember which version but 3.86 is so bad can't even do wrangler dev without "exited with code 1."  I'm also on mac (14.6)

**Comment by andyjessop** [comment] 2024-11-15 12:51
@ImSingee thanks very much for reporting this. I've tried to reproduce this locally, and I'm unable to reproduce:

```
andy in ~/dev/tmp/demo on main
$ pnpm dev

> demo@0.0.0 dev /Users/andy/dev/tmp/demo
> wrangler dev


 ⛅️ wrangler 3.87.0
-------------------

⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (3ms)
```

```
andy in ~/dev/tmp/demo on main
$ bun repl
Welcome to Bun v1.1.27
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> await fetch('http://localhost:8787')
Response {}
>
```

But a reproduction notwithstanding, we don't actually support Bun in this way, so I'll close this issue for now.

**Closed by andyjessop** 2024-11-15 12:51 UTC
Labels: bug
