### ISSUE TITLE
🐛 BUG: workerd inspector process doesn't die

### ISSUE THREAD

**Issue by jjonte** [cloudflare/workers-sdk#4612] opened 2023-12-16 03:55 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.21.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

MacOS, Sonoma

### Describe the Bug

When shutting down a running `wrangler dev` on a basic "hello world" Worker, an extra workerd process hangs around, occupies the port, and eats CPU cycles (1 core @ ~100%). The only solution is to Force Quit the process.

```
export default {
	async fetch(request: Request, env: unknown, ctx: ExecutionContext) {
		return new Response('hello world');
	},
};
```

### Please provide any relevant error logs

When running `wrangler dev` it looks like this:
![Screenshot 2023-12-15 at 10 45 16 PM](https://github.com/cloudflare/workers-sdk/assets/108731/b77beca9-7f4f-421e-b6f6-325c47d925fd)

After pressing x in the terminal window this happens:
![Screenshot 2023-12-15 at 10 45 36 PM](https://github.com/cloudflare/workers-sdk/assets/108731/e6dffab9-faad-41f7-8353-d8f10aa3b081)

![Screenshot 2023-12-15 at 10 46 50 PM](https://github.com/cloudflare/workers-sdk/assets/108731/82331da0-4245-428f-8e78-08695b91e107)

![Screenshot 2023-12-15 at 10 46 37 PM](https://github.com/cloudflare/workers-sdk/assets/108731/ce1feb0b-1e5e-4a53-a065-9996819da386)

**Comment by zhawtof** [comment] 2023-12-17 05:51
I'm also experiencing the same issue. Same wrangler version and Mac specs.

**Comment by ezg27** [comment] 2023-12-17 21:41
Experiencing the same with MacOS Ventura 13.5.1, Node v20.9.0.

It looks as though this may have started in Wrangler v3.20.0 with [this](https://github.com/cloudflare/workers-sdk/pull/4571) PR to add Sentry crash reporting. Commenting out the `await closeSentry()` call [here](https://github.com/cloudflare/workers-sdk/blob/912bfeb249a3047804bcb7c152b4f71507ce6c8c/packages/wrangler/src/index.ts#L772) leads to Wrangler processes exiting successfully with both `cmd+c` and the `[x] to exit` shortcut. Processes also exit successfully when reverting to Wrangler v3.19.0 before the Sentry handling was added.

Haven't managed to figure out exactly what's causing things to hang yet though. The [Node docs](https://nodejs.org/api/process.html#processdisconnect) say the following re calls to `process.disconnect()`:

```...the process.disconnect() method will close the IPC channel to the parent process, allowing the child process to exit gracefully once there are no other connections keeping it alive.```

So could be there's some connections from Sentry flushing events in `Sentry.close()` that are preventing things from exiting?

**Comment by alpertuna** [comment] 2023-12-18 04:38
My setup: Arch Linux Kernel: 6.6.7-arch1-1, NodeJs: v21.4.0

I have a similar issue but it is not new for me, when I realized the hanging processes, the wrangler version was v3.17.

Now I use wrangler v3.20 but the issue is still there.

I use wrangler for local development. Whenever I stop the `wrangler dev`, there is always a workerd process left behind that keeps the default port open and, makes cpu 100% after some time.
I can't kill the process gracefully, so I need to kill it forcefully.

To automatically kill the zombie process, I use a script similar to the script mentioned here; https://github.com/cloudflare/workers-sdk/issues/3378

**Comment by admah** [comment] 2023-12-18 17:10
@jjonte thanks for filing this bug. We are taking a look and will add updates as they are availaible.

**Comment by admah** [comment] 2023-12-18 18:56
Possibly related to #4131

**Comment by peterboyer** [comment] 2023-12-20 10:47
I am also experiencing this problem. 

Downgrading to `wrangler@3.19.0` fixes the zombie process for me.
Upgrading to `wrangler@3.20.0` re-introduces the zombie process.
Problem still present as of `wrangler@3.22.0`.

Node v20.5.0

**Comment by peterboyer** [comment] 2023-12-20 11:44
**I think I found the cause of the problem + a hacky/temporary workaround for local dev.**

---

I just inspected the diff[1] between release tags [`wrangler@3.19.0`](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.19.0) and [`wrangler@3.20.0`](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.20.0).

[1] https://github.com/cloudflare/workers-sdk/compare/wrangler%403.19.0...wrangler%403.20.0

I found this newly added call[2] of `await Sentry.close();` as part of `wrangler`'s recent introduction of Sentry for error reporting.

[2] [packages/wrangler/src/sentry/index.ts:130 (from diff)](https://github.com/cloudflare/workers-sdk/compare/wrangler%403.19.0...wrangler%403.20.0#diff-0e3eb03e60d5bf1c7273e7a89fc284e20625c62dba5d9fffd6fac7483e3c9ebbR130)

---

If you install `wrangler@3.20.0`, open up `.../node_modules/wrangler/wrangler-dist/cli.js`, and comment out the corresponding minified `await close();` call on line `154410` (found by searching for the nearby `"Would you like to report this error to Cloudflare?"` string) then the **`workerd` process now properly quits without hanging**.

We can upgrade to `wrangler@3.22.0`, open up `.../node_modules/wrangler/wrangler-dist/cli.js`, and comment out the same call on line `154209` (found by the same search string as above) and the **`workerd` process now properly quits without hanging**.

---

This `await Sentry.close();` call is part of the `closeSentry()` function as part of the new Sentry integration.

https://github.com/cloudflare/workers-sdk/blob/35e8a5dc261256cb0122f56f0b71dadbacd6d80b/packages/wrangler/src/sentry/index.ts#L128-L132

It seems that awaiting this function is not resolving when being called as part `wrangler`'s `main()` function's `finally` block, which is then preventing `process.disconnect()` from being called, which I presume is in charge of letting the `workerd` process die.

https://github.com/cloudflare/workers-sdk/blob/35e8a5dc261256cb0122f56f0b71dadbacd6d80b/packages/wrangler/src/index.ts#L767-L775

---

I hope this helps.

For now, if you'd like to hack around the problem for local development before this is patched upstream: you may upgrade to `wrangler@latest` and comment out this Sentry `await close();` call to allow `workerd` to quit gracefully.

**Closed** 2023-12-20 14:22 UTC
Labels: bug, start-dev-worker
