### ISSUE TITLE
🐛 BUG: Generating project from typescript template fails

### ISSUE THREAD

**Issue by petoknm** [cloudflare/workers-sdk#2799] opened 2023-02-25 11:00 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.11.1

### What operating system are you using?

Linux

### Describe the Bug

Copy pasting the command from quickstart page on workers...

```
$ npx wrangler generate my-app cloudflare/workers-sdk/tree/main/templates/worker-typescript
 ⛅️ wrangler 2.11.1 
--------------------
Creating a worker in my-app from cloudflare/workers-sdk/tree/main/templates/worker-typescript

✘ [ERROR] Failed to find "tree/main/templates/worker-typescript" in https://github.com/cloudflare/workers-sdk.git


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Expected result: Successfully generate the project
Actual result: Error, no project generated

**Comment by Cherry** [comment] 2023-02-26 16:50
I can confirm this issue in Windows too, and even when using https://github.com/cloudflare/workers-sdk/pull/2735.

**Comment by lrapoport-cf** [comment] 2023-03-03 04:29
i believe this is a documentation error and should be fixed by https://github.com/cloudflare/cloudflare-docs/pull/7728

**Comment by penalosa** [comment] 2023-03-03 14:16
Fixed in https://github.com/cloudflare/cloudflare-docs/pull/7728

**Comment by Cherry** [comment] 2023-03-03 15:10
This does not appear to be resolved.

```
 npx wrangler@latest generate my-app worker-router
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from worker-router

✘ [ERROR] Failed to find "worker-router" in https://github.com/cloudflare/templates.git
```


```
npx wrangler@latest generate my-app mhart/cf-sentry
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from mhart/cf-sentry

✘ [ERROR] Failed to find "undefined" in https://github.com/mhart/cf-sentry.git
```

**Comment by penalosa** [comment] 2023-03-03 16:05
To try and narrow this down, does `npx wrangler generate my-app https://github.com/flareact/flareact` work?

**Comment by Cherry** [comment] 2023-03-03 16:06
It does not, no:
```
 npx wrangler@latest generate my-app https://github.com/flareact/flareact
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from https://github.com/flareact/flareact

✘ [ERROR] Failed to find "undefined" in https://github.com/flareact/flareact.git
```

**Comment by penalosa** [comment] 2023-03-03 16:09
Does that work in WSL?

**Comment by Cherry** [comment] 2023-03-03 16:15
It does not, when I run it on my Windows filesystem:
```
cherry@WINDOWS-JAMES:/mnt/e$ npx wrangler@latest generate my-app https://github.com/flareact/flareact
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from https://github.com/flareact/flareact

✘ [ERROR] Failed to find "undefined" in https://github.com/flareact/flareact.git
```
`WRANGLER_LOG=debug` didn't provide any more info unfortunately. 🤔

But if I run specifically on my Linux filesystem, it works fine:

```
cherry@WINDOWS-JAMES:~$ npx wrangler@latest generate my-app https://github.com/flareact/flareact
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from https://github.com/flareact/flareact
✨ Success!
```

**Comment by penalosa** [comment] 2023-03-03 18:09
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2850, which captures the root cause here for the Windows issue. The original issue has been address by a documentation change to the QuickStarts page

**Closed by penalosa** 2023-03-03 18:09 UTC
Labels: bug, templates
