### ISSUE TITLE
🐛 BUG: bulk secret insert operation fails

### ISSUE THREAD

**Issue by KamaniBhavin** [cloudflare/workers-sdk#4675] opened 2023-12-30 08:19 UTC
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

wrangler 3.22.1

### What version of Node are you using?

v18.18.2

### What operating system are you using?

macOS 14.1.2

### Describe the Bug

**Issue Summary: Unable to Load Secrets into Worker Script**

**Description:**
I am encountering an issue while attempting to load secrets from a `secrets.json` file into my worker script using the command `cat secrets.json | npx wrangler secret:bulk --env development`. The process fails without displaying any errors in the terminal.

**Additional Context:**
Upon inspecting the logs, I identified a missing `.env.development` file, which wasn't required in earlier versions of wrangler. After creating the `.env.development` file and rerunning the command, the process failed again. In the logs, I noticed a failed PATCH request to Cloudflare for inserting secrets, resulting in an HTTP status code of 400.

**Expected Behavior:**
The command should successfully load secrets into the worker script without errors.

### Please provide any relevant error logs

```
--- 2023-12-30T07:52:35.824Z debug
🪵  Writing logs to "/Users/bhavinkamani/.wrangler/logs/wrangler-2023-12-30_07-52-35_712.log"
---

--- 2023-12-30T07:52:35.824Z log
 ⛅️ wrangler 3.21.0 (update available [32m3.22.1[39m)
[38;5;214m-------------------------------------------------------[39m
---

--- 2023-12-30T07:52:35.830Z log
🌀 Creating the secrets for the Worker "cf-static-assets-dev" 
---

--- 2023-12-30T07:52:35.834Z debug
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/ee0ca54b5c041011478678fb2bf726a4/workers/scripts/cf-static-assets-dev/settings
---

--- 2023-12-30T07:52:35.834Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:35.834Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:35.834Z debug
-- END CF API REQUEST
---

--- 2023-12-30T07:52:37.473Z debug
-- START CF API RESPONSE: OK 200
---

--- 2023-12-30T07:52:37.473Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:37.473Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:37.473Z debug
-- END CF API RESPONSE
---

--- 2023-12-30T07:52:37.474Z debug
-- START CF API REQUEST: PATCH https://api.cloudflare.com/client/v4/accounts/ee0ca54b5c041011478678fb2bf726a4/workers/scripts/cf-static-assets-dev/settings
---

--- 2023-12-30T07:52:37.474Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:37.474Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T07:52:37.474Z debug
-- END CF API REQUEST
---

--- 2023-12-30T07:52:39.111Z debug
-- START CF API RESPONSE: Bad Request 400
---

--- 2023-12-30T07:52:39.112Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---
```

**Comment by KamaniBhavin** [comment] 2023-12-30 13:29
It seems to be working intermittently 🤔. I'm puzzled because it was functioning correctly an hour ago, and my GitLab CI successfully deployed the worker to Cloudflare. However, in the current pipeline run, the same process is failing, and the logs indicate the following:

```

--- 2023-12-30T13:24:40.840Z debug
🪵  Writing logs to "/Users/bhavinkamani/.wrangler/logs/wrangler-2023-12-30_13-24-40_727.log"
---

--- 2023-12-30T13:24:40.840Z log
 ⛅️ wrangler 3.22.1
[38;5;214m-------------------[39m
---

--- 2023-12-30T13:24:40.846Z debug
Retrieving cached values for account from node_modules/.cache/wrangler
---

--- 2023-12-30T13:24:40.846Z log
🌀 Creating the secrets for the Worker "cf-static-assets-dev" 
---

--- 2023-12-30T13:24:40.846Z debug
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/ee0ca54b5c041011478678fb2bf726a4/workers/scripts/cf-static-assets-dev/settings
---

--- 2023-12-30T13:24:40.846Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:40.846Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:40.846Z debug
-- END CF API REQUEST
---

--- 2023-12-30T13:24:44.348Z debug
-- START CF API RESPONSE: OK 200
---

--- 2023-12-30T13:24:44.348Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:44.348Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:44.348Z debug
-- END CF API RESPONSE
---

--- 2023-12-30T13:24:44.349Z debug
-- START CF API REQUEST: PATCH https://api.cloudflare.com/client/v4/accounts/ee0ca54b5c041011478678fb2bf726a4/workers/scripts/cf-static-assets-dev/settings
---

--- 2023-12-30T13:24:44.349Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:44.349Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:44.349Z debug
-- END CF API REQUEST
---

--- 2023-12-30T13:24:46.333Z debug
-- START CF API RESPONSE: Bad Request 400
---

--- 2023-12-30T13:24:46.333Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:46.333Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-12-30T13:24:46.333Z debug
-- END CF API RESPONSE
---

--- 2023-12-30T13:24:46.334Z log

---

--- 2023-12-30T13:24:46.334Z log
Finished processing secrets JSON file:
---

--- 2023-12-30T13:24:46.334Z log
✨ 0 secrets successfully uploaded
---

--- 2023-12-30T13:24:46.335Z log

---

--- 2023-12-30T13:24:46.422Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1m🚨 5 secrets failed to upload[0m


---

--- 2023-12-30T13:24:46.422Z log
[32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose[0m
---

--- 2023-12-30T13:24:50.356Z debug
Sentry: Capturing exception Error: 🚨 5 secrets failed to upload
---

```


This behavior is inconsistent with the successful deployment an hour ago.

**Comment by petebacondarwin** [comment] 2024-01-02 18:31
I believe the debug log warning about a missing .env.development file is a red-herring and not relevant.

**Comment by petebacondarwin** [comment] 2024-01-02 18:59
I think we need to log the `err` to get more information from this issue at this point: https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/secret/index.ts#L473

@KamaniBhavin - are you seeing this locally or only in CI? If you can reproduce it locally perhaps you could patch the `node_modules/wrangler/wrangler-dist/cli.js` file to log this error?

**Comment by petebacondarwin** [comment] 2024-01-03 10:59
Actually this is a duplicate of https://github.com/cloudflare/workers-sdk/issues/4496.

**Closed by petebacondarwin** 2024-01-03 10:59 UTC
Labels: bug, internal, wrangler
