### ISSUE TITLE
🐛 BUG: wrangler login only lists the first 20 accounts

### ISSUE THREAD

**Issue by celso** [cloudflare/workers-sdk#4349] opened 2023-11-06 14:11 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0 [Wrangler]

### What version of Node are you using?

v18.18.2

### What operating system are you using?

Mac

### Describe the Bug

I have more than 20 cloudflare accounts under my profile. When wrangler sends me through the account selector view, it only lists my first 20 accounts and it does not paginate.

Looks like getAccountChoices is using the /membership method, which defaults to 20 per_page items https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/choose-account.tsx#L12

**Comment by admah** [comment] 2023-11-06 23:35
Duplicate of #3257

**Closed** 2023-11-13 14:49 UTC
Labels: bug
