### ISSUE TITLE
🐛 BUG: Circular Bindings Between Workers with Durable Objects

### ISSUE THREAD

**Issue by Lotfi-Arif** [cloudflare/workers-sdk#3152] opened 2023-05-05 14:02 UTC
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

Mac

### Describe the Bug

Hello Cloudflare Support,

I am writing to report a bug I encountered involving circular bindings between two Workers that both have Durable Objects. I have been able to replicate the issue using Wrangler version 2.19.0.

**Bug description:**
When I serve both Workers locally, they end up stuck in an infinite serving loop between the two Workers.

**Steps to reproduce:**
Set up two Workers with Durable Objects on Wrangler version 2.19.0.
Create circular bindings between the two Workers.
Serve both Workers locally using wrangler dev.

**Expected behavior:**
I expect the Workers to communicate with each other without getting stuck in an infinite loop.

**Actual behavior:**
The Workers get stuck in an infinite serving loop, which seems to be caused by the circular bindings between the Durable Objects in both Workers.

Here is the repo that I created which replicates the behavior that I mentioned: [worker-circular-binding](https://github.com/Lotfi-Arif/worker-circular-binding)

Please let me know if you need any further information to help resolve this issue. I would appreciate it if you could investigate and provide a solution or workaround for this problem.

Thank you in advance for your assistance.

**Comment by penalosa** [comment] 2023-07-11 22:07
Thanks for reporting this, and the detailed reproduction. Unfortunately, based on the reproduction you provided it looks like the behaviour you're seeing isn't a result of the use of Durable Objects. It looks like your Workers unconditionally fetch each other, which leads to an infinite request loop (Worker 1 fetches worker2, which fetches worker 1, which fetches worker 2 and so on). If possible, it would be great to hear a bit more about your use case, which could maybe help with debugging this.

I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!

**Closed by penalosa** 2023-07-11 22:07 UTC
Labels: bug
