### ISSUE TITLE
🐛 BUG: wrangler throws error trying to list secrets when no secrets set

### ISSUE THREAD

**Issue by johtso** [cloudflare/workers-sdk#6287] opened 2024-07-18 21:31 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.65.0 [wrangler]

### What operating system and version are you using?

Mac Sonoma

### Describe the Bug

```
~/Code/services/email-sender on main •
❯ wrangler secret list --env staging                                                                                                           22:23:26

✘ [ERROR] A request to the Cloudflare API (/accounts/814e8d36e1399315694670071a13c144/workers/scripts/email-sender-staging/secrets) failed.

  workers.api.error.script_not_found [code: 10007]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose



~/Code/services/email-sender on main •
❯ wrangler secret put foo --env staging                                                                                                        22:23:38

 ⛅️ wrangler 3.65.0
-------------------

✔ Enter a secret value: … ****
🌀 Creating the secret for the Worker "email-sender-staging"
✨ Success! Uploaded secret foo

~/Code/services/email-sender on main •
❯ wrangler secret list --env staging                                                                                                           22:28:12
[
  {
    "name": "foo",
    "type": "secret_text"
  }
]
```

**Comment by CarmenPopoviciu** [comment] 2024-07-19 17:06
hi @johtso ,

thank you for raising this issue with us 🙏 

@WalshyDev and I had a look (thaaaaank you Walshy!!!!!) and it seems that at the time you ran the `wrangler secret list --env staging` command, your Worker was not yet deployed, which is why you got the `workers.api.error.script_not_found` error...which basically tries to communicate exactly what I said, albeit in a very cryptic manner.

We also see that once you deployed your Worker the `secret` command returns what is expected of it. So it would seem that this is fixed for you, but please do confirm that just to be abs sure 🙏 

Not sure if our command docs are confusing (pls let us know if you did find them so), or if anything else played out here, but just to clarify, `wrangler secret` requires that the Worker for which it is invoked for exists prior to running the command. So the order in which you'd want to run these commands is:
```
wrangler deploy --env [env_name]
wrangler secret put ...
wrangler secret list ...
```

When `wrangler secret put` is omitted, then `wrangler secret list` will return an empty array. 

Having said that, the one thing we could action on here, is the cryptic error message, which really doesn't help our users understand what is going on. We'll be tracking that work in WC-2399

Hope this helps

**Comment by johtso** [comment] 2024-07-19 17:19
Just to clarify, the list command was run _after_ freshly deploying the worker (staging env, first deployment of that worker across any env).

I don't know if it's expected to take some time after first deployment for the list command to work and return the empty array perhaps? Would you usually expect list to work prior to the first put having been done?

**Comment by CarmenPopoviciu** [comment] 2024-07-19 17:43
> was run after freshly deploying the worker

hmmm...this is not what we see in our traces. We definitely see and attempt to `PUT /secrets` *before* the Worker is deployed.

I also tried to repro your use case, and cannot, unless I call `wrangler secret` before `wrangler deploy` :/

How did you deploy your Worker? And how are u running these commands? From your terminal? 

> I don't know if it's expected to take some time after first deployment for the list command to work
no, this shouldn't be an issue

> Would you usually expect list to work prior to the first put having been done
if no secrets were `PUT` `list` should return an empty array, which I can confirm it does

**Comment by johtso** [comment] 2024-07-19 17:51
Ah, right you are! While scrolling through my shell history I missed the fact that my deploy failed because of a missing queue, so you're right, the worker had not been deployed. Sorry about the misdirection!

**Comment by CarmenPopoviciu** [comment] 2024-07-19 17:53
not at all! I am really glad you raised this with us ❤️ . We get to fix those unhelpful messages because of that so yay!!

closing and thank you again!!

**Closed by CarmenPopoviciu** 2024-07-19 17:53 UTC
Labels: awaiting reporter response, bug
