### ISSUE TITLE
🐛 BUG: fetch cannot connect to local https server with self signed certificate

### ISSUE THREAD

**Issue by mariusGundersen** [cloudflare/workers-sdk#4257] opened 2023-10-23 07:50 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.7.0 [Wrangler]

### What version of Node are you using?

18.13.0

### What operating system are you using?

Windows

### Describe the Bug

I'm having trouble running my pages project locally, as fetch always fails to connect to my locally running api server. I have some functions in my pages project that make fetch requests to a REST api, in production this will run on a different server but for local testing it runs on my local machine. For reasons out of my control it runs as an https server with a self signed certificate (that I don't have any control over, again, outside of my control) on `https://localhost:9002`. Unfortunately I am unable to get the functions to connect to it, instead I get this error:

```
workerd/jsg/util.c++:275: error: e = kj/compat/tls.c++:221: failed: TLS peer's certificate is not trusted; reason = unable to get local issuer certificate
stack: 7ff7da5ad190 7ff7da5f09ec 0 0 0 7ff7da92f778 7ff7da93061b 7ff7da932948 0 0 0 7ff7da8b477d 0 0; sentryErrorContext = jsgInternalError
[mf:err] Error: internal error
[mf:inf] GET / 500 Internal Server Error (534ms)
```

I have tried using `NODE_EXTRA_CA_CERTS`, `SSL_CERT_FILE` and `NODE_TLS_REJECT_UNAUTHORIZED=0` but I still get the same issue. 

### Please provide a link to a minimal reproduction

https://github.com/mariusGundersen/wrangler-https

**Comment by mariusGundersen** [comment] 2023-10-24 07:24
I have tried that, as I said. Just to make it extra obvious I have made a new npm script which sets `NODE_EXTRA_CA_CERTS` and it still fails.

**Comment by penalosa** [comment] 2023-10-24 09:25
Thanks for adding that script! I've looked into this a bit more, and while I can reproduce your error with your specific certificates, Wrangler behaves correctly with new certificates. Could you try generating a certificate and private key with the following command?

```sh
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 30 -out cert.pem -subj "/CN=localhost"
```

Additionally, you'll need to use an absolute path to your certificate file in `NODE_EXTRA_CA_CERTS`:

```sh
cross-env NODE_EXTRA_CA_CERTS=/path/to/wrangler-https/localhost.crt wrangler pages dev ./public
```

I'm going to close this for now, but feel free to comment with more details if those steps don't work for you, and we can investigate further.

**Closed by penalosa** 2023-10-24 09:25 UTC
Labels: needs reproduction, bug

**Comment by mariusGundersen** [comment] 2023-10-24 09:56
So is the problem here that workerd doesn't understand `X509v3 Subject Alternative Name`? Or that it requires `X509v3 Subject Key Identifier` and `X509v3 Authority Key Identifier`?

I am able to get this to work with the certificate generated with your openssl command, but unfortunately I can't replace the certificate of the actual server that I want to connect to (this is just a minimal reproduction). The actual certificate is a bit weird, but uses `X509v3 Subject Alternative Name`. That might be why it's not working.

**Comment by Djennez** [comment] 2023-11-08 12:07
I thought I'd share this since we have been running into this error as well; 
`workerd/jsg/util.c++:275: error: e = kj/compat/tls.c++:221: failed: TLS peer's certificate is not trusted; reason = unable to get local issuer certificate`. 

After looking for configuration errors for way too long, I stumbled upon this thread and started experimenting with new certificate generation, and like with @mariusGundersen, it started to work with a basic newly generated certificate (thanks @penalosa).

After some trial and error, I found our problem was that the original certificate did not have `keyUsage` set to `keyCertSign`. None of the pieces of software in the environment saw this as an error, except for the Cloudflare worker. I guess that the used SSL library from the worker is more strict in this regard.

Hopefully this info might help someone with the same problem.
