### ISSUE TITLE
🚀 Feature Request: next-on-pages --remote D1

### ISSUE THREAD

**Issue by jonathangreensted** [cloudflare/workers-sdk#5096] opened 2024-02-26 07:05 UTC
### Describe the solution

Could --remote flag be supported for next-on-pages projects using D1 please?

I'd like this to work:

npm run pages:build && wrangler pages dev .vercel/output/static --compatibility-date=2024-01-17 --compatibility-flag=nodejs_compat --d1 DB=[db-id] --remote

Maybe I'm missing something but it seems tricky to clone the remote db back to my local dev environment.  Happy to be shown a better way!

**Comment by ctarmor** [comment] 2024-03-03 16:32
This would be nice!

Here is my issue:

https://github.com/cloudflare/workers-sdk/issues/3505#issuecomment-1975219478

**Comment by penalosa** [comment] 2024-11-08 22:31
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/4929

**Closed by penalosa** 2024-11-08 22:31 UTC
Labels: enhancement, d1
