### ISSUE TITLE
🐛 BUG: _routes.json is not respected when using a proxy command

### ISSUE THREAD

**Issue by grimsteel** [cloudflare/workers-sdk#2950] opened 2023-03-27 00:15 UTC
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.13.9

### What operating system are you using?

Windows

### Describe the Bug

When using `wrangler pages dev` with a proxy command, any `_routes.json` file served by the proxy server is not respected.

Example Repo: https://github.com/grimsteel/cf-pages-routes-proxy-not-respected

Steps for reproduction are in the README.

Essentially, _routes.json is only respected when serving static files from a directory which includes it. When using a proxy server, even if it serves a _routes.json at the root, it's not respected and the functions will be invoked for all routes

**Comment by CarmenPopoviciu** [comment] 2023-03-28 11:48
hi @grimsteel,

thank you for reporting this issue, and especially for the very comprehensive repro repository <3!

Currently, `wrangler pages dev -- <COMMAND>` doesn't support any special metafiles such as `_headers`, `_redirects`, or `_routes.json`. 

This has to do with the fact that when run in this mode, wrangler will defer the serving of the static assets entirely to the server spun up by the proxy command. Since `routes.json` has no special meaning in the context of the proxy dev server, even though that file is technically served, its routing rules are never applied, as the proxy dev server wouldn't know how to. Furthermore, in order for wrangler to apply the `_routes.json` routing rules, it would need to know where this specific file lives. However, at the moment, [the only way to do that](https://github.com/cloudflare/workers-sdk/blob/0a77990457652af36c60c52bf9c38c3a69945de4/packages/wrangler/src/pages/dev.ts#L399) is via `wrangler pages dev <DIRECTORY>`, where DIRECTORY is the directory of static assets to serve. Supplying both a `<DIRECTORY>` and proxy command is currently [not supported](https://github.com/cloudflare/workers-sdk/blob/0a77990457652af36c60c52bf9c38c3a69945de4/packages/wrangler/src/pages/dev.ts#L213).

We currently have no plans to provide metafiles support with proxy commands in the near future. If you have any further questions please feel free to follow-up in this thread. For now, closing, as this is expected behaviour

**Closed by CarmenPopoviciu** 2023-03-28 11:48 UTC
Labels: pages, bug
