### ISSUE TITLE
Pages dev reading wrangler.toml is really confusing

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#3757] opened 2023-08-14 03:02 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Windows

### Describe the Bug

People are so often confused when they can define bindings, DOs, etc. with `wrangler.toml` and it works in `pages dev`.

They then publish their project with `pages deploy` and none of their bindings show up, get very confused, and end up in the Discord wondering what they did wrong. This is a very disjunct experience and is hit by users every single week in the Discord.

Example conversation excerpt from recently:

> user: I'm able to push to github and pages does sync and deploy properly. But none of the wrangler durable object bindings are showing within the worker object functions under settings.
> user: My wrangler settings are
```
name = "xxx"
workers_dev = true
compatibility_date = "2023-08-07"
main = ".svelte-kit/cloudflare/_worker.js"

[[durable_objects.bindings]]
name = "room"
class_name = "DurableObjectNameSpace"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectNameSpace"]
```

> me: Pages doesn't use wrangler.toml unfortunately
> me: In dev it kinda works, but that's technically a bug and it shouldn't
> me: All pages configuration has to be done via the API directly, or the Pages dashboard
> me:  And unfortunately, you can not publish new DO namespaces with Pages today either. You can bind to existing ones, but you'll have to publish new ones with an external worker. 

> user: oh wow. Very alpha status lol

This experience is probably one that'll improve in convergence, but until then, if `wrangler.toml` isn't going to be used in the same way that it is for workers, where you can use it for config, it should probably be **made very clear when publishing that anything in your `wrangler.toml` is ignored**.

**Comment by snilan** [comment] 2023-08-27 02:25
This is honestly my biggest gripe with Cloudflare right now. Having a different experience for bindings between Pages and Workers is very frustrating

**Comment by Wallacy** [comment] 2023-10-26 00:37
The problem is not that pages should not read wrangler.toml on using pages dev... its actually nice that they do because is way more complex to do passing all binding using cli; Also for people like me that uses _worker.js and actually uses regular worker and pages together is the best;

Pages does not need any "new" config file. Just need to read wrangler.toml and apply the correspondent bindings/config to that script. On the deployment page we have all the individual config anyway.

**Comment by lyc8503** [comment] 2023-11-10 16:47
Hello, how can I bind a kv namespace to a pages project via wrangler then if it doesn't respect `wrangler.toml`? Must I manually open Cloudflare Dashboard to do that? Can't I just achieve that via wrangler? I want to use that in a headless pipeline but haven't found any ways to do that...

**Comment by jkonowitch** [comment] 2024-01-29 14:48
I can't believe this has not been addressed yet. This is a pretty significant and obvious confusion that could easily be addressed in the documentation. Just add an info/warning box to the Pages docs calling out that, for now, wrangler.toml isn't used. Though, my 2 cents is that it the toml file _should_ work for pages so cloudflare infra can be checked into source control rather than configured via the dashboard.

**Comment by Cherry** [comment] 2024-01-30 15:56
I'm not entirely sure that docs PR reduces much confusion. What is/isn't supported is only a small part of the confusion here - most folks in my experience are confused by the very different outcomes with using `wrangler.toml` with Workers, and things get published, vs with Pages, where things don't.

When Pages does support configuration, is this format going to work exactly the same within `wrangler.toml`? Or will folks have to change their configs again when that lands?

**Comment by admah** [comment] 2024-04-11 15:04
I'm going to close this out now that `wrangler.toml` is available to all users in an open beta and is documented.

**Closed by admah** 2024-04-11 15:04 UTC
Labels: pages, bug
