### ISSUE TITLE
🐛 BUG: deprecated dependencies

### ISSUE THREAD

**Issue by benmccann** [cloudflare/workers-sdk#6189] opened 2024-07-02 18:12 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.62.0

### What operating system and version are you using?

any

### Describe the Bug

Wrangler has deprecated packages in its dependency tree, which causes deprecation warnings for us when doing pnpm install

https://npmgraph.js.org/?q=wrangler

![Screenshot from 2024-07-02 11-09-38](https://github.com/cloudflare/workers-sdk/assets/322311/a36108aa-4388-40c5-92ad-2a46de02f20c)

It looks like you need to switch from `@esbuild-plugins/node-modules-polyfill` to `esbuild-plugin-polyfill-node`

### Please provide a link to a minimal reproduction

pnpm install wrangler

### Please provide any relevant error logs

 WARN  2 deprecated subdependencies found: rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8

**Comment by petebacondarwin** [comment] 2024-07-08 14:48
This was discussed at some length in https://github.com/cloudflare/workers-sdk/issues/1232.
The current plan is to move to a completely new approach to node-compat that uses unenv and built-in run time modules.
We don't plan to update these plugins.

**Comment by benmccann** [comment] 2024-07-08 14:54
It's been TWO YEARS!! Can we update the plugins in the meantime instead of serving deprecated versions to all of our users? This is truly ridiculous

What's the release timeline for wrangler 4?

**Comment by benmccann** [comment] 2024-07-08 17:45
I found this fixed as the last commit in the v4 branch four months ago: https://github.com/cloudflare/workers-sdk/pull/5209. But there have been no further updates to the branch since then

**Comment by petebacondarwin** [comment] 2024-07-08 19:36
These are just warnings. Do you actually have a bug in the node_compat feature that would be resolved by changing these dependencies?

**Comment by benmccann** [comment] 2024-07-08 20:19
There's no bug and I get that they're just warnings, but I don't want to teach our users to ignore warnings nor do we want to ignore them in our own projects. Users file bugs against us everytime we have deprecation warnings, it causes our audit checks to fail, and it's just not consistent with the quality of our offering to generate warnings for years while telling users to ignore them.

**Comment by RamIdeas** [comment] 2024-08-19 13:48
To provide an update here we have a new node compat feature about to launch soon which will become our primary recommendation for node polyfills _but_ we cannot remove the old node compat feature without a breaking change.

Since this issue pertains to warnings caused by deprecated dependencies needed for the old node compat feature, I've applied a breaking change label.

Although, if we wanted to fix this without a breaking change, we could consider vendoring the deprecated packages into our repo.

**Comment by irvinebroque** [comment] 2024-08-19 15:47
Vendoring makes sense to me

**Comment by penalosa** [comment] 2024-12-03 15:20
Closed by #7336

**Closed by penalosa** 2024-12-03 15:20 UTC
Labels: bug

**Comment by benmccann** [comment] 2025-03-13 22:37
I wanted to share a huge thank you to everyone here who worked on the new wrangler 4 that is out now for working to fix this!!
