### ISSUE TITLE
🚀 Feature Request: [C3] Automate bumping versions of frameworks

### ISSUE THREAD

**Issue by jculvey** [cloudflare/workers-sdk#3329] opened 2023-05-23 16:50 UTC
### Describe the solution

Today we pin the version of the web frameworks we support in a json file. The process of discovering new versions, testing that they work with c3, and bumping them if possible is manual and time consuming. It would be useful to automate as much of this as possible to help with maintainability.

We should have a CI workflow that runs our existing tests on newer versions of framework and surfaces to the team newer compatible versions that we can move to. It would also alert us to new, incompatible versions of frameworks that need attention.

**Comment by IgorMinar** [comment] 2023-08-22 22:43
closing as dupe of https://github.com/cloudflare/workers-sdk/issues/3805

**Closed by IgorMinar** 2023-08-22 22:43 UTC
Labels: enhancement, c3
