### ISSUE TITLE
🚀 Feature Request: keep json files in `node_modules/.cache/wrangler` at another location

### ISSUE THREAD

**Issue by harryzcy** [cloudflare/workers-sdk#4429] opened 2023-11-12 09:21 UTC
### Describe the solution

Right now, the cached files like `node_modules/.cache/wrangler/pages.json` is used for tracking project selections. But whenever I do `npm ci`, the cached files get deleted, thus prompting me to select the project again.

Can you keep the cache at a different location? Like I see there's a directory `.wrangler`. What is that directory for? Can it be used for cache instead?

**Comment by admah** [comment] 2024-02-28 20:06
@harryzcy thank you for submitting this feature request. I believe this should match up with the current Workers experience, which does store temporary files in `.wrangler`. We have a handful of other cache-related items and should be able to fix this as part of that work.

**Comment by penalosa** [comment] 2024-11-08 22:40
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/4299

**Closed by penalosa** 2024-11-08 22:40 UTC
Labels: enhancement, quick win
