### ISSUE TITLE
🐛 BUG: Could not get log, Page Error: Invalid URL string.

### ISSUE THREAD

**Issue by willin** [cloudflare/workers-sdk#4040] opened 2023-09-27 05:14 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

 ⛅️ wrangler 3.10.0

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

<https://domain.js.cool/>  Invalid URL string.

### Please provide a link to a minimal reproduction

https://github.com/willin/domain-remix-refactor

### Please provide any relevant error logs

<img width="884" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/1890238/68ac1935-0dad-465e-8840-4cca080f10b8">

Real-time Log: `Could not establish websocket connection. Begin log stream to try again.`

Wrangler tail:

```bash
❯ npx wrangler pages deployment tail
 ⛅️ wrangler 3.10.0
-------------------
Select a project:
❯ domain-remix-refactor
No deployment specified. Using latest deployment for production environment.
/Users/v0/Sites/domain.willin.wang/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:30947
            throw a;
            ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/v0/Sites/domain.willin.wang/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:108144:17)
    at ClientRequest.<anonymous> (/Users/v0/Sites/domain.willin.wang/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:108044:9)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by penalosa** [comment] 2023-09-29 14:25
Thanks for opening an issue! Unfortunately, I'm not able to access your reproduction repo—could you ensure it's public?

**Comment by willin** [comment] 2023-09-29 14:28
oh... i've deleted...

**Comment by willin** [comment] 2023-09-29 14:29
https://github.com/willin/domain 

<img width="911" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/1890238/2f4c78f7-4950-41b2-aa23-40bf68a438a3">

**Comment by admah** [comment] 2024-02-26 16:21
@willin I'm going to close this as we are not able to reproduce. For more info on how to access logs with Pages Functions, please see https://developers.cloudflare.com/pages/functions/debugging-and-logging/. If you are able to provide a repo and instructions, please open a new issue.

**Closed by admah** 2024-02-26 16:21 UTC
Labels: bug
