### ISSUE TITLE
🐛 BUG: Authentication error [code: 10000]

### ISSUE THREAD

**Issue by mblode** [cloudflare/workers-sdk#2678] opened 2023-02-04 21:24 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.0

### What operating system are you using?

Mac

### Describe the Bug

Locally and on the buildkite CI/CD, I'm getting the following error:
```
wrangler publish --env staging   
Delegating to locally-installed wrangler@2.9.0 over global wrangler@2.9.0...
Run `npx wrangler publish --env staging` to use the local version directly.

 ⛅️ wrangler 2.9.0 
-------------------
Your worker has access to the following bindings:
- Vars:
  - ENVIRONMENT: "staging"
  - MRYUM_URL: "staging.mryum.com"
Total Upload: 415.84 KiB / gzip: 65.54 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/<OBFUSCATED>/workers/scripts/global-staging-qr-proxy) failed.

  Authentication error [code: 10000]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

I have tried to reset the token. I have tried passing in the `CLOUDFLARE_API_TOKEN=<YOUR_API_TOKEN_VALUE>` in the command line. I have tried adding permission "Account Workers Scripts Edit" permission to your token.

Nothing seems to be fixing the issue

<img width="1066" alt="Screenshot 2023-02-03 at 5 00 18 PM (1)" src="https://user-images.githubusercontent.com/7183998/216790114-21ef9634-b084-4123-b8ab-767e2b1edd37.png">
<img width="1135" alt="Screenshot 2023-02-03 at 5 00 45 PM (1)" src="https://user-images.githubusercontent.com/7183998/216790117-d090047f-03d1-4372-8c5a-b9c00c5a3e5e.png">

**Comment by jspspike** [comment] 2023-02-06 16:10
Could you post your wrangler.toml? Sometimes your token and account id specified in your wrangler.toml differ

**Comment by Froxz** [comment] 2023-02-06 20:08
@jspspike I've changed from `CLOUDFLARE_TOKEN` to Global API Key  with Email and it worked, I guess there is an ongoing issue with CF using `CLOUDFLARE_TOKEN` and `CLOUDFLARE_ACCOUNT_ID`, becuase on our end we didn't modify any token/code. Our Bitbucket pipeline just started throwing this error on deployment out of the blue.

**Comment by jspspike** [comment] 2023-02-10 21:51
Just to clarify you're using the global API key through `CLOUDFLARE_API_TOKEN` and specifying account through `CLOUDFLARE_ACCOUNT_ID`?

**Comment by Froxz** [comment] 2023-02-10 22:20
Hi @jspspike 

Initially we were using `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ACCOUNT_ID`, `CLOUDFLARE_API_TOKEN` is the one that you create manually:
![image](https://user-images.githubusercontent.com/3294939/218209384-f5097fca-b7eb-473c-80e8-3e0544af9f38.png)

But few days during CI deployment it just stoped working. So we switched to `CLOUDFLARE_EMAIL` and `CLOUDFLARE_API_KEY` (aka Global API Key)

**Comment by TigranKirakosov** [comment] 2023-02-15 13:25
Hello, @jspspike !

It looks for me this is some sort of an issue with compatibility.

Experiencing quite the same problem as @Froxz does with publishing workers, expect getting `workers.api.error.unauthorized [code: 10023]`
Our stable version of the worker uses `@cloudflare/wrangler` (1.19.6), tried to upgrade to `wrangler 2.9.0~` locally (mac) - results of retrying same publish command leading to the same `unauthorized` error.

We tried to generate a new token with the same permissions but still getting same results, and to switch to `Global API Key` is not an option for us since we're not owning this particular account hence not allowed to have that much permissions which `Global API key` would grant.

Any chances that nowadays permissions for `CLOUDFLARE_API_TOKEN` should be extended in order to proceed with worker publishing action?

**Comment by Froxz** [comment] 2023-02-15 13:42
Hi @TigranKirakosov after some times I've also started getting same error:

![image](https://user-images.githubusercontent.com/3294939/219043563-945c08fb-8a84-419d-8ecd-86ffd0b8199b.png)

**Comment by bhrlabs** [comment] 2023-02-23 06:35
I am seeing the same issue "workers.api.error.unauthorized [code: 10023]". This started happening on a perfectly working github action.

**Comment by jspspike** [comment] 2023-03-06 16:18
@TigranKirakosov Are you using the `Edit Cloudflare Workers` API Token template by any chance? And do you have any other environment variables such as `CLOUDFLARE_ACCOUNT_ID` set? Certain endpoints have changed between wrangler1 and wrangler2 that might be causing this issue

**Comment by jspspike** [comment] 2023-03-06 16:22
@TigranKirakosov Also any bindings with your worker? This error code can be returned if you're attempting to use a feature (like logpush or placement mode) certain special bindings that you don't have permission for

**Comment by advissor** [comment] 2023-03-17 13:42
Did anyone find a solution other than using the Global API key? 

The same stuff happens if you give an "admin worker"  member permission plus an API token with Cloudflare Pages Edit,  and try to deploy a Pages project.

**Comment by jspspike** [comment] 2023-03-20 15:19
I believe that there are likely different issues in this thread which are causing this error. If there is any mismatch with account id and the authenticated user, or if the auth token has an incorrect permission, or if the any special features are being used which the account doesn't have permission.

To help debug this issue further, please provide
* your account id (this okay to provide publicly)
* the account the API token is on
* the specific permissions of the API token
* What environment variable you're using to pass in the API token

Without this information it's difficult to figure out what exactly is causing this error, since this error is simply a generic authentication error if there is _something_ wrong with the token or account id

**Comment by net-tech** [comment] 2023-03-20 23:19
> Hi @jspspike
> 
> Initially we were using `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ACCOUNT_ID`, `CLOUDFLARE_API_TOKEN` is the one that you create manually:
> 
> ![image](https://user-images.githubusercontent.com/3294939/218209384-f5097fca-b7eb-473c-80e8-3e0544af9f38.png)
> 
> But few days ago during CI deployment it just stoped working viat throwing error `Authentication error [code: 10000]`, no changes were done to token permissions, so we switched to `CLOUDFLARE_EMAIL` and `CLOUDFLARE_API_KEY` (aka Global API Key)

How exactly are you specifying those two ENVs? In the command or a different way?

**Comment by agis** [comment] 2023-03-21 15:35
I've created an API token using the "Edit Cloudflare Workers" template, from an account that is a Super Administrator. I've added this as an Environment Secret in GitHub, and named it `CF_API_TOKEN`.

Then, inside the workflow I do this:

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Staging
    environment: staging

    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'subdir'
          environment: 'staging'
```

When the job runs, I get:

```
Using API Token authentication
Notice:  No command was provided, defaulting to 'publish'
Delegating to locally-installed wrangler@2.13.0 over global wrangler@2.13.0...
Run `npx wrangler publish --env staging` to use the local version directly.

 ⛅️ wrangler 2.13.0 
--------------------
✘ [ERROR] ParseError: A request to the Cloudflare API (/accounts/xxx/workers/services/foo-staging) failed.

      at throwFetchError (/github/workspace/node_modules/wrangler/wrangler-dist/cli.js:129716:17)
      at fetchResult (/github/workspace/node_modules/wrangler/wrangler-dist/cli.js:129683:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async publish (/github/workspace/node_modules/wrangler/wrangler-dist/cli.js:150155:31)
      at async Object.publishHandler [as handler] (/github/workspace/node_modules/wrangler/wrangler-dist/cli.js:146347:3) {
    text: 'A request to the Cloudflare API (/accounts/xxx/workers/services/foo-staging) failed.',
    notes: [ { text: 'Authentication error [code: 10000]' } ],
    location: undefined,
    kind: 'error',
    code: 10000
  }


Your worker has access to the following bindings:
- Vars:
  - C: "xxx"
  - A: "xxx"
  - B: "xxx"
Total Upload: 1.63 KiB / gzip: 0.63 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/foo-staging) failed.

  Authentication error [code: 10000]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by agis** [comment] 2023-03-21 19:41
> @agis Are you sure the account for the token should have access to the account you're attempting to publish to? I tried to recreate the issue using `CF_API_TOKEN` from a super admin account and both with the cli directly and github actions I was unable to reproduce the authentication error. The token I used was scoped to my user and scoped to only the specific zone the routes were on like yours.

Yes, I'm sure the account that I used to create the token is a Super Admin account, so it has complete access to the said zone. Do I have to provide something else to the GitHub Action besides the API token?

In any case, I'll attempt to create a token using a different account and see what happens.

**Comment by jspspike** [comment] 2023-03-21 20:34
@agis You shouldn't have to provide anything else to Github Actions other than setting the CF_API_TOKEN actions secret in your repository settings. I would try testing with wrangler manually and creating a token with all accounts and zones and start restricting permissions to see what permission is causing the issue

**Comment by agis** [comment] 2023-03-22 10:50
> @agis You shouldn't have to provide anything else to Github Actions other than setting the CF_API_TOKEN actions secret in your repository settings. I would try testing with wrangler manually and creating a token with all accounts and zones and start restricting permissions to see what permission is causing the issue

How would you pass the CF_API_TOKEN to Wrangler manually? I couldn't find any instructions in the documentation on how to do this.

**Comment by bgroupe** [comment] 2023-03-22 18:03
I can reproduce this locally with `wrangler 2.12.0` when I generate a token with the edit workers template in my account.

**Comment by barabo** [comment] 2023-04-05 03:54
I was seeing a similar error message from wrangler when I tried to deploy a worker that included a `logpush = true` entry.  After I removed that line from `wrangler.toml` I was able to publish new deployments of the worker.

See #2991

**Comment by penalosa** [comment] 2023-04-24 15:15
Hi all! I'm going to close this for now, since it seems like there are various issues being reported in this thread. If you're having an issue with authentication, please open a new issue with the following reproduction steps, and we can investigate:
- A GitHub repository which reproduces the issue, including (if applicable) your CI setup
- The exact token permissions of your API token (available from the Cloudflare API)

**Closed by penalosa** 2023-04-24 15:15 UTC
Labels: bug, awaiting dev response

**Comment by vikiival** [comment] 2023-04-25 12:03
Hey,
I just found this issue while debugging my wrangler action 
https://github.com/kodadot/runners/actions/runs/4796683580/jobs/8532743119

to fix this problem make sure that:

1. You have secrets

<img width="379" alt="Screenshot 2023-04-25 at 14 02 49" src="https://user-images.githubusercontent.com/22471030/234270391-d5699d40-0347-4bea-b261-6777d0b80919.png">

2. `CF_API_TOKEN` to has permission to do particular operation

**Comment by jylin** [comment] 2023-10-29 17:11
I ran into this error as well and after hours of debugging discovered that wrangler caches some account settings into the "node_modules/wrangler/" directory, then it uses those and ignores environment variables!

**Comment by lcampos** [comment] 2024-10-10 20:08
We were running into this issue and after hours of debugging it turns out to be caused by us having `logpush = true` as mentioned above. CF removed our account's access to logpush which added to the confusion of things just starting to fail all of a sudden. It's not an SDK issue but an API issue, we're using CF APIs directly. The real bug is how useless the API error is:

```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10023,
      "message": "workers.api.error.unauthorized"
    }
  ],
  "messages": []
}
```

**Comment by di-sukharev** [comment] 2024-11-01 09:59
# here is the working solution:

```ts
import { v4 as uuidv4 } from "uuid";

interface CloudflareImageUploadResponse {
  result: {
    id: string;
    filename: string;
    metadata: Record<string, any>;
    uploaded: string;
    requireSignedURLs: boolean;
    variants: string[];
  };
  success: boolean;
  errors: any[];
  messages: string[];
}

interface CloudflareImageDeleteResponse {
  result: {} | null;
  success: boolean;
  errors: { code: number; message: string }[];
  messages: string[];
}

interface UploadImageOptions {
  file: Buffer | Blob;
  metadata?: Record<string, any>;
  requireSignedURLs?: boolean;
  filename?: string;
}

async function upload({
  file,
  metadata = {},
  requireSignedURLs = false,
  filename = uuidv4(),
}: UploadImageOptions) {
  const formData = new FormData();

  const blob = file instanceof Blob ? file : new Blob([file]);
  formData.append("file", blob, filename);

  if (Object.keys(metadata).length > 0) {
    formData.append("metadata", JSON.stringify(metadata));
  }

  if (requireSignedURLs) {
    formData.append("requireSignedURLs", String(requireSignedURLs));
  }

  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/images/v1`,
    {
      method: "POST",
      headers: {
        "X-Auth-Key": process.env.CLOUDFLARE_API_TOKEN!,
        "X-Auth-Email": process.env.CLOUDFLARE_EMAIL!,
      },
      body: formData,
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    console.log("Error Response Body:", errorBody);
    throw new Error(
      `Failed to upload image: ${response.statusText} - ${errorBody}`
    );
  }

  const { result }: CloudflareImageUploadResponse = await response.json();

  console.log("UPLOADED_IMAGE_TO_CLOUDFLARE_IMAGES", result);

  const publicUrl = result.variants[0];

  return publicUrl;
}

async function remove(imageId: string): Promise<CloudflareImageDeleteResponse> {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/images/v1/${imageId}`,
    {
      method: "DELETE",
      headers: {
        "X-Auth-Key": process.env.CLOUDFLARE_API_TOKEN!,
        "X-Auth-Email": process.env.CLOUDFLARE_EMAIL!,
      },
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    console.log("Error Response Body:", errorBody);
    throw new Error(
      `Failed to delete image: ${response.statusText} - ${errorBody}`
    );
  }

  const result = await response.json();

  console.log("DELETED_IMAGE_FROM_CLOUDFLARE_IMAGES", result);

  return result;
}

// async function test() {
//   const url = await upload({
//     file: Buffer.from(
//       await fetch(
//         "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fget.pxhere.com%2Fphoto%2Fanimal-pet-kitten-cat-small-mammal-fauna-heal-blue-eye-close-up-nose-whiskers-vertebrate-domestic-lying-tabby-cat-norwegian-forest-cat-ginger-fur-small-to-medium-sized-cats-cat-like-mammal-carnivoran-domestic-short-haired-cat-domestic-long-haired-cat-609263.jpg"
//       ).then((r) => r.arrayBuffer())
//     ),
//   });

//   await remove(url);
// }

// test();

export const CloudflareImages = {
  upload,
  remove,
};
```
