### ISSUE TITLE
🚀 Feature Request: Request for support of the credentials option in Wrangler's fetch function

### ISSUE THREAD

**Issue by minoritea** [cloudflare/workers-sdk#4716] opened 2024-01-08 03:06 UTC
### Describe the solution

Dear Wrangler Team,

I have encountered an issue where it appears that Wrangler currently does not support the `credentials` option in the fetch function. This limitation causes problems in certain frameworks and environments.

For instance, in my case, I receive the following error when executing code compiled into WebAssembly using the Go language:

```
panic: JavaScript error: The 'credentials' field on 'RequestInitializerDict' is not implemented.
 
 -> syscall/js.Value.Call
 ->   syscall/js/js.go:397

    net/http.(*Transport).RoundTrip
      net/http/roundtrip_js.go:128
    net/http.send
      net/http/client.go:260
    net/http.(*Client).send
      net/http/client.go:181
    net/http.(*Client).do
      net/http/client.go:724
    net/http.(*Client).Do
      net/http/client.go:590
    golang.org/x/oauth2/internal.doTokenRoundTrip
      golang.org/x/oauth2@v0.15.0/internal/token.go:256
    golang.org/x/oauth2/internal.RetrieveToken
      golang.org/x/oauth2@v0.15.0/internal/token.go:226
    golang.org/x/oauth2.retrieveToken
      golang.org/x/oauth2@v0.15.0/token.go:167
    golang.org/x/oauth2.(*Config).Exchange
      golang.org/x/oauth2@v0.15.0/oauth2.go:234
...
```

This error arises because the `credentials` option is hardcoded in the net/http standard library of Go when compiled to Javascript:
https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/net/http/roundtrip_js.go;l=82

Unfortunately, this means the issue cannot be rectified from the calling side.

There was a previous bug report related to a similar issue, but regrettably, it was closed by the owner:
#2514 

In that ticket, many users expressed their need for this feature, but it seems to have been left unaddressed for a long time, possibly due to the ticket being closed.

Additionally, it was reported in that ticket that this issue is not only present in WASM but also occurs in JavaScript frameworks like SvelteKit.

Could you please consider supporting the `credentials` option in Wrangler's fetch function? This feature would greatly aid in resolving these issues and enhance the flexibility and usability of Wrangler in various environments.

Thank you for your attention to this matter.

**Comment by penalosa** [comment] 2024-01-08 16:06
The `credentials` option is not supported in the Cloudflare Workers runtime by design. There's an existing issue on `workerd` which tracks allowing this option to be a no-op, and so I'll close this issue in favour of that one, which is the right place to track this: https://github.com/cloudflare/workers-sdk/issues/4716

**Closed by penalosa** 2024-01-08 16:06 UTC
Labels: enhancement

**Comment by gbyesiltas** [comment] 2024-01-15 17:21
> The `credentials` option is not supported in the Cloudflare Workers runtime by design. There's an existing issue on `workerd` which tracks allowing this option to be a no-op, and so I'll close this issue in favour of that one, which is the right place to track this: #4716

@penalosa Are you sure you linked the right ticket? It looks like you linked this one :D
