### ISSUE TITLE
🚀 Feature Request: Inform users why the /functions directory is being ignored

### ISSUE THREAD

**Issue by PierBover** [cloudflare/workers-sdk#2962] opened 2023-03-30 16:31 UTC
### Describe the solution

In most cases when using functions with a pages project, the `/functions` directory is being ignored and there are no warnings or information on why that is.

When using `wrangler pages dev` the `/functions` directory is being ignored and Wrangler simply says:

```
No functions. Shimming...
```

It would be nice if Wrangler said something like:

```
We noticed you're using a /functions directory. Sorry this feature is not supported because of X. Check this URL for more information.
```
The docs also don't explain this behavior and mostly point out how to use the `/functions` directory which is extremely confusing.

In some unrelated section of the [pages docs](https://developers.cloudflare.com/pages/platform/direct-upload/#using-functions), it's explained that the `/functions` directory doesn't work with direct uploads either. That's all the information I could gather after two hours of trying to make this work.

The Cloudflare Dashboard doesn't inform users either when uploading a project with a `/functions` directory. Something like this would have been very helpful:

```
We noticed you're using a /functions directory. Sorry this feature is not supported with direct upload. Check this URL for more information.
```

**Comment by jaswrks** [comment] 2023-09-30 10:30
I think one reason this happens is because Wrangler expects the `./functions` directory to exist in the current working directory where Wrangler is being run from. It doesn't take the directory given at the command line into consideration, which seems like a bug to me.

**Comment by jaswrks** [comment] 2023-09-30 10:32
Problematic lines are here:
https://github.com/cloudflare/workers-sdk/blob/f025b612f5070efcb05a6dc69ecbd717a8b78e8b/packages/wrangler/src/pages/dev.ts#L267-L268
It should be looking for `./functions` to exist in the directory given, not the current working directory.

**Comment by dario-piotrowicz** [comment] 2023-10-01 09:45
One thing that wasn't mentioned here is that `/functions` also gets ignored when using [advanced mode](https://developers.cloudflare.com/pages/platform/functions/advanced-mode/), although that is documented in the advanced mode docs page Wrangler doesn't show any warnings/info regarding that happening (see https://github.com/cloudflare/workers-sdk/issues/3701).

**Comment by CarmenPopoviciu** [comment] 2024-04-25 16:16
hi folks, thank you for raising this issue and providing all the details you did <3

I want to clarify a little what seems to be a misconception here. 

In `wrangler pages dev [directory]`, `[directory]` is the directory of static assets to serve (see relevant [docs](https://developers.cloudflare.com/workers/wrangler/commands/#dev-1)). So think your bundled js/css/ html files, and other static assets such as images, etc. Pages Functions are not considered static assets, which is why we don't look for them in that `[directory]`. This is not a bug, it is expected behaviour.

As @jaswrks correctly pointed out, we always look for the `/functions` directory in the `cwd` where the `pages dev` command is being run. This is by design, and at this moment, we don't support custom paths for the `functions` directory.

The two cases (see [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/pages/dev.ts#L505-L511)) in which we are ignoring Functions are:
1. we did find a `/functions` directory, but something went wrong while attempting to build them
2. as Dario pointed out, we found an `_worker.js` file, which will always take precedence over `/functions`

Given that use case `#2` is documented behaviour
```
When using a _worker.js file, the entire /functions directory is ignored, including its routing and middleware characteristics

**Comment by CarmenPopoviciu** [comment] 2024-05-16 15:50
hi folks,

after looking more thoroughly into this, turns out that we actually do display some Functions specific messages to stdout. Here are the main use cases:

1. we didn't find `/functions` in the root directory. In this case we will [log](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/pages/dev.ts#L522) the following:

<img width="222" alt="Screenshot 2024-05-16 at 17 28 47" src="https://github.com/cloudflare/workers-sdk/assets/4638332/7ee9f42c-5a69-47a1-9bdb-a48b53c3519f">

2. we did find a `/functions` folder but no routes, whic basically means the folder is empty. In this case we will [log](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/pages/dev.ts#L503-L505) the following:

<img width="701" alt="Screenshot 2024-05-16 at 17 14 57" src="https://github.com/cloudflare/workers-sdk/assets/4638332/61f8f05a-f01e-4140-9fbd-c757133c23c5">

3. we found `/functions` but something went wrong while attempting to build the Functions. In this case we will exit with an [error](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/pages/dev.ts#L511):

<img width="394" alt="Screenshot 2024-05-16 at 17 21 09" src="https://github.com/cloudflare/workers-sdk/assets/4638332/1f6829d4-171b-4baa-a183-01a27579de0f">

A similar behaviour is in place while watching the `functions` directory, with the exception that [we don't exit](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/pages/dev.ts#L492-L494) for use case `3`:

<img width="886" alt="Screenshot 2024-05-16 at 17 20 46" src="https://github.com/cloudflare/workers-sdk/assets/4638332/e1104342-72d4-4573-83c4-e04b4eab0490">

I also had a look at our docs and we do have [this section](https://developers.cloudflare.com/pages/get-started/direct-upload/#functions) in place that correctly describes the behaviour for Direct Uploads via Dash. It is possible this clarification was not in place at the time this issue was raised, which would explain the confusion. In fact, I think much has changed since then in both the codebase and our docs since then.

Given all of the above, and my previous comment, I think we are safe to close this one out. 

@PierBover if you have any further remarks, feedback, or still experience issues on the matter, please feel free to re-open or reach out to us! Thank you again for flagging these issues and raising them with us <3

**Closed by CarmenPopoviciu** 2024-05-16 15:50 UTC
Labels: enhancement, pages, wrangler, pages-dev
