### ISSUE TITLE
🐛 BUG: Unable to fetch a worker uploaded with Cloudflare API

### ISSUE THREAD

**Issue by YOD-Solutions** [cloudflare/workers-sdk#3088] opened 2023-04-23 23:58 UTC
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.16.0

### What operating system are you using?

Windows

### Describe the Bug

I have attempted to `init` a dashboard worker that I uploaded with cloudflare API. The worker contains three modules (an index.js and two supporting js files). The worker runs without issues. 

The issue I have is that I can't fetch this worker with wrangler.
The command I used: `wrangler init --from-dash test-worker`
The error message: _Expected only one entry in multipart response_

**Comment by jspspike** [comment] 2023-04-24 15:15
This is a duplicate of [this issue](https://github.com/cloudflare/workers-sdk/issues/2886), work is planned to address this

**Closed by jspspike** 2023-04-24 15:15 UTC
Labels: bug
