### ISSUE TITLE
🐛 BUG: Error during inital deployment

### ISSUE THREAD

**Issue by eneajaho** [cloudflare/workers-sdk#3215] opened 2023-05-15 20:08 UTC
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `C3` are you using?

next

### What operating system are you using?

Mac

### Describe the Bug

Steps followed: 
- npm create cloudflare@next
- Choose Angular
- Add name, styles
- Agree to deploy app
- Get an error as in the screenshot
- Was currently logged in, the error file was empty!!

<img width="1169" alt="CleanShot 2023-05-15 at 22 05 37@2x" src="https://github.com/cloudflare/workers-sdk/assets/25394362/b9640108-f844-4280-9ae9-c0c12bfafe4b">

After trying: ` npm run deploy` again, this time it worked fine.

**Comment by petebacondarwin** [comment] 2023-05-16 08:30
Is this reproducible? I.e. if you follow these steps again now do you get the same error again? I wonder if it was just a transient problem with the backend?
Was there already a Pages project with this name in your account?

**Comment by admah** [comment] 2023-05-19 20:00
I retested this with `npm create cloudflare@latest` and it seems to be working as expected. 

`npm create cloudflare@next` seems to be pinned to `2.0.0` which is not the latest. I'm going to close this now as we do encourage users to use `@latest` in all docs.

**Closed by admah** 2023-05-19 20:00 UTC
Labels: bug, c3
