### ISSUE TITLE
🐛 BUG: C3 should highlight the first menu item

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3931] opened 2023-09-12 15:25 UTC
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.2.0

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

C3 currently always highlights the second item '"Hello world" worker' by default:

<img width="494" alt="Screenshot 2023-09-12 at 8 24 24 AM" src="https://github.com/cloudflare/workers-sdk/assets/216296/419d5e91-d50e-4534-ba08-6e1fbc031174">

This feels unusual and surprising. Let's highlight the first menu item instead.

**Comment by admah** [comment] 2023-09-12 16:13
Duplicate of #3910

**Closed** 2023-10-03 00:52 UTC
Labels: bug, c3
