### ISSUE TITLE
🐛 BUG: Unwanted detection of Node builtins

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/workers-sdk#1475] opened 2022-07-14 12:28 UTC
### What version of `Wrangler` are you using?

0.0.0-d35c69f

### What operating system are you using?

macOS

### Describe the Bug

Wrangler2 attempts to detect the importing of Node built-ins (such as `http` and `fs`), seemingly using RegEx.

This is unwanted behavior in many applications. Packages like `faunadb` are designed for operation in **both** Node.JS and browser (or Worker) environments. They do this via simple checks like checking if `window` exists.

Because of the RegEx validation, the build fails even though the adapter would never import those modules in a Worker and so would otherwise work. The `node_compat` flag can be enabled to work around this, however it adds significant bundle size.

For a good example to reproduce this, try installing and using `faunadb`. Wrangler's behavior of doing this RegEx check breaks all functionality (and all examples of FaunaDB and Workers).

**Comment by isaac-mcfadyen** [comment] 2022-07-14 17:50
I wonder if `esbuild` would tree-shake those packages? Since they're imported dynamically (`import('http')`)? Not sure.

Anyways, yeah I'd definitely be good with downgrading that to a warning, so that the user is aware but it doesn't block builds if they know for sure it's fine.

**Comment by threepointone** [comment] 2022-07-15 09:38
esbuild won't tree shake dynamic imports.

**Comment by Inrixia** [comment] 2022-10-25 07:07
I'm running into this exact issue as well with the only fix being to fork the module and disable the Node.js detection (https://github.com/Inrixia/tweetnacl-js/commit/5a9c25e0045dadcb2be68705f5e841fa2db3715b)...

There REALLY needs to be a way to manually disable throwing on Node.js requires for specific packages or another way to get around this for packages where the developer knows it is a non issue.

**Comment by penalosa** [comment] 2023-09-29 14:14
Closing as duplicate of #4050

**Closed by penalosa** 2023-09-29 14:14 UTC
Labels: bug, node compat
