### ISSUE TITLE
🐛 BUG: Registering worked.dev subdomain fails in "wrangler init"

### ISSUE THREAD

**Issue by akseiya** [cloudflare/workers-sdk#4915] opened 2024-02-03 15:55 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.26.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

PopOS (22 LTS)

### Observed behavior
After authorising Wrangler to nuke my Cloudflare account, the following happens while running `wrangler init` in an interactive shell:
```
 ⛅️ wrangler 3.26.0
-------------------
Total Upload: 0.19 KiB / gzip: 0.16 KiB
▲ [WARNING] You need to register a workers.dev subdomain before publishing to workers.dev


? Would you like to register a workers.dev subdomain now?
🤖 Using fallback value in non-interactive context: yes

✘ [ERROR] This command cannot be run in a non-interactive context
```

### Expected behavior
`wrangler init` finishes successfully, not lying to its dependencies that it's run non-interactively.

### Steps to reproduce
`npx wrangler init NAME` in a clean directory, follow the instructions from [API Tutorial](https://developers.cloudflare.com/d1/tutorials/build-a-comments-api/)

### Please provide any relevant error logs

```
--- 2024-02-03T15:43:57.925Z debug
🪵  Writing logs to "/home/uriel/.config/.wrangler/logs/wrangler-2024-02-03_15-43-57_816.log"
---

--- 2024-02-03T15:43:57.925Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at tryLoadDotEnv (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:124257:72)
    at loadDotEnv (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:124266:12)
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:162342:20
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:131131:16
    at maybeAsyncResult (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:129352:44)
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:131130:14
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:129339:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env'
}
---

--- 2024-02-03T15:43:57.931Z log
 ⛅️ wrangler 3.26.0
-------------------
---

--- 2024-02-03T15:43:58.114Z log
Using npm as package manager.
---

--- 2024-02-03T15:43:58.155Z warn
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare\@2 -- trionficfd1` instead.

  The `init` command will be removed in a future version.


---

--- 2024-02-03T15:43:58.155Z log
Running `npm create cloudflare\@2 -- trionficfd1`...
---

--- 2024-02-03T15:44:48.760Z log

---

--- 2024-02-03T15:44:48.761Z error
✘ [ERROR] Command failed with exit code 1: npm create cloudflare@2 -- trionficfd1


---

--- 2024-02-03T15:44:48.762Z log
If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
---

--- 2024-02-03T15:52:41.899Z debug
Sentry: Capturing exception Error: Command failed with exit code 1: npm create cloudflare@2 -- trionficfd1
---
```

**Comment by petebacondarwin** [comment] 2024-02-05 10:20
Perhaps we should add an option to set whether to create a workers.dev domain to the command line args?

**Comment by penalosa** [comment] 2024-08-22 12:42
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/4263

**Closed by penalosa** 2024-08-22 12:42 UTC
Labels: bug, wrangler, c3
