### ISSUE TITLE
🐛 BUG: wrangler secret:bulk command broke (again) when worker has DO bindings

### ISSUE THREAD

**Issue by izidormaklary** [cloudflare/workers-sdk#5753] opened 2024-05-03 12:49 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.53.1[Wrangler]

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Mac Sonoma 14.1.1

### Observed behavior

```wrangler secret:bulk``` fails when trying to upload secrets to a worker with Durable Object binding. 
Not the first time it occurs: [#4496](https://github.com/cloudflare/workers-sdk/issues/4496). 
Although there is mention of the: 
```
Failed to load .env file ".env.dev": Error: ENOENT: no such file or directory, open '.env.dev'
``` 
log line it seems irrelevant, but the  response to the patch request (originally sanitized from the logs) saying:
```
{
      "code": 10061,
      "message": "Cannot create binding for class DurableObject that is not exported by the script"
}
``` 
indicates that the issue with  durable objects and secret:bulk resurfaced. 

It's important to note that it only occurs with existing workers, there is no issue when uploading secrets to a brand new worker

### Expected behavior
It should upload secrets regardless of durable object bindings.

### Steps to reproduce
- deploy a worker with at least one DO binding
- try to use the ```wrangler secret:bulk``` command on the env you already deployed once

### Please provide any relevant error logs

```
--- 2024-05-03T12:38:19.820Z debug
🪵  Writing logs to " /User/root/.wrangler/logs/wrangler-2024-05-03_12-38-19_721.log"
---

--- 2024-05-03T12:38:19.820Z debug
Failed to load .env file ".env.dev": Error: ENOENT: no such file or directory, open '.env.dev'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at tryLoadDotEnv (/User/root/node_modules/wrangler/wrangler-dist/cli.js:158790:72)
    at loadDotEnv (/User/root/node_modules/wrangler/wrangler-dist/cli.js:158801:12)
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:200143:20
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:165196:16
    at maybeAsyncResult (/User/root/node_modules/wrangler/wrangler-dist/cli.js:163417:44)
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:165195:14
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:163404:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env.dev'
}
---

--- 2024-05-03T12:38:19.821Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at tryLoadDotEnv (/User/root/node_modules/wrangler/wrangler-dist/cli.js:158790:72)
    at loadDotEnv (/User/root/node_modules/wrangler/wrangler-dist/cli.js:158801:50)
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:200143:20
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:165196:16
    at maybeAsyncResult (/User/root/node_modules/wrangler/wrangler-dist/cli.js:163417:44)
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:165195:14
    at /User/root/node_modules/wrangler/wrangler-dist/cli.js:163404:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env'
}
---

--- 2024-05-03T12:38:19.826Z log
 ⛅️ wrangler 3.53.1
[38;2;255;136;0m-------------------[39m
---

--- 2024-05-03T12:38:19.831Z log
🌀 Creating the secrets for the Worker "worker-name-dev" 
---

--- 2024-05-03T12:38:19.831Z debug
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/{accountId}/workers/scripts/worker-name-dev/settings
---

--- 2024-05-03T12:38:19.831Z debug
HEADERS: {
  "User-Agent": "wrangler/3.53.1"
}
---

--- 2024-05-03T12:38:19.831Z debug
INIT: {}
---

--- 2024-05-03T12:38:19.831Z debug
-- END CF API REQUEST
---

--- 2024-05-03T12:38:20.778Z debug
-- START CF API RESPONSE: OK 200
---

--- 2024-05-03T12:38:20.779Z debug
HEADERS: {
 ...
}
---

--- 2024-05-03T12:38:20.779Z debug
RESPONSE: {
  "result": {
    "placement": {},
    "compatibility_date": "2024-04-05",
    "compatibility_flags": [
      "nodejs_compat"
    ],
    "usage_model": "standard",
    "tags": [],
    "tail_consumers": [],
    "logpush": true,
    "bindings": [
      {
        "class_name": "DurableObjectNamespace",
        "name": "DO",
        "namespace_id": "{do_id}",
        "script_name": "do-script-name-dev",
        "type": "durable_object_namespace"
      },
      {
        "name": "RANDOM_SECRET",
        "type": "secret_text"
      },
    ]
  },
  "success": true,
  "errors": [],
  "messages": []
}

---

--- 2024-05-03T12:38:20.779Z debug
-- END CF API RESPONSE
---

--- 2024-05-03T12:38:20.779Z debug
-- START CF API REQUEST: PATCH https://api.cloudflare.com/client/v4/accounts/{accountId}/workers/scripts/worker-name-dev/settings
---

--- 2024-05-03T12:38:20.779Z debug
HEADERS: {
  "User-Agent": "wrangler/3.53.1"
}
---

--- 2024-05-03T12:38:20.779Z debug
INIT: {
  "method": "PATCH",
  "body": {}
}
---

--- 2024-05-03T12:38:20.779Z debug
-- END CF API REQUEST
---

--- 2024-05-03T12:38:21.793Z debug
-- START CF API RESPONSE: Bad Request 400
---

--- 2024-05-03T12:38:21.794Z debug
HEADERS: {
  ...
}
---

--- 2024-05-03T12:38:21.794Z debug
RESPONSE: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10061,
      "message": "Cannot create binding for class DurableObject that is not exported by the script"
    }
  ],
  "messages": []
}

---

--- 2024-05-03T12:38:21.794Z debug
-- END CF API RESPONSE
---

--- 2024-05-03T12:38:21.794Z log

---

--- 2024-05-03T12:38:21.794Z log
Finished processing secrets JSON file:
---

--- 2024-05-03T12:38:21.794Z log
✨ 0 secrets successfully uploaded
---

--- 2024-05-03T12:38:21.795Z log

---

--- 2024-05-03T12:38:21.879Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1m🚨 9 secrets failed to upload[0m


---

--- 2024-05-03T12:38:21.880Z log
[32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose[0m
---
```

**Comment by izidormaklary** [comment] 2024-06-13 10:08
The bug is still there in v3.60.2 and its breaking our pipelines set up for multiple workers :(

**Comment by penalosa** [comment] 2024-06-17 13:41
@matthewdavidrodgers could you have a look at this?

**Comment by lrapoport-cf** [comment] 2024-08-26 15:54
i've connected with @matthewdavidrodgers on this -- there is some higher priority work on his plate at the moment, but this is on his radar to tackle as he becomes available, so assigning to him 👍

**Comment by matthewdavidrodgers** [comment] 2024-10-02 18:22
I'm unable to reproduce this issue.
steps taken:
- created a worker with a durable object and binding via `npx create cloudflare@latest`, following the steps for a worker with a durable object
- deploying that worker
- adding a secret via `npx wrangler@latest secret bulk <my-secret-file>`
- adding another secret via the same method
- updating the first secret via the same method

all commands succeed and the worker operates as expected. feel free to reopen if this issue persists

**Comment by hansottowirtz** [comment] 2024-10-22 07:57
Hi, this issue still exists and I made a minimal repro: https://github.com/hansottowirtz/secrets-bulk-do-binding-repro

Apparently this error only occurs when the DO is in another worker, and bound using `script_name`. Can you reopen the issue?

**Comment by matthewdavidrodgers** [comment] 2024-10-25 22:40
@hansottowirtz ah i see - that is indeed a bug and i can reproduce it. reopening and will get a fix in

**Comment by matthewdavidrodgers** [comment] 2024-10-29 20:35
@hansottowirtz this should be resolved, can you confirm?

**Comment by hansottowirtz** [comment] 2024-10-29 21:27
Great, it seems to work 👍

**Closed** 2024-10-30 16:03 UTC
Labels: blocked, bug, internal
