### ISSUE TITLE
🐛 BUG: multiple custom domains cause api failures

### ISSUE THREAD

**Issue by noroutine** [cloudflare/workers-sdk#6500] opened 2024-08-14 22:18 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.71.0 [wrangler]

### What version of Node are you using?

v20.15.1

### What operating system and version are you using?

Mac Ventura 13.6.7 (22G720)

### Observed behavior
When I have exactly 1 (one) custom domain route in wrangler.toml, it works as expected.
However having two custom domains, causes random and various api failures, but in the end doesn't work

### Expected behavior
Multiple custom domains shall be working i guess

### Steps to reproduce
Ultimately I just play with basic DOs, KV, mails and what else, nothing fancy, code can be found here https://github.com/noroutine/hello-worker

Changing the routes to 
```
routes = [
  { pattern = "hello.0xff.today", custom_domain = true },
  { pattern = "hello2.0xff.today", custom_domain = true }
]
```
causes the failures. Looks like valid toml to me. No fancy env vars or cli args either

### Please provide a link to a minimal reproduction

https://github.com/noroutine/hello-worker

### Please provide any relevant error logs

Examples of three different observed failures:
```
Uploaded hello-worker (4.29 sec)

✘ [ERROR] A request to the Cloudflare API (/accounts/f643dc89eb3361ff6523a744cd37d236/workers/scripts/hello-worker/domains/records) failed.

  workers.api.error.unknown [code: 10013]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

```
Uploaded hello-worker (4.32 sec)

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 6433)

  PUT /accounts/f643dc89eb3361ff6523a744cd37d236/workers/scripts/hello-worker/domains/records -> 504
  Gateway Time-out

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

```
✘ [ERROR] A request to the Cloudflare API (/accounts/f643dc89eb3361ff6523a744cd37d236/workers/scripts/hello-worker/domains/changeset?replace_state=true) failed.

  workers.api.error.unknown [code: 10013]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by noroutine** [comment] 2024-08-14 22:44
UPD: was likely some blip as it started to work okidoki

So this is likely some glitch in the cloudflare matrix related to availability, will just leave this for awareness of matrix maintainers

Feel free to close otherwise

**Comment by tanushree-sharma** [comment] 2024-08-19 16:59
Thanks for reporting this! I suspect this will be hard for us to reproduce given its an issue with the network. 

We'll keep an eye out for similar issues. Going to close this issue out since you're unblocked.

**Closed** 2024-08-19 17:51 UTC
Labels: bug
