### ISSUE TITLE
🐛 BUG: Put Conditional logic reversed

### ISSUE THREAD

**Issue by bstopp** [cloudflare/workers-sdk#6411] opened 2024-08-02 18:02 UTC
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.20240725.0

### What version of Node are you using?

20.13.1

### What operating system and version are you using?

Mac Sonoma 14.6

### Describe the Bug

I'm trying to use the `onlyIf` conditional for putting an object into a bucket using R2 Bindings. However, I'm seeing the reverse of operations than expected.

#### Precondition: Object exists at `key`
Only write if there exists content, but do not create _new_ content.

```
const update = await env.BUCKET.put(key, 'Overwrite Content', { onlyIf: { etagMatches: '*' } });
```
Observed behavior: `update === null`, nothing is written.

#### Precondition: No object exists at `key`
Only write if there is nothing there, do not overwrite.
```
const update = await env.BUCKET.put(key, 'New Content', { onlyIf: { etagDoesNotMatch: '*' } });
```
Observed behavior: `update !== null`, content is overwritten.

#### Precondition: Object exists at `key`
```
const update = await env.BUCKET.put(key, 'Overwrite Content', { onlyIf: { etagMatches: '*' } });
```
Expected  behavior: `update !== null`, an overwrite operation occurs.

#### Precondition: No object exists at `key`
```
const update = await env.BUCKET.put(key, 'New Content', { onlyIf: { etagDoesNotMatch: '*' } });
```
Expected behavior: `update === null`, new content is written to previously non-existing key.

### Steps to reproduce
Please provide the following:
See Gist link.

### Please provide a link to a minimal reproduction

https://gist.github.com/bstopp/0c8f9b29a73840e06eb1e906f457ca91

**Comment by bstopp** [comment] 2024-08-02 18:06
I'm still figuring this out - sorry for any spam.

**Comment by bstopp** [comment] 2024-08-02 18:22
Yes. two of the four conditional logic checks seem to be backwards:

1. Content exists, `ifOnly: etagMatches: '*'` should overwrite content
2. Content exists, `ifOnly: etagDoeNotMatch: '*'` should _not_ overwrite content.

These two are correct:

1. Content does not exist, `ifOnly: etagMatches: '*'` does not create content
2. Content does not exist, `ifOnly: etagDoeNotMatch: '*'` does create content

Seems that  the `'*'` logic check for existing content is reversed.

**Comment by rameardo** [comment] 2024-08-05 06:55
It seems there might be a misunderstanding of how the `onlyIf `preconditions `etagMatches` and `etagDoesNotMatch `work in the context of R2 Bindings with Cloudflare.

Here’s a more detailed explanation of these preconditions and what the expected behavior should be:

- `etagMatches`: This condition will succeed if the ETag of the existing object matches the specified ETag. Using `'*'` is incorrect in this context as it is not a valid ETag. Instead, you should use the actual ETag of the object.
- `etagDoesNotMatch`: This condition will succeed if the ETag of the existing object does not match the specified ETag. Again, using` '*' `as a wildcard does not work here and is likely the cause of the unexpected behavior.

Given your code examples, here is how you can update them to reflect the correct usage of ETags:

### Test 1: Should Overwrite Content if Found (etagMatches)

```javascript
it("should overwrite content if found (etagMatches: actual ETag)", async () => {
  const key = 'index.html';
  // Put initial object
  await env.BUCKET.put(key, 'Original Content', {});

  const current = await env.BUCKET.get(key);
  assert(current);
  const etag = current.httpMetadata.etag;

  const onlyIf = { etagMatches: etag };
  const update = await env.BUCKET.put(key, 'Overwrite Content', { onlyIf }); // Should overwrite if ETag matches.
  assert(update);
});
```

### Test 2: Should Not Create New Content (etagMatches)

```javascript
it("should not create new content (etagMatches: '*')", async () => {
  const key = 'index.html';
  const current = await env.BUCKET.get(key);
  assert.ifError(current); // Ensure the object does not exist.

  const onlyIf = { etagMatches: '*' }; // '*' is not valid, hence will not match any ETag.
  const update = await env.BUCKET.put(key, 'New Content', { onlyIf }); // Should not create new content.
  assert.ifError(update);
});
```

### Test 3: Should Not Overwrite Content if Found (etagDoesNotMatch)

```javascript
it("should not overwrite content if found (etagDoesNotMatch: actual ETag)", async () => {
  const key = 'index.html';
  // Put initial object
  await env.BUCKET.put(key, 'Original Content', {});

  const current = await env.BUCKET.get(key);
  assert(current);
  const etag = current.httpMetadata.etag;

  const onlyIf = { etagDoesNotMatch: etag };
  const update = await env.BUCKET.put(key, 'Overwrite Content', { onlyIf }); // Should not overwrite if ETag matches.
  assert.ifError(update);
});
```

### Test 4: Should Create New Content if Not Found (etagDoesNotMatch)

```javascript
it("should create new content if not found (etagDoesNotMatch: non-existing ETag)", async () => {
  const key = 'index.html';
  const nonExistentEtag = "non-existing-etag";

  const onlyIf = { etagDoesNotMatch: nonExistentEtag };
  const update = await env.BUCKET.put(key, 'New Content', { onlyIf }); // Should create new content.
  assert(update);
});
```

### Summary

1. Use the actual ETag of the object when using `etagMatches `and `etagDoesNotMatch`.
2. Avoid using `'*'`

**Comment by petebacondarwin** [comment] 2024-08-05 13:14
Thanks for the detailed response @rameardo - closing as it looks like this is working as expected.

**Closed by petebacondarwin** 2024-08-05 13:14 UTC
Labels: bug

**Comment by bstopp** [comment] 2024-08-05 13:39
'*' is a vaild etag, as specified in the [Conditional Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests#dealing_with_the_first_upload_of_a_resource) documentation. Specifically in the case of "Do not save if content exists".

However, additionally, assuming that `etagMatches: '*'` is equivalent to the request header `If-Match: *`, then

```
The asterisk is a special value representing any resource. Note that this must match as false if the origin server does not have a current representation for the target resource. 
```

As defined in the [If-Match HTTP docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match#sect1). Then Test Case 2, `onlyIf` should return false - thus no update.

And again with [If-Match HTTP Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match). Then `etagDoesNotMatch: '*'` => `If-None-Match: '*'` => No resource existing does _not_ match `*`.

**Comment by bstopp** [comment] 2024-08-05 13:52
> It seems there might be a misunderstanding of how the onlyIf preconditions etagMatches and etagDoesNotMatch work in the context of R2 Bindings with Cloudflare.

This may be the case. But I'm basing my expectations on the equivalency of `etagMaches => If-Match` and `etagDoesNotMatch => If-None-Match`. 

[The documentation](https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#conditional-operations) specifically references conditional requests, but does not explicitly state that these should not be equivalent. 

I have updated the Gist to include test cases for `If-Match` and `If-None-Match` and, Test Case 4 (new test case 6) does behave as expected. `If-Match` still does not:

```
it ("should not create new content (If-Match: '*')", async () => {
    const key = 'index.html';
    const current = await env.BUCKET.get(key)
    assert.ifError(current);

    const httpHeaders = { 'If-Match': '*' };
    const update = await env.BUCKET.put(key, 'New Content', httpHeaders); // Should have overwritten.
    assert.ifError(update);
  });
 ```
 This should not create new content.

**Comment by bstopp** [comment] 2024-08-05 15:37
Co-worker pointed out my put options may be invalid, so updated it:

```javascript
 it ("should not create new content (If-Match: '*')", async () => {
    const key = 'index.html';
    const current = await env.BUCKET.get(key)
    assert.ifError(current);

    const onlyIf = { 'If-Match': '*' };
    const update = await env.BUCKET.put(key, 'New Content', { onlyIf }); // Should not have created content
    assert.ifError(update);
  });
```

This still creates content.

**Comment by harshal317** [comment] 2024-08-21 14:22
Hey @bstopp thanks for raising this! This seems to be an issue with how the runtime is handling the R2Conditional parameters passed in. I've created an issue in workerd and will get this fixed!
