### ISSUE TITLE
🐛 BUG: `wrangler types` copies actual string from wrangler.toml instead of the type

### ISSUE THREAD

**Issue by shmuli9** [cloudflare/workers-sdk#7273] opened 2024-11-16 21:56 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.86.1 & 3.87.0 [Wrangler]

### What version of Node are you using?

20.15.0

### What operating system and version are you using?

Windows 11

### Observed behavior
When running `wrangler types` the `worker-configuration.d.ts` is wrongly populated with the **actual value** in the wrangler.toml instead of setting up the **types**

### Expected behavior
When running `wrangler types` the `worker-configuration.d.ts` is sets up the **types** to reflect the **types of values** in the wrangler.toml

### Steps to reproduce
Please provide the following:
> wrangler.toml
```toml
[vars]
SERVER_ADDRESS = "http://localhost:3000/event"
BUCKET_NAME ="my-bucket"
CLOUDFLARE_ACCOUNT_ID="XXXXX"
ACCESS_KEY_ID="XXXXX"
```

> worker-configuration.d.ts

```typescript
// Generated by Wrangler by running `wrangler types`

interface Env {
	SERVER_ADDRESS: "http://localhost:3000/event";
	BUCKET_NAME: "my-bucket";
	CLOUDFLARE_ACCOUNT_ID: "XXXXX";
	ACCESS_KEY_ID: "XXXXX";
	SECRET_ACCESS_KEY: string;
	BUCKET: R2Bucket;
	DB: D1Database;
	QUEUE: Queue;
}
```

- Commands used to start your local dev server, including custom env and cli args
`npx wrangler types`

**Comment by shmuli9** [comment] 2024-11-16 22:04
This seems to be related https://github.com/cloudflare/workers-sdk/issues/5082

**Comment by shmuli9** [comment] 2024-11-16 22:05
The only way to fix this seems to be by defining the variables in .dev.vars as well - this causes the types to be properly generated

**Comment by andyjessop** [comment] 2024-11-25 14:55
Thanks very much for reporting! This is a duplicate of https://github.com/cloudflare/workers-sdk/pull/5086 - you can follow over there for progress.

**Closed by andyjessop** 2024-11-25 14:55 UTC
Labels: bug
