### ISSUE TITLE
🐛 BUG: "Got error: multipart: message too large" when deploying for Next JS SSR app

### ISSUE THREAD

**Issue by oscar-iolab** [cloudflare/workers-sdk#3391] opened 2023-06-02 04:24 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Windows

### Describe the Bug

I am having issue with Pages deployment after running next-on-pages (`npx @cloudflare/next-on-pages@1`) to generate static files and _worker.js dir (SSR).
Below is the screenshot of the deployment log from connected Github build.
![Screenshot_2023-06-01_111312](https://github.com/cloudflare/workers-sdk/assets/88138542/ce3eb630-5090-4283-9a3e-4746ebe18704)

As what I can see now is the next-on-pages command success on both locally (my dev machine) and Pages, but seems Pages pops this "multipart: message too large" error when I try to deploy the app.

I tried both deployment methods, Github (build log as in above screenshot) and `npx wrangler pages deploy .vercel/output/static` (files upload success), but both failed when publishing on Pages.

More info:
Framework: Next JS v13.3.4
Next-on-pages: v1.0.1
SSR pages: 20+
_worker.js dir (unzipped) size: 14MB+

**Comment by Piotrovskyi** [comment] 2023-06-04 19:29
Have same issue

**Comment by TimothyKrell** [comment] 2023-06-08 13:49
I'm seeing the same issue as well. I'm still trying to figure out why. I know that simplifying a server action file allows it to deploy, but the file was pretty simple as it was. I'm currently trying to narrow down what bit of code causes the `multipart: message too large` error.

  
![image](https://github.com/cloudflare/workers-sdk/assets/1585669/7123878f-d5d3-4eb6-9476-feed8f40b99e)

**Comment by TimothyKrell** [comment] 2023-06-08 14:05
I narrowed this down to using the `qs` library. I don't think it would be that much of a problem, though, right? It doesn't seem large enough to cause an issue: https://bundlephobia.com/package/qs@6.11.2

**Comment by elbaro** [comment] 2023-06-27 16:10
We experience this when there are a lot of files rather than large files.

Some complex library can create a lot of chunks. We have more than 1,000 chunks. The total file size didn't exceed the worker limit, but the multipart encoding and overhead from the number of files probably hit the limit.

```
00:45:45.903 | - __next-on-pages-dist__/chunks/92941.js (esm)
00:45:45.904 | - __next-on-pages-dist__/chunks/92961.js (esm)
00:45:45.904 | - __next-on-pages-dist__/chunks/93090.js (esm)
00:45:45.904 | - __next-on-pages-dist__/chunks/93157.js (esm)
00:45:45.904 | - __next-on-pages-dist__/chunks/93192.js (esm)
..
```

**Comment by GregBrimble** [comment] 2023-06-27 17:25
Looks related: https://github.com/golang/go/commit/1e43cfa15b4b618812e85c00c9e92c2615b324c8

cc @dario-piotrowicz

**Comment by dario-piotrowicz** [comment] 2023-07-18 17:51
I made some progress here: https://github.com/cloudflare/next-on-pages/pull/349

but unfortunately my changes there don't seem to reduce the number of files enough to solve the issue, I'll try to reduce the number of files further (or @james-elicx which I think had some ideas regarding this)

**Comment by elbaro** [comment] 2023-07-18 20:13
If the issue is really the number of files, worker should be able to upload many files, not uploading less files. I don't see any documented limit on the number of files.

Can you just zip, upload and unzip?

**Comment by dario-piotrowicz** [comment] 2023-07-25 20:33
Hopefully this should be fixed, @oscar-iolab, @Piotrovskyi, @TimothyKrell and @elbaro could you try again with the latest next-on-pages release ([1.4.0](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.4.0)) and let me know if things work now? 🙏

**Comment by dario-piotrowicz** [comment] 2023-07-26 13:33
I suspect that this issue is not yet fixed, so I'm reopening it as I am looking into it further

**Comment by dario-piotrowicz** [comment] 2023-07-27 17:09
I'm having some trouble reproducing this on my side, I'll keep looking into this, but anyways if anyone could potentially share their source code that would be really helpful 🙂 🙏

**Comment by elbaro** [comment] 2023-08-07 12:35
@dario-piotrowicz next-on-pages v1.5 reduced 1,000 files to 100 files and the deploy succeeded.

**Comment by elbaro** [comment] 2023-08-07 12:46
However the issue remains. Our app will grow over time and we don't know when it will break - 200 files? 500?
Since the doc says the limit of 20,000 files, it should be supported.

> the limit seems to be dependent on an external dependency

In the golang link above, it says you can set `GODEBUG=multipartmaxheaders=<values>` or `GODEBUG=multipartmaxparts=<value>`. I think it is reasonable to limit a single request size and the correct solution is CF splitting the request into smaller ones or archive to avoid multipart header overhead.

**Comment by dario-piotrowicz** [comment] 2023-08-07 18:48
@elbaro thanks for confirming that not next-on-pages works for you 🙏 

Regarding the issue, yes we ideally should find a way to properly fix it

I did eventually manage to make a reproduction of it: https://github.com/dario-piotrowicz/cf-workers-and-pages-bugs-reproductions/tree/master/pages/workerjs-dir-message-too-long

Hopefully we can address this in wrangler soon 🙂

**Comment by dario-piotrowicz** [comment] 2023-08-08 16:49
@elbaro we've looked into this and we're looking into increasing the limits you mentioned in your comment 👍

(Splitting the request into smaller requests would drastically increase the complexity of our implementation and it doesn't look necessary so we've opted not to go that route)

(PS: the pages 20000 limit is for assets, but here we indicate js module files, so it's not the same thing, although I appreciate that the docs wording doesn't make that too clear)

**Comment by dario-piotrowicz** [comment] 2023-08-15 20:50
I'm closing this issue since we've drastically decreased the amount of files generated by Next.js adaptor and also significantly increased the amount of files deployable (5000 to be precise for the time being, which should be plenty for even very large applications, if this turns out not to be enough we can always increase it further later)

So it should be very hard to hit this limit now

@oscar-iolab, @Piotrovskyi, @TimothyKrell and @elbaro if you still encounter this issue please let me know 🙂

**Closed by dario-piotrowicz** 2023-08-15 20:50 UTC
Labels: pages, bug
