### ISSUE TITLE
🐛 BUG: Workerd/Vitest - Handler does not export a fetch() function

### ISSUE THREAD

**Issue by lewsmith** [cloudflare/workers-sdk#5726] opened 2024-04-30 00:48 UTC
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.52.0 [Wrangler]

### What version of Node are you using?

18

### What operating system and version are you using?

Linux

### Observed behavior
Within the last 5 days my vitest integration tests have started failing with the error `Handler does not export a fetch() function` but with no changes to my code. I will investigate more, but currently on hols. 

I just re-ran a previously successful GH action that now fails with the following:

```bash
npx vitest run -c ./integration/vitest.config.ts

 RUN  v1.3.0 /home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker

CI environment detected, skipping worker build. Will use previously built worker.
[vpw:inf] Starting single runtime for integration/vitest.config.ts...
workerd/io/worker.c++:1874: 
info: uncaught exception; source = Uncaught (in promise); stack = Error: Handler does not export a fetch() function.
    at Object.fetch (home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/vitest-pool-workers/dist/worker/index.mjs:337:13)
workerd/io/io-context.c++:355: 

info: uncaught exception; exception = workerd/jsg/_virtual_includes/jsg/workerd/jsg/value.h:1333: failed: jsg.Error: Handler does not export a fetch() function.

stack: 
/home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/workerd-linux-64/bin/workerd@351c970 
/home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/workerd-linux-64/bin/workerd@351d6e5 
/home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5583fff 
/home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/workerd-linux-64/bin/workerd@33a[42](https://github.com/lewsmith/rust-cloudflare-axum-worker/actions/runs/8887108368/job/24401827771#step:6:43)50 
/home/runner/work/rust-cloudflare-axum-worker/rust-cloudflare-axum-worker/node_modules/@cloudflare/workerd-linux-64/bin/workerd@33a4990

stdout | integration/tests/request.test.ts > dispatches fetch event

Setting up panic hook...

 ❯ integration/tests/request.test.ts  (1 test | 1 failed) 124ms
   ❯ integration/tests/request.test.ts > dispatches fetch event
     → Handler does not export a fetch() function.

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  integration/tests/request.test.ts > dispatches fetch event
Error: Handler does not export a fetch() function.
 ❯ integration/tests/request.test.ts:5:17
      3| 
      4| it('dispatches fetch event', async () => {
      5|   const hello = await SELF.fetch('https://fake.host/');
       |                 ^
      6|   expect(hello.status).toBe(200);
      7|   expect(await hello.text()).toContain('👋 Hello from the Worker');

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { remote: true }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


Error: Error: Handler does not export a fetch() function.
 ❯ integration/tests/request.test.ts:5:17
```

### Expected behavior
Expect the tests to succeed as they previously did.

### Packages
```json
"@cloudflare/vitest-pool-workers": "^0.2.3",
"@cloudflare/workers-types": "^4.20240423.0",
"typescript": "^5.4.5",
"vitest": "1.3.0",
"wrangler": "^3.52.0"
```

### Example Failing Code
```ts
import { SELF } from 'cloudflare:test';
import { expect, it } from 'vitest';

it('dispatches fetch event', async () => {
  const hello = await SELF.fetch('https://fake.host/');
  expect(hello.status).toBe(200);
  expect(await hello.text()).toContain('👋 Hello from the Worker');
});
```

**Comment by penalosa** [comment] 2024-05-02 09:54
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by lewsmith** [comment] 2024-05-02 23:41
> Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

Certainly @penalosa!

Here's a repo - https://github.com/lewsmith/cloudflare-rs-vitest
Here's the fail - https://github.com/lewsmith/cloudflare-rs-vitest/actions/runs/8931843147

This is the basic rust template `cargo generate cloudflare/workers-rs` (was unsure where to put this issue TBH), with vitest added on top, following the ['Basic tests using SELF' recipe](https://github.com/cloudflare/workers-sdk/tree/main/fixtures/vitest-pool-workers-examples/basics-unit-integration-self)

It was 100% working a few days ago...

**Comment by lewsmith** [comment] 2024-05-03 00:07
@penalosa 

After a quick debug, I can see that after switching my `command` in the `wrangler.toml` from 
```toml
command = "cargo install worker-build && worker-build --release"
``` 
to 
```toml
command = "cargo install worker-build@0.0.10 && worker-build --release"
``` 
everything works.

Working branch - https://github.com/lewsmith/cloudflare-rs-vitest/tree/worker-build-v0.0.10
Successful test - https://github.com/lewsmith/cloudflare-rs-vitest/actions/runs/8932046993

The worker-build crate was released 4 days ago which is roughly when the issue started. Obviously, without the version cargo install will use v0.1.0. 

So the issue is definitely in the worker-build crate. Will continue to debug, but it's now apparent I raised this bug in the wrong repo! Should I leave or close and re-raise in the workers-rs repo?

**Comment by lewsmith** [comment] 2024-05-03 02:36
@penalosa , think I've worked it all out..

The change here has converted the default export from an object to a class: https://github.com/cloudflare/workers-rs/commit/f3eb1eb535d9b248615db531490b77629338a439#diff-8d6c7becdc081deeddd5cbbff42bffccd48ab491f413299edf0977832aa53be4L9

However, in vitest-pool-workers, there's some checks that don't seem to have been updated to work with the above change:

https://github.com/cloudflare/workers-sdk/blob/main/packages/vitest-pool-workers/src/worker/index.ts#L266

I think something like this is needed, but without some further testing/thinking I'm unsure as to the typings and any side affects:

```ts
const defaultExport =
  typeof mainModule === "object" &&
  mainModule !== null &&
  "default" in mainModule &&
  new mainModule.default(ctx, env); // Here
```

The above does work - my tests pass, but it's just a quick and dirty hack.  I will put together a cleaner fix as pull request once I return from my holiday, now I know exactly where the issue is.

**Comment by kflansburg** [comment] 2024-05-04 11:25
@penalosa I think that `vitest-pool-workers` should be updated to support the new `WorkerEntrypoint` pattern. Even if we explicitly don't support RPC here, I imagine this pattern will become more widely used.

**Comment by emily-shen** [comment] 2024-10-09 13:31
Closing since we have added support for WorkerEntrypoint in vitest-pool-workers now - I've tested the repro with a recent version and the error seems resolved. Please let us know if you have any further issues though :)

**Closed by emily-shen** 2024-10-09 13:31 UTC
Labels: bug, vitest
