### ISSUE TITLE
🚀 Feature Request: Miniflare Log Pipe

### ISSUE THREAD

**Issue by bruceharrison1984** [cloudflare/workers-sdk#5692] opened 2024-04-23 15:28 UTC
### Describe the solution

It'd be nice if Miniflare `UnstableDevWorker` offered a way to pipe it's log output into another process (ie Vite). 

Currently the only option is to allow the server to write logs to the console, where they frequently get managled in the output of other processes.

**Comment by penalosa** [comment] 2024-06-17 13:08
This should be addressed by the integration stage of the [`WaaL`](https://github.com/cloudflare/workers-sdk/milestone/11) milestone

**Comment by penalosa** [comment] 2024-11-04 17:56
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/2894, where we'll address this

**Closed by penalosa** 2024-11-04 17:56 UTC
Labels: enhancement
