### ISSUE TITLE
Deprecated dependencies in Wrangler v3.91.0 causing warnings

### ISSUE THREAD

**Issue by princegearydymosco** [cloudflare/workers-sdk#7373] opened 2024-11-27 16:37 UTC
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.91.0

### What operating system and version are you using?

Windows 11

### Describe the Bug

Describe the bug
When installing wrangler@3.91.0, several warnings about deprecated dependencies are observed:
- rollup-plugin-inject: Deprecated, no longer maintained. Recommendation: use @rollup/plugin-inject.
- sourcemap-codec: Deprecated. Recommendation: use @jridgewell/sourcemap-codec.

These warnings indicate that wrangler relies on outdated packages, which could lead to long-term maintenance and compatibility issues.

Observed behavior
During the installation of wrangler@3.91.0 using npm install, the following warnings are generated:

npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead.

Expected behavior
The installation of wrangler should not produce warnings about deprecated dependencies. All dependencies should be actively maintained and supported.

![image](https://github.com/user-attachments/assets/1159e18d-afaf-433a-8b8e-b31592c86d9e)

**Comment by penalosa** [comment] 2024-11-28 13:43
This is a duplicate of https://github.com/cloudflare/workers-sdk/issues/6189, and will be resolved in #7334. To note, these dependencies are only used if you turn on the `node_compat` flag in your Wrangler config file

**Closed by penalosa** 2024-11-28 13:43 UTC
Labels: bug
