### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by AAlber** [cloudflare/workers-sdk#4784] opened 2024-01-19 09:11 UTC
### Which Cloudflare product(s) does this pertain to?

R2, Workers for Platforms, Wrangler core

### What version(s) of the tool(s) are you using?

3.20.0

### What version of Node are you using?

20.9.0

### What operating system are you using?

Mac

### Describe the Bug

Hello,
I am trying to deploy my worker using wrangler and it keeps crashing and giving a gateway timeout. 
Please help resolve this issue.

Thank you,
Alex

### Please provide any relevant error logs

"% npx wrangler deploy
 ⛅️ wrangler 3.20.0 (update available 3.23.0)
-------------------------------------------------------

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  
  <!--[if I... (length = 6434)

  GET /accounts/d7cea93cb0b0fa7c6f98e336cecb5dec/workers/services/fuxam-r2-worker -> 504 Gateway
  Time-out
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose"
  I'm connected to the internet and keep getting this bug. Please resolve it ASAP

**Comment by philippviereck** [comment] 2024-01-19 09:17
Not sure if a github issue is the right place to open this as I don't think it's a issue with the SDK, but it seems as if cloudflare is having some issues with their API because I have the same issue when trying to deploy a worker. Although it's not always the same path that timesout on me.

**Comment by admah** [comment] 2024-01-22 17:09
Is this still an issue for you @AAlber?

**Comment by admah** [comment] 2024-01-24 18:34
I'm going to close this issue for now. Please reopen and provide a minimal reproduction if it continues to be a problem

**Closed by admah** 2024-01-24 18:34 UTC
Labels: bug
