### ISSUE TITLE
:no_entry_sign:  BUG: [ssr] Error: The 'mode' field on 'RequestInitializerDict' is not implemented.

### ISSUE THREAD

**Issue by wpplumber** [cloudflare/workers-sdk#4700] opened 2024-01-04 12:28 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.22.2

### What version of Node are you using?

v19.0.0

### What operating system are you using?

Linux

### Describe the Bug

I'm using Astro build project using SSR and it works ok locally but when I use wrangler to prepare for Cloudflare it gives the following error:

`The 'credentials' field on 'RequestInitializerDict' is not implemented.`

The important is the issue is when using `swell-js` it gives this error but when using `fetch` and a public endpoint it works both locally and in wrangler.

### Please provide any relevant error logs

>       at checkURL
>   (file:///home/wrangler/tmp/bundle-ngYvmD/checked-fetch.js:9:9)
>       at Object.apply
>   (file:///home/.wrangler/tmp/bundle-ngYvmD/checked-fetch.js:27:3)
>       at e (file:///home/dist/_worker.js:49:109124)
>       at Object.list (file:///home/dist/_worker.js:49:41677)
>       at e (file:///home/dist/_worker.js:57:1116)
>       at index (file:///home/dist/_worker.js:9:222)
>       at im (file:///home/zdist/_worker.js:23:284)
>       at P_ (file:///home/dist/_worker.js:22:119)
>       at am (file:///home/dist/_worker.js:38:2579)
>       at xx (file:///home/dist/_worker.js:108:15205) (x6)
> 
> 
> [wrangler:inf] GET / 500 Internal Server Error (32ms)
>

**Comment by penalosa** [comment] 2024-01-08 16:25
The `credentials` option is not supported in the Cloudflare Workers runtime by design. There's an existing issue on `workerd` which tracks allowing this option to be a no-op, and so I'll close this issue in favour of that one, which is the right place to track this: https://github.com/cloudflare/workers-sdk/issues/4716

**Closed by penalosa** 2024-01-08 16:25 UTC
Labels: bug
