### ISSUE TITLE
R

### ISSUE THREAD

**Issue by jesushi27** [cloudflare/workers-sdk#5372] opened 2024-03-25 18:45 UTC
https://github.com/boywithkeyboard/warp/tree/main

**Comment by admah** [comment] 2024-03-26 22:01
@jesushi27 I'm going to close this issue as we can't action on the link above. If you need to reopen, please tell us what the issue is that you're seeing, with a way for us to reproduce. Thanks!

**Closed by admah** 2024-03-26 22:01 UTC
