### ISSUE TITLE
🚀 Feature Request: c3 should list  framework versions in the menu

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3930] opened 2023-09-12 15:21 UTC
### Describe the solution

Currently we list only names, but it's unclear to users what they'll get:
<img width="494" alt="Screenshot 2023-09-12 at 8 20 27 AM" src="https://github.com/cloudflare/workers-sdk/assets/216296/db6ff3d0-0586-40b7-acad-8e225bf3e331">

Could we please add a major version number after each item in the menu?

**Comment by admah** [comment] 2023-09-12 17:46
Duplicate of #3908

**Comment by jculvey** [comment] 2023-10-25 05:13
After looking into this and brainstorming ways of supporting it, I don’t think we can support this at the moment. There’s a number of issues that make this challenging to tackle.

The biggest problem is that we version framework scaffolding tools (like `create-react-app`), not the frameworks themselves. 

In many cases, these tools don’t even version the frameworks. Here’s a few examples of package.json files where a framework version is nowhere to be found:

- [solid](https://github.com/solidjs/solid-start/blob/main/packages/create-solid/package.json)
- [next](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/package.json)
- [remix](https://github.com/remix-run/remix/blob/main/packages/create-remix/package.json)

Furthermore, most frameworks don’t have a coordinated matching version with their scaffolding tools. For example, the latest version of [create-svelte](https://www.npmjs.com/package/create-svelte) as of this writing is `5.1.1`, where the latest version of [svelte](https://www.npmjs.com/package/svelte) is `4.2.2`. 

Most of these tools actually pull from [template repos](https://github.com/solidjs/solid-start/tree/main/examples) to copy their initial files. These templates will have a package.json that actually pins the version of the framework.

Because of these factors, it’s quite difficult to determine the mapping between the version of frameworks and their scaffolding tools. 

We considered inspecting the artifacts of our e2e runs on dependabot PRs, inspecting the resultant package.json for the version and committing it along with the version bump. Even this won’t quite give us a correct result however, since the framework version isn’t really deterministic for multiple runs of the same scaffolding tool. This is because many of them allow you to select or specify a template, which may have different framework version. Not only that, but these templates are often pulled directly from github as raw files, not installed as a dependency via npm, meaning they aren’t actually versioned by the scaffolding tools and can change at any time.

Without a viable strategy to handle this, it seems as if it’s better to not tell users a version than to tell them a version that’s possibly incorrect.

**Closed by jculvey** 2023-10-25 05:13 UTC
Labels: enhancement, c3
