### ISSUE TITLE
🐛 BUG: wrangler pages dev doesn't support service bindings or the `--service` argument

### ISSUE THREAD

**Issue by trevhunter** [cloudflare/workers-sdk#3436] opened 2023-06-12 16:04 UTC
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

WSL

### Describe the Bug

According to [documentation for wrangler pages dev](https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-service-binding-locally), I should be able to run pages locally using wrangler and have it set up service bindings. However, wrangler 3.1.0 does not support the `--service` argument that is described in the documentation. 

Steps:
1. Set up a simple pages project.
2. Run `wrangler pages dev /. --service=SVC=SERVICE_NAME`

*Expected:* Wrangler will set up the service binding as expected and documented, much like KV, R2, D1, DO and env vars. 
*Actual:* Wrangler returns an error `[ERROR] Unknown argument: service`

**Comment by trevhunter** [comment] 2023-06-12 16:05
Further community thread at: https://community.cloudflare.com/t/using-service-binding-to-call-a-worker-from-a-pages-function-locally/489343/2

**Comment by CarmenPopoviciu** [comment] 2024-04-25 13:49
hi folks, thank you for raising this issue.

I have tested running `wrangler pages dev [directory] --service=SVC=SERVICE_NAME` and everything works as expected 👇 
<img width="441" alt="Screenshot 2024-04-25 at 14 46 20" src="https://github.com/cloudflare/workers-sdk/assets/4638332/3b8df1af-c2bf-4aaf-aca5-ba2be44aae7e">

I am running latest wrangler version `3.52.0`. 

We have recently added support for `wrangler.toml` in Pages, so service bindings can now be specified via the configuration file as well. Please keep in mind that support for service bindings in local mode is experimental and may change.

Closing this issue as can't reproduce. If you are still experiencing issues, pls feel to re-open and provide us with detailed repro steps 🙏

**Closed by CarmenPopoviciu** 2024-04-25 13:49 UTC
Labels: pages, bug
