### ISSUE TITLE
🚀 Feature Request: Generate more general types for wrangler types

### ISSUE THREAD

**Issue by stevezhu** [cloudflare/workers-sdk#6303] opened 2024-07-21 13:12 UTC
### Describe the solution

# Problem
Wrangler generates the exact type for environment variables defined. For example, the following `wrangler.toml`:
```toml
[vars]
AUTH_DOMAIN = "https://www.example.com"
```
Generates this type:
```typescript
interface Env {
  AUTH_DOMAIN: "https://www.example.com";
}
```
It should be assumed that environment variables are able to change, otherwise they would just be defined as constants instead. This kind of type generation seems to make more sense:
```diff
 interface Env {
-  AUTH_DOMAIN: "https://www.example.com";
+  AUTH_DOMAIN: string;
 }
```

I don't think it's correct to assume that the values defined in `wrangler.toml` are the only possible values for the environment variables.

## Secrets

Another issue is that secrets are only defined inside `.dev.vars` which isn't checked into version control. This creates issues for CI where the type generation isn't idemponent because `.dev.vars` doesn't exist in the CI environment. Changing the type generation to be more general will allow placeholder values to be defined in `wrangler.toml` for types.

eg.
```toml
[vars]
AUTH_DOMAIN = "https://www.example.com"
AUTH_SECRET = "<secret>"
```
```typescript
interface Env {
  AUTH_DOMAIN: string;
  AUTH_SECRET: string;
}
```

## Different environments

This would also solve this relevant issue: https://github.com/cloudflare/workers-sdk/issues/5850

# Suggestion
Reference:
https://github.com/cloudflare/workers-sdk/blob/5462ead9207459e7547ba571157159c8618d3583/packages/wrangler/src/type-generation.ts#L157-L173

It makes more sense to me for the implementation of `constructTypes` to be something more like this
```diff
 export function constructType(
   key: string,
   value: string | number | boolean,
   useRawVal = true
 ) {
   const typeKey = constructTypeKey(key);
-  if (typeof value === "string") {
-    if (useRawVal) {
-      return `${typeKey}: ${value};`;
-    }
-    return `${typeKey}: ${JSON.stringify(value)};`;
-  }
-  if (typeof value === "number" || typeof value === "boolean") {
-    return `${typeKey}: ${value};`;
-  }
+  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
+    if (useRawVal) {
+      return `${typeKey}: ${value};`;
+    }
+    return `${typeKey}: ${typeof value};`;
+  }
   return `${typeKey}: unknown;`;
 }
```

Changing the implementation or adding an extra flag to `wrangler types` to enable this behavior would be greatly appreciated.

**Comment by stevezhu** [comment] 2024-07-21 20:41
Realized a related PR exists here: https://github.com/cloudflare/workers-sdk/pull/5086
And a comment on the same suggestion as this issue: https://github.com/cloudflare/workers-sdk/pull/5086#issuecomment-1964765288

**Comment by andyjessop** [comment] 2024-08-07 13:21
I'll close this as it's a duplicate of #5086, which is implementing the same suggestion.

**Closed by andyjessop** 2024-08-07 13:21 UTC
Labels: enhancement
