### ISSUE TITLE
🐛 BUG: Dev tools doesn't open, Windows 11 Edge

### ISSUE THREAD

**Issue by dmeagor** [cloudflare/workers-sdk#4949] opened 2024-02-07 20:02 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.27.0

### What version of Node are you using?

v20.11.0

### What operating system and version are you using?

Windows 11, Edge latest

### Describe the Bug

Without chrome installed (just MS Edge) hitting d does absolutely nothing. All other keys work as expected including b to open MS Edge browser.

### Observed behavior
Nothing, nada, the absence of something

### Expected behavior
Dev tools debugger should open

### Steps to reproduce
>wrangler dev
press d

**Comment by penalosa** [comment] 2024-08-22 12:30
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/1445

**Closed by penalosa** 2024-08-22 12:30 UTC
Labels: bug
