### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by AAlex-11** [cloudflare/workers-sdk#5336] opened 2024-03-21 10:22 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.34.2

### What version of Node are you using?

v18.17.0

### What operating system and version are you using?

Windows 11

### Steps to reproduce
npx wrangler init --from-dash my-telegram-bot

 The `init --from-dash` command is no longer supported. Please use `npm create cloudflare@2.5.0 my-telegram-bot -- --existing-script justrelax10-telegram-bot` instead.

npm create cloudflare@2.5.0 justrelax10-telegram-bot -- --existing-script my-telegram-bot

Too many positional arguments provided

### 
--- 2024-03-21T10:23:10.267Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at tryLoadDotEnv (E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:124605:72)
    at loadDotEnv (E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:124614:12)
    at E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:164339:20
    at E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:131658:16
    at maybeAsyncResult (E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:129879:44)
    at E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:131657:14
    at E:\Angular\TelegramBot\node_modules\wrangler\wrangler-dist\cli.js:129866:22
    at Array.reduce (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}

**Comment by penalosa** [comment] 2024-07-08 13:41
This seems to have been fixed in the last few months—I can't reproduce this. I'll close it out for now, but feel free to open a new issue with more details if you're still running into problems.

**Closed by penalosa** 2024-07-08 13:41 UTC
Labels: bug, c3
