### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by strawbs1989** [cloudflare/workers-sdk#4766] opened 2024-01-18 00:11 UTC
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

C3

### What operating system are you using?

windows

### Describe the Bug

i was trying to upload files and still getting 

```
00:05:31.817 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
-- | --
00:05:31.817 |  
00:05:31.817 | phpmailer/icudt72.dll is 31.3 MB in size
```

but thing is i have removed phpmailer from system and git 
is there anyway this issue could be sorted so i can keep uploading files please 

### Please provide any relevant error logs

```
00:05:31.817 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
-- | --
00:05:31.817 |  
00:05:31.817 | phpmailer/icudt72.dll is 31.3 MB in size
00:05:31.817 |  
00:05:31.817 |  
00:05:31.817 | If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
00:05:31.830 | Failed: upload process exited with code: 1
00:05:32.690 | Failed: error uploading static assets. Check the logs above for more information. If this continues for an unknown reason, contact support: https://cfl.re/3WgEyrH
00:05:32.690 | Error: Failed to publish assets. For support, join our Discord (https://discord.gg/cloudflaredev) or create a ticket and reference the deployment ID: 74aeb280-a4d7-4c36-adc5-926d1f218057

```

**Comment by penalosa** [comment] 2024-01-18 15:13
This is expected for sites deployed to Cloudflare Pages. As the error message says:

> Pages only supports files up to 26.2 MB in size

See https://developers.cloudflare.com/pages/platform/limits/#file-size for more details

In your specific case, it looks like the file `phpmailer/icudt72.dll` is being detected by Pages, which is larger than the upload size limit. If you delete that file, Pages should be able to properly upload your site. I'm going to close this issue for now, but if that doesn't work feel free to open a new issue with more details and a link to a GitHub repository with a reproduction so we can investigate further.

**Closed by penalosa** 2024-01-18 15:13 UTC
Labels: bug
