### ISSUE TITLE
🐛 BUG: wrangler dev --local doesn't inject process.env variables

### ISSUE THREAD

**Issue by aivLuk** [cloudflare/workers-sdk#2865] opened 2023-03-07 14:52 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Mac

### Describe the Bug

I'm using some env variables in the worker code from .env file. However running `wrangler dev --local --live-reload --node-compat` gives an empty `process.env` object. If I remove --local flag it works. However without --local I'm not able to use --live-reload function.

I'm building with webpack and injecting env variables like so:
`plugins: [new DefinePlugin({ 'process.env': JSON.stringify(dotenv.config().parsed) })],`

Same issue appears when running `wrangler publish`.

**Comment by penalosa** [comment] 2023-03-13 08:34
Thanks for reporting this! Would you be able to share your `wrangler.toml` file, as well as a reproduction repository, if possible? Thanks!

**Comment by aivLuk** [comment] 2023-03-16 06:37
Can't really share the repo, it's private but `wrangler.toml` looks like this:

`name = "image-conversion-worker"
main = "src/index.ts"
compatibility_date = "2023-02-28"
route = "example.com/v1"

[build]
command = "yarn && yarn build"

[env.staging]
name = "image-conversion-worker-staging"
route = "stage.example.com/v1"

[env.production]
name = "image-conversion-worker"
route = "example.com/v1"`

Also have .env file with env variables.

Running with `wrangler dev --local --live-reload --node-compat` gives {} for `process.env` anywhere in the worker. Removing `--local` flag everything works and env variables get picked up by `process.env.VARIABLE`.

And same thing when I do `wrangler publish --env \"${DEPLOY_ENV}\" --node-compat`. It doesn't pick up env variables

**Comment by penalosa** [comment] 2023-03-16 08:55
It looks like your `main` entry point is set to `src/index.ts`, rather than in dist. Could you try setting `main` to point to the file that `yarn build` outputs?

**Comment by jspspike** [comment] 2023-03-27 15:28
@aivLuk Looks like we haven't gotten a response from you for 2 weeks. I'll be closing this issue for now, feel free to respond and reoopen the issue in the future

**Closed by jspspike** 2023-03-27 15:28 UTC
Labels: bug, awaiting dev response
