### ISSUE TITLE
🐛 BUG: 3.69.0 `wrangler dev` Cannot find module '@cloudflare/workers-shared/dist/asset-server-worker.mjs'

### ISSUE THREAD

**Issue by MingweiSamuel** [cloudflare/workers-sdk#6430] opened 2024-08-06 16:45 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.69.0

### What version of Node are you using?

10.4.0

### What operating system and version are you using?

Windows 10

### Observed behavior
`wrangler dev` crashes on the latest uploaded version (40 min ago) 3.69.0

### Expected behavior
No crash

### Steps to reproduce
`wrangler dev` in any wrangler repo

### Please provide any relevant error logs

`wrangler dev`
```
X [ERROR] Error reloading local server: Error: Cannot find module '@cloudflare/workers-shared/dist/asset-server-worker.mjs'

  Require stack:
  - C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
      at Function.resolve (node:internal/modules/helpers:187:19)
      at buildMiniflareOptions
  (C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:162904:41)
      at #onBundleUpdate
  (C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:163010:78)
      at C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:163045:58
      at Mutex.runWith
  (C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\node_modules\miniflare\dist\src\index.js:3519:25)
      at MiniflareServer.onBundleUpdate
  (C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:163045:24)
      at C:\Users\Mingw\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:163208:33 {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Mingw\\AppData\\Roaming\\npm\\node_modules\\wrangler\\wrangler-dist\\cli.js'
    ]
  }
  ```

**Comment by MingweiSamuel** [comment] 2024-08-06 16:45
(downgrading to wranger 3.68.0, everything seems to work fine)

**Comment by irvinebroque** [comment] 2024-08-06 16:46
Dupe of https://github.com/cloudflare/workers-sdk/issues/6429 — broken release. Working on fixing now.

**Closed by irvinebroque** 2024-08-06 16:46 UTC
Labels: bug
