### ISSUE TITLE
🐛 BUG: request.signal is not aborted when the request is cancelled

### ISSUE THREAD

**Issue by ayonli** [cloudflare/workers-sdk#6467] opened 2024-08-12 06:50 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.70.0 [wrangler]

### What version of Node are you using?

22.3.0

### What operating system and version are you using?

Ubuntu 20.04.6 LTS

### Observed behavior
When the user cancels the request, the `Request.signal` property does not change and the `abort` event is not triggered.

### Expected behavior
When the user cancels the request, the `Request.signal` property should be aborted and the `abort` event shall be triggered. 

### Steps to reproduce

Code example:

```ts
function sleep(ms: number) {
    return new Promise<void>(resolve => setTimeout(resolve, ms));
}

export default {
    async fetch(req: Request) {
        req.signal.addEventListener("abort", () => {
            console.log("Request aborted!");
        });

        await sleep(5000);

        console.log("Is the request aborted: ", req.signal.aborted);

        return new Response("Hello, World!");
    }
};
```

Send the request and then abort it during the waiting period:

```sh
curl http://localhost:8787
^C
```

The server should print the following:

```txt
Request aborted!
Is the request aborted:  true
```

Instead, it printed:

```txt
Is the request aborted:  false
```

**Comment by andyjessop** [comment] 2024-08-12 11:29
This is a duplicate of #2373.

> We can investigate making it usable on server-side request objects but it is likely a lower priority and may not happen for a while

**Closed by andyjessop** 2024-08-12 11:29 UTC
Labels: bug

**Comment by irvinebroque** [comment] 2024-08-12 15:36
I don't see the connection between this and https://github.com/cloudflare/workers-sdk/issues/2373? 

Runtime issue? cc @jasnell

**Comment by jasnell** [comment] 2024-08-12 15:41
The request.signal is only used client side. It is not implemented as a way of determining if the client disconnected. We can explore that but it's not trivial. I would consider this a feature request not a bug.

**Comment by ayonli** [comment] 2024-08-13 02:24
@jasnell It would be nice if there is a way to determine that the connection is closed, and there isn't a better way to do so than utilizing the `Request.signal` property. It literally indicates that the request is aborted, and it can be passed around asynchronous operations like the `Context` object in Golang.

When the request is aborted, we can cancel some pending tasks that are still running, we can even roll back database transactions if we want.

What should I do? Do I need to open a feature request or can you reopen this issue?

**Comment by ricardopolo** [comment] 2024-11-08 10:04
if request signal is not supported what can we use to detect when the client is disconnected?

**Comment by andyjessop** [comment] 2024-11-12 15:07
> This is a duplicate of #2373.
> 
> > We can investigate making it usable on server-side request objects but it is likely a lower priority and may not happen for a while

@irvinebroque  Looks like I linked the wrong issue, sorry about that.
