### ISSUE TITLE
🐛 BUG: Python workers cannot deploy correctly when using FastAPI

### ISSUE THREAD

**Issue by MemoryShadow** [cloudflare/workers-sdk#5608] opened 2024-04-13 13:34 UTC
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

wrangler 3.50.0

### What version of Node are you using?

21.7.2

### What operating system and version are you using?

Linux Archlinux latest-lts

### Observed behavior
 When I deployed the project following the example project, wrangler told me that requirements.txt is not currently supported.    The original text I got was: "You cannot yet deploy Python Workers that depend on packages defined in requirements.txt.    Support for Python packages  is coming soon.    [code: 10021]"
When I remove requirements.txt, it says: ModuleNotFoundError: No module named 'fastapi'.

### Expected behavior
There is at least one way to properly deploy the project

### Steps to reproduce

```bash
git clone https://github.com/cloudflare/python-workers-examples.git
cd 03-fastapi
npx wrangler@latest deploy
```

### Please provide a link to a minimal reproduction

https://github.com/cloudflare/python-workers-examples/tree/main/03-fastapi

### Please provide any relevant error logs

Error 1:

[ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/xxxx) failed.

  You cannot yet deploy Python Workers that depend on packages defined in requirements.txt. Support
  for Python packages is coming soon. [code: 10021]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

======================================================================
Error 2:

[ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/xxxx) failed.

  Uncaught Error: PythonError: Traceback (most recent call last):
    File "/lib/python312.zip/_pyodide/_base.py", line 629, in pyimport_impl
      res = __import__(stem, fromlist=fromlist)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/session/metadata/main.py", line 9, in <module>
      from fastapi import Depends, FastAPI
  ModuleNotFoundError: No module named 'fastapi'

**Comment by RamIdeas** [comment] 2024-04-15 16:25
Hi @MemoryShadow! As the error message upon deploy states, you cannot yet deploy Python Workers that depend on packages for now. For local development, they are supported, therefore there is no work in wrangler to track so I will close this issue. Support for Python packages in the platform is coming soon 👍

**Closed by RamIdeas** 2024-04-15 16:25 UTC
Labels: bug

**Comment by christianversloot** [comment] 2024-05-02 09:41
Hi @RamIdeas - sorry for commenting here while the issue is closed, wanted to +1 as we are also dependent on package (specifically, `aiohttp`) for deployment of a Worker.

Does the team have an estimation of _soon_? Before summer? After summer?
Thanks!

**Comment by laike9m** [comment] 2024-06-11 02:56
This confuses me. If `wranger deploy` doesn't work for Python worker in many cases, how am I supposed to deploy it?

**Comment by RamIdeas** [comment] 2024-06-19 16:51
The [docs](https://developers.cloudflare.com/workers/languages/python/packages/#supported-packages) describe a bunch of packages provided by the runtime which you can use.

@christianversloot `aiohttp` is also mentioned on that page under HTTP Client Libraries

**Comment by oaigudmundsson** [comment] 2024-06-20 07:56
So, why have these tutorials ?
https://developers.cloudflare.com/workers/languages/python/packages/fastapi/
https://github.com/cloudflare/python-workers-examples/tree/main/03-fastapi

If it's not even run, why bother to add?

**Comment by christianversloot** [comment] 2024-06-20 10:56
I've tried deploying in multiple ways...

1. Importing `aiohttp` without `requirements.txt` - deploy fails because `aiohttp` cannot be found.
2. Importing `aiohttp` with `requirements.txt` - error message about `requirements.txt` not being supported.
3. Importing `aiohttp` via `pyodide` - deploy fails because packages are encoded within the environment.

In other way, there seems no way to use things right now, similar as to what @oaigudmundsson had already wondered.

For now I've had no other option to convert my worker into a JS based one.

**Comment by Yutsuro** [comment] 2024-06-23 15:25
Not only can't it be deployed to Workers, but the FastAPI demo doesn't even work locally. What is the purpose of its tutorial?

**Comment by SZRabinowitz** [comment] 2024-06-24 16:14
It doesnt even work in localhost. And it's the official cloudflare example...

**Comment by hoodmane** [comment] 2024-09-12 09:04
Running `npx wrangler@latest dev` on the fastapi example works fine for me currently. If anyone still cannot make `wrangler dev` work on these examples, can you run `wrangler version` and post the version number?

**Comment by AhanR** [comment] 2024-11-05 20:26
Hi there, I'm facing a similar issue with the requirements:

I'm using the wrangler version:  ⛅️ wrangler 3.84.1

### The error message that I receive:
`" found in requirements.txt. Note that requirements.txt should contain package names only, not version specifiers.`

I have added a few requirements of my own as well but can you please tell me why the server is not working locally either?
