### ISSUE TITLE
🐛 BUG: npm create cloudflare@latest -- --framework angular fails on node LTS/jod (v22.11.0)

### ISSUE THREAD

**Issue by neomax7** [cloudflare/workers-sdk#7340] opened 2024-11-25 20:10 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

wrangler@3.90.0

### What version of Node are you using?

v22.11.0

### What operating system and version are you using?

Mac sequoia 15.1.1

### Observed behavior
Please describe.
npm create cloudflare@latest -- --framework angular 
fails with error on sqllite3 installation
when executed on node v22.11.0 (lts/jod)

here is snippets of error
`519 verbose pkgid better-sqlite3@8.7.0
520 error code 1
521 error path /Users/jongsikkim/code/angular-challenge/node_modules/better-sqlite3
522 error command failed
523 error command sh -c prebuild-install || node-gyp rebuild --release
524 error TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
524 error   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
524 error   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
524 error   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
524 error   LIBTOOL-STATIC Release/sqlite3.a
524 error   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
524 error rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
525 error prebuild-install warn install No prebuilt binaries found (target=22.11.0 runtime=node arch=arm64 libc= platform=darwin)`

### Expected behavior
Please describe.
finish gracefully

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

npm create cloudflare@latest -- --framework angular 
using node v22.11.0 regardless of OS

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by emily-shen** [comment] 2024-12-16 14:12
Hiya, closing as this seems to have been fixed recently, and I can't reproduce it any more, but do let us know if this resurfaces :)

**Closed by emily-shen** 2024-12-16 14:12 UTC
Labels: bug
