### ISSUE TITLE
🐛 BUG: 'open a browser' shortcut opens custom domain, if present, in wrangler dev

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#2691] opened 2023-02-08 13:55 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

MacOS

### Describe the Bug

When using a Worker that has a custom domain, the `open a browser` shortcut will open the custom domain (i.e `https://custom.example.com:8787`) which will timeout.

Repro:

`wrangler.toml`

```toml
name = "custom-repro"
main = "src/index.ts"
compatibility_date = "2023-02-08"

[route]
pattern = "custom.example.com"
custom_domain = true
```

Before the script is uploaded to the edge preview (before the `Total Upload` output), `b` will open `http://127.0.0.1:8787` as expected - after that, it will open your custom domain.

**Comment by KianNH** [comment] 2023-02-08 14:03
In `packages/wrangler/src/dev/dev.tsx`:

https://github.com/cloudflare/workers-sdk/blob/dae0a2d1fd0f8526d87e834180f35da54b0ce443/packages/wrangler/src/dev/dev.tsx#L564-L571

![image](https://user-images.githubusercontent.com/94662631/217551393-93dbf30c-e0e1-46b4-b82a-d2e298bd6bc8.png)

**Comment by threepointone** [comment] 2023-02-08 17:50
Can confirm this, has broken my dev workflow. Seems bad.

**Comment by penalosa** [comment] 2023-02-08 18:03
Duplicate of https://github.com/cloudflare/workers-sdk/issues/2610, but yes, this is a bug we should fix. As a workaround, opening `http://127.0.0.1:8787` directly in your browser should work.

**Closed by penalosa** 2023-02-08 18:03 UTC
Labels: bug
