### ISSUE TITLE
🐛 BUG: wrangler deploy gets error workers.api.error.unauthorized [code: 10023] when trying to create kv:namespace binding

### ISSUE THREAD

**Issue by tomasbilos** [cloudflare/workers-sdk#5649] opened 2024-04-18 13:43 UTC
### Which Cloudflare product(s) does this pertain to?

KV

### What version(s) of the tool(s) are you using?

3.51.0

### What version of Node are you using?

v18.20.2

### What operating system and version are you using?

WSL Ubuntu

### Observed behavior
`yarn wrangler deploy` ends with error when deploying worker with KV namespace binding defined in wrangler.toml

`workers.api.error.unauthorized [code: 10023]`

### Expected behavior

`yarn wrangler deploy` deploys worker and create binding to the KV namespace

### Steps to reproduce
My worker:
```
export default {
  async fetch(
    request: Request,
    env: { KV_BINDING: KVNamespace }
  ): Promise<Response> {
    console.log(await env.KV_BINDING.list());
    return new Response("OK");
  },
};
```

My wrangler.toml
```
name = "origin"
main = "src/index.ts"
compatibility_date = "2024-04-04"
account_id = "xxx"

kv_namespaces = [
  { binding = "KV_BINDING", id = "xxx" }
]
```

Command that fails is `yarn wrangler deploy`.

```
 ⛅️ wrangler 3.51.0
-------------------
Your worker has access to the following bindings:
- KV Namespaces:
  - MY_BINDING: xxx
Total Upload: 0.23 KiB / gzip: 0.20 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/origin) failed.

  workers.api.error.unauthorized [code: 10023]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I remove `kv_namespaces` from `wrangler.toml` I am able to deploy the worker.

### Please provide any relevant error logs

```
--- 2024-04-18T13:35:08.170Z debug
-- END CF API RESPONSE
---

--- 2024-04-18T13:35:08.182Z log
Your worker has access to the following bindings:
- KV Namespaces:
  - MY_BINDING: xxx
---

--- 2024-04-18T13:35:08.183Z log
Total Upload: 0.23 KiB / gzip: 0.20 KiB
---

--- 2024-04-18T13:35:08.185Z debug
-- START CF API REQUEST: PUT https://api.cloudflare.com/client/v4/accounts/xxx/workers/scripts/origin?include_subdomain_availability=true&excludeScript=true
---

--- 2024-04-18T13:35:08.185Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-04-18T13:35:08.185Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-04-18T13:35:08.185Z debug
-- END CF API REQUEST
---

--- 2024-04-18T13:35:09.729Z debug
-- START CF API RESPONSE: Unauthorized 401
---
```

**Comment by RaresAil** [comment] 2024-05-20 09:41
@tomasbilos i had the same issue until i added to the token the permission for KV edit

**Comment by threepointone** [comment] 2024-06-15 08:41
@tomasbilos were you using a custom API key when developing/deploying? Because when using oauth login, we do support kv reads / bindings. Alternately, can you check whether you have the correct kv namespace id in your wrangler.toml?

**Comment by petebacondarwin** [comment] 2024-06-17 18:35
Closing as not reproducible and probably a configuration issue with auth token.

**Closed by petebacondarwin** 2024-06-17 18:35 UTC
Labels: awaiting reporter response, bug

**Comment by sunainha-vijay** [comment] 2024-06-29 16:03
> @tomasbilos i had the same issue until i added to the token the permission for KV Storage Edit

yes worked for me as well, thanks:)
