### ISSUE TITLE
🐛 BUG: Can't opt in to Durable Objects

### ISSUE THREAD

**Issue by BuGlessRB** [cloudflare/workers-sdk#3195] opened 2023-05-11 20:45 UTC
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

Linux Debian

### Describe the Bug

```
Your worker has access to the following bindings:
- Durable Objects:
  - COUNTER: Counter
- KV Namespaces:
  - merchantcachekv: 0240727990c343bdad78ab9a
- R2 Buckets:
  - merchantcacher2: merchantcache
Total Upload: 2.22 KiB / gzip: 0.84 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/284f5694e83a40fb219e4132ee141b83/workers/scripts/merchantcache) failed.

  In order to use Durable Objects, you must agree to pricing at
  https://dash.cloudflare.com/284f5694e83a40fb219e4132ee141b83/workers/overview?enable-durable-objects
  [code: 10084]
```
  
That's what I get when trying Durable Objects, even though I have usage based billing turned on on "Cubic Circle" and it is supposed to include Durable Objects.

**Comment by IgorMinar** [comment] 2023-05-12 10:48
This seems to be related / duplicate of https://github.com/cloudflare/workers-sdk/issues/3185.

We are looking into it and will fix shortly. Apologies for the trouble.

**Comment by petebacondarwin** [comment] 2023-05-12 11:44
An internal fix for this should be rolling out later today once USA is online.

**Comment by admah** [comment] 2023-05-23 03:44
This fix has been released. Please reopen if you continue to experience this issue.

**Closed by admah** 2023-05-23 03:44 UTC
Labels: bug
